### ISSUE TITLE
GPAD output for model 586fc17a00001662 not being generated

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/minerva#100]
Hi,

I've been working on a new model this morning:

http://noctua.berkeleybop.org/editor/graph/gomodel:586fc17a00001662

and hoping to take a look at the GPAD output here:

http://build.berkeleybop.org/job/export-lego-to-gpad-sparql/lastSuccessfulBuild/artifact/legacy/gpad/

but I don't see anything new being generated.

I also don't see the model listed here:

https://github.com/geneontology/noctua-models/tree/master/models

If the model is not being saved to the master/models directory does that explain why I can't see a GPAD?  Is there something else I need to be doing?

Thanks,
--Kimberly

**Comment by balhoff** [comment]
@vanaukenk you're correct, the model needs to be on GitHub first. @kltm it looks like the GH commit is a week behind, does it need to be nudged?

**Comment by kltm** [comment]
@vanaukenk 
Apologies--I'm not sure what happened here. There are essentially a couple of "secret" users that are used for things like dumping the files to disk from minerva and they were logged out. My only guess is that somebody (me being the most likely culprit) was demoing something during biocuration using one of the secret users and logged out. I don't recall doing that, and the last flush was on Friday, which doesn't make a lot of sense,but I wasn't firing all pistons towards the end either.
This should now be fixed, flushed, and updated in like half an hour.

**Comment by kltm** [comment]
This is now being blocked by the fact that http://geneontology.org/ontology/imports/x-disjoint.owl can no longer be found, so the job cannot be run. Initially found by @jnguyenx, and reported by email to @cmungall directly.

**Comment by balhoff** [comment]
Shouldn't be an issue any longer.
