### ISSUE TITLE
Add an API call that returns configuration details, including reasoner

### ISSUE THREAD

**Issue by cmungall** [geneontology/minerva#104]
- reasoner + approach in use (arachne, slme+elk, etc) (easy)
 - list of ontologies in import chain, plus versionIRIs (easy)
 - stats on average reasoner invocation time, number of invocations (will take a bit of extra work)

The noctua client can simply get this as a json blob through barista and display as a json blob for debugging, no fanciness necessary

**Comment by kltm** [comment]
Honestly, I'd prefer not having an API call for the versioning, but rather add it to the current "--version" information.
For the live stats, it would be nice to follow the same pattern as:
http://barista.berkelybop.org/status
http://noctua.berkeleybop.org/status

**Comment by cmungall** [comment]
Should we make a swagger definition for these? Not clear what kicks are

**Comment by kltm** [comment]
Just toy demonstration toy.

**Comment by kltm** [comment]
A swagger definition could be made, but it wouldn't be usable without a fair change in plumbing for the three components as they are not written up from swagger tooling.

**Comment by kltm** [comment]
As well, these are not particularly supposed to be public rest APIs, but rather programming APIs.

**Comment by cmungall** [comment]
swagger can be authored directly rather than generated from inline annotations.

Long term goal: all web APIs should have operations and payloads documented using a standard framework, e.g. openAPI/swagger.

**Comment by kltm** [comment]
I'd agree in principle for end-user APIs (e.g. AmiGO, Biolink)--I think it's a great idea and solid format. That said, I think there are some important caveats.
First, I think this makes less sense for programming (I do there there is a distinction) and diagnostic "APIs" (e.g. minerva line or something that is intended for nagios to consume).
As well, and unfortunately I cannot find an issue to reference, there is overhead for bolting these things on after the fact. The tooling for JS (as of December when I tried to apply the node/express version to the amigo api) is very weak and has serious issues for after-the-fact adoption, being really tooled to be used within their larger swagger/express framework. The python environment (at that point) seemed much more mature and flexible in this regard; I have no idea about java.

Now, all that said, it depends on what we are trying to accomplish. It would seem to be that need a way for minerva to report what is loaded, the reasoner, and the code point largely for debugging--I'd think these are probably not generally useful, so having them available from the command line (possibly invoked for the noctua client to pick up) would be fine.
The reasoner usage might be useful for tying things back to load in nagios and graylog, so it may be that we'd want to actually have that in something simple for the former or just directly in the logging.

**Comment by goodb** [comment]
http://noctua-dev.berkeleybop.org:6800/status

**Comment by kltm** [comment]
@goodb Truly lovely.

**Comment by kltm** [comment]
Moving this straight to "Done" so as not to confuse @vanaukenk

**Comment by vanaukenk** [comment]
@kltm @cmungall @goodb 

Do you think we can close this ticket?  Thx.

**Comment by lpalbou** [comment]
@kltm regarding yesterday discussion on a standalone landing page, seems like it could use those configs too as runtime variables

**Comment by kltm** [comment]
@lpalbou The runtime environment is not currently available there. We can continue using the current infrastructure for now and revisit it when we start doing larger refactors.
