### ISSUE TITLE
Ensure that minerva instances do not start with stale ontologies

### ISSUE THREAD

**Issue by cmungall** [geneontology/minerva#107]
The safest way to start minerva is by providing a single ontology IRI that resolves to the root of the import chain, e.g. http://purl.obolibrary.org/obo/go/extensions/go-lego.owl

One drawback of this approach is that start-up can be slow due to network I/O and is not resilient to network errors.

To get around this, we can use a well-documented and robust mirroring strategy. For example [robot mirror](https://github.com/ontodev/robot/blob/master/examples/README.md#mirroring). Note that care must be taken to ensure that the cache does not get stale. For example, the mirror can be regenerated by a jenkins job on a weekly or daily basis.

Things to avoid

 - use of svn. See https://github.com/geneontology/noctua/issues/434

**Comment by cmungall** [comment]
minerva still starting up with

```
-c /home/swdev/local/src/svn/geneontology.org/trunk/ontology/extensions/catalog-v001.xml
```

**Comment by cmungall** [comment]
Aside from the tests, are any of the following used: 

https://github.com/geneontology/minerva/search?utf8=%E2%9C%93&q=catalog-v001.xml&type=

**Comment by cmungall** [comment]
I think this is what needs fixed:

 * https://github.com/geneontology/operations/blob/93dc5ca44a064e72b8f100cdf6340d707352b0be/templates/noctua/noctua-aws-startup.yaml#L74-L77

Other uses of catalogs:

I believe this is deprecated/unused: should we mark/remove?

 * https://github.com/geneontology/go-site/blob/master/configurations/supervisord/minerva.conf


## amigo confs

I see we're also potentially using catalogs for noctua

 * https://github.com/geneontology/amigo/search?utf8=%E2%9C%93&q=catalog-v001.xml&type=
 * https://github.com/geneontology/operations/search?utf8=%E2%9C%93&q=catalog-v001.xml&type=
 
the amigo loads seem fine, not sure why the minerva load seems stale

**Comment by kltm** [comment]
The supeevisord may be outdated, but it should likely be switched to operations.

**Comment by kltm** [comment]
As well, we have not restarted minerva for a while.

**Comment by cmungall** [comment]
__FALSE ALARM__

In #414

I made this edit to svn:

http://viewvc.geneontology.org/viewvc/GO-SVN?view=revision&revision=43381

The catalog is actually silent:

http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/ontology/extensions/catalog-v001.xml?view=markup

so we should remove the catalogs from the yaml anyway to get rid of a pointless dependency. But adding the svn catalog  has no effect!
