### ISSUE TITLE
Arachne (?) does not seem to work well with undo / redo functionality

### ISSUE THREAD

**Issue by kltm** [geneontology/minerva#108]
Arachne (?) does not seem to work well with undo / redo functionality. For example:

- start a new model
- add `nucleus` individual
- add `chromosome` individual
- add `occurs_in` from n -> c
- add `occurs_in` from c-> n
- turn on reasoner
- model gets marked as inconsistent
- remove `occurs_in` from n -> c
- remove`occurs_in` from c-> n
- model gets marked as consistent
- undo remove `occurs_in` from c -> n
- undo remove `occurs_in` from n -> c
- *model still marked as consistent*

In fact, I do not seem to be able to achieve an inconsistent state in the model again after performing the undo.

I'm not sure if the reasoner system was always like this or Arachne-specific.

I'll have the new noctua client out later tonight for other people to test (https://github.com/geneontology/noctua/issues/436).

**Comment by balhoff** [comment]
Testing locally, I think I'm seeing the same issue with ELK.

**Comment by kltm** [comment]
Okay, good to know. Do you have a feel for why this is happening? Depending, we'll have to be very ginger, and maybe do more experiments to see if any undo/redo at all affects the reasoner, or if only when dealing with inconsistent states.
If it cannot be worked around, we'll have to make the choice os undo/redo vs. reasoners, and I think we already know the answer there...

**Comment by cmungall** [comment]
Is this to do with incremental reasoning?

I don't see any cases of `flush()` being called on the reasoner.

Have you tried switching it off and switching it on again?

(presumably creates a new instance of the reasoner)

**Comment by kltm** [comment]
Yes, from my experiments last night, switching it "on" and "off" again does not seem to solve the problem. However, we should probably be more exhaustive in the testing in general if it is not obvious what is going on here.

**Comment by balhoff** [comment]
This should be fixed after #114 is merged. It doesn't look like incremental reasoning is used in Minerva. There is a listener for model changes which creates a new reasoner each time any changes have happened. Undo/redo changes weren't being processed via the path that led to this listener.

**Comment by kltm** [comment]
Fix now out in the wild; will reopen if something goes wrong.
