### ISSUE TITLE
GPAD file contains causal function annotations

### ISSUE THREAD

**Issue by ukemi** [geneontology/minerva#109]
With the new reasoner, the GPAD now contains annotations for functions that are causally upstream of other functions. For example in this model of a glycolytic process:

http://noctua.berkeleybop.org/editor/graph/gomodel:55c3ef4c00000001

Gene products with a molecular function are given annotations that are causally upstream of other molecular functions get an annotation like this:

MGI	MGI:97552	acts_upstream_of	GO:0004743	ISBN:0-87901-047-9	ECO:0000033			20150811	GO_Noctua		contributor=http://orcid.org/0000-0001-7476-6306|noctua-model-id=gomodel:55c3ef4c00000001

This also has consequences with respect to evidence in the same way that it does for complex models that chain biological processes. In the case above, the evidence for the annotation is the evidence that the activity of Eno1 is upstream of pyruvate kinase and has nothing to do with the activity of Pgam1. 

Evidence issues aside, the base annotation correct and is really powerful, but will be misleading for anyone who picks up the GPAD file and ignores the qualifiers. 

The catch-22 is this. In the case of causal annotations to biological processes, I'm pretty sure that some groups want to retain them and some groups don't. Does it make sense to create the files and then have steps that will filter annotations before they are loaded into the respective resources? Do we want to do this in the repository or have it done by individual groups as they load the files?

**Comment by balhoff** [comment]
@ukemi is this ticket obsolete now?

**Comment by ukemi** [comment]
Unfortunately not. I have created a simpler model:

http://noctua.berkeleybop.org/editor/graph/gomodel:5a7e68a100000739


This annotation has incorrect evidence:

Gpi1 Mmus | acts_upstream_of | fructose-bisphosphate aldolase activity | PMID:0000004 | sequence similarity evidence used in manual assertion | UniProtKB:19191 |   | 20180327 | GO_Noctua |   | noctua-model-id=gomodel:5a7e68a100000739\|contributor=http://orcid.org/0000-0001-7476-6306

There is no single piece of evidence that Gpi1 acts upstream of 'fructose-bisphosphate aldolase activity'. It is based on an evidence chain that links through the 6-PFK activity.

**Comment by balhoff** [comment]
Oh I see, I was focusing on the qualifiers, which seem to be accepted now. Can we just extend GPAD to support compound evidence and be done with it? :-P

**Comment by ukemi** [comment]
I still think that for anyone picking up these annotations and ignoring the qualifiers, having these in the file would be very misleading. This isn't such a problem with process annotations, but to me it is a real concern with function annotations. I would vote not to include them in the gaf, but we should see what @vanaukenk, @pgaudet and @thomaspd think. I don't think the final say should be mine. Maybe we can take a look on the call today.

**Comment by thomaspd** [comment]
I agree that we shouldn't put downstream effects on MFs in the GAFs/GPADs.  In general, I'm for minimizing the indirect annotations inferred from the GO-CAM models, but I think the qualifiers are an acceptable solution for indirect BP annotations.

**Comment by vanaukenk** [comment]
This issue appears to have been fixed.
