### ISSUE TITLE
Allow to create individual from IRIs (such as PubMed ids) or plain strings

### ISSUE THREAD

**Issue by jnguyenx** [geneontology/minerva#11]
A reference might not exclusively be a PubMed id, it might come from an unknown source.

**Comment by kltm** [comment]
I hadn't realized this restriction existed. Are you given an error is some cases?

**Comment by jnguyenx** [comment]
Here's the error with a random string:
"Could not successfully handle batch request. Exception:
org.geneontology.minerva.MolecularModelManager$UnknownIdentifierException.
Could not retrieve a class for id: made_up_reference"
Note that it also throws an error when one tries to use whitespaces.

**Comment by hdietze** [comment]
A custom IRIs such as PMID:00000 can now be requested during the creation of an individual (add) using the parameter: `individual-iri`

As we are now using proper CURIE handling, short and long forms of IRIS are now resolved to the same IRI on the server, for example:
'PMID:00000' <=> '<http://www.ncbi.nlm.nih.gov/pubmed/00000>'

**Comment by kltm** [comment]
Have added what should be that API change to use this: https://github.com/berkeleybop/minerva-requests/commit/6c1f49d4119d294ac0312a5ec89db793dcc925f4
Still needs testing--will update noctua-repl to test.
