### ISSUE TITLE
CC (part_of) annotations not showing up in GPAD inferences

### ISSUE THREAD

**Issue by cmungall** [geneontology/minerva#111]
http://noctua.berkeleybop.org/editor/graph/gomodel:591f58ab00000021

![image](https://cloud.githubusercontent.com/assets/50745/26412450/ae3e661c-405d-11e7-866b-0534a6d1f804.png)

The CC annotation (9+0 motile cilium) not showing up here:

http://noctua.berkeleybop.org/workbench/annpreview/?model_id=gomodel:591f58ab00000021

**Comment by balhoff** [comment]
This rule was previously hardcoded in Minerva but is now included with RO. For some reason the rule in RO is not working or not being used (confirmed locally - it works again if the hardcoded version is added back).

**Comment by balhoff** [comment]
I believe this is the problem: https://github.com/balhoff/owl-to-rules/blob/46507bf5577340790d2865970f6d3eb6f827039a/src/main/scala/org/geneontology/jena/OWLtoRules.scala#L39

SWRL rules are not being grabbed from imports. Will fix.

**Comment by balhoff** [comment]
https://github.com/balhoff/owl-to-rules/commit/99bdcd8e432cca7a2070114438233616911bb752

**Comment by balhoff** [comment]
@kltm this should be fixed if you update Noctua to the latest Minerva or [tag 0.6.1](https://github.com/geneontology/minerva/releases/tag/v0.6.1).

**Comment by kltm** [comment]
Restarted with master build. Somebody may want to check and close if corrected.

**Comment by balhoff** [comment]
Thanks! Looks good.
