### ISSUE TITLE
RO:0002612 ; axiom has evidence is not being used to create evidence, <http://geneontology.org/lego/evidence> is

### ISSUE THREAD

**Issue by dougli1sqrd** [geneontology/minerva#115]
The documentation for minerva says that we use RO:0002612 axiom has evidence to link evidence to a statement. However in practice minerva apparently uses the <http://geneontology.org/lego/evidence> term. Should we change minerva to generate the documented RO:0002612 instead? Or am I missing something about the model?

**Comment by balhoff** [comment]
I think this is planned but hasn't happened yet. It would be good to know what the prerequisites should be for switching. I'll close this since we already have #13, but if funding works out for minerva work in the near future maybe we should look at this.

**Comment by kltm** [comment]
Actually, before @hdietze left, we believe we made the changes needed in minerva to support this; if fact, there should be a couple of test models that demonstrate the differences.
That said, the client and client handling code have not been switched and need to be reworked a bit before this can be fully supported: 
https://github.com/geneontology/noctua/issues/141
