### ISSUE TITLE
Is "gomodel" namespace/prefix an issue as Noctua gets used more broadly?

### ISSUE THREAD

**Issue by kltm** [geneontology/minerva#116]
This question came up in a discussion about Noctua in the context of Planteome. Currently, all produced models will generate ids like gomodel:203974209734902. Given that GO and Planteome have their own Noctua silos, this could cause collisions. For example, a resource that dealt with both Planteome and GO annotations would not be able to disambiguate.

Currently, AFAIK, this is fairly hardwired into Minerva. Would we want something where this is specified at runtime?

At this point, it does not seem urgent, but may eventually cause nastiness.

@cmungall @balhoff @elserj

**Comment by cmungall** [comment]
It's configurable: https://github.com/geneontology/minerva/blob/a90ec00b711c0c198fbdee64135024d71da156e0/minerva-cli/src/main/java/org/geneontology/minerva/cli/MinervaCommandRunner.java#L102-L104

But this hasn't been fully tested as we've had no need. There may be some hardwiring in the sparql queries but should be easy to config. I suggest we do any experiments in the context of planteome

**Comment by kltm** [comment]
Great--I didn't know or forgot that was there. @elserj There may also be some assumptions about this in other parts of Noctua as well.

**Comment by balhoff** [comment]
I started a configurability doc here: https://github.com/geneontology/minerva/blob/master/configuration.md

**Comment by kltm** [comment]
Cheers!
