### ISSUE TITLE
Proposal: Use the model-level providedBy as a default if there is no providedBy on the evidence

### ISSUE THREAD

**Issue by cmungall** [geneontology/minerva#119]
I think I would be able to implement this. @balhoff and @kltm - do you see any reason not to do this?

@vanaukenk and @ukemi - does this seem OK as a policy decision?

**Comment by balhoff** [comment]
I don't see a problem with this. I can implement as soon as we decide how to treat multiple providedBy values.

**Comment by cmungall** [comment]
Was there a separate ticket on the multiple providedBys?

I am in favor of simple concatenation, and treating as cardinality=1, a "joint group". According to
https://github.com/geneontology/go-annotation/blob/master/specs/gpad-gpi-1_2.md

 - the field must be alphanumeric or '-'s and '_'s. 
 - it must be registered

We wouldn't register the joint ones, but I think as a first pass if we emit GPAD with this minor violation, people can then decide what they want to do with these (which I assume will be in the minority)

**Comment by kltm** [comment]
I'm sure there was one around somewhere. At some point in some medium, I half seriously (now pretty seriously) proposed that if the cardinality-1 was set, it would probably be cleaner to use a JSON blob--we could load it with more as we go, not worry about ordering issues, and still use grep.

**Comment by balhoff** [comment]
It looks like a URI or CURIE would violate the constraints on that field. How would you like to see the values?

**Comment by ukemi** [comment]
How does the model-level group get assigned? It seems that this default would be ok and the evidence-level group assignment would replace it. 

I can't remember a case where I would want to be associated with more than one group for a single annotation,but I think @vanaukenk had some. We should ask about this on an annotation call. We need to be sure to test all of the different parameters and see what comes out in the gpad.

**Comment by ukemi** [comment]
Related ticket:
https://github.com/geneontology/noctua/issues/458

**Comment by balhoff** [comment]
I think I've introduced a red herring with the multiple providedBy issue. I think there can be multiple providedBys on an edge (if different people add the edge, add evidences, etc.), but actually there shouldn't be multiple on an evidence, which is the level associated with a single annotation. So we just need to decide how to format the value and then I'll go ahead an implement this.

**Comment by vanaukenk** [comment]
Yes, I think using a model-level providedBy, concatenated if necessary, seems a reasonable default approach.  

Wrt multiple groups for a single annotation, I was thinking more about how we would handle evidence when a model uses imported legacy annotations but a curator adds edges while working in Noctua.  I'm testing one of those now.

**Comment by balhoff** [comment]
@vanaukenk I am a bit unclear on how multiple contributors or providers could get attached to a single evidence. I am doing some queries in the graph store and do see some evidences with more than one contributor. I need to look at how Minerva works to figure out if this is expected. The examples I looked at so far are not typical models, e.g. [Canonical Wnt from seeding](http://noctua.berkeleybop.org/editor/graph/gomodel:5667fdd400000892).

**Comment by vanaukenk** [comment]
I just tried a test model, but when I imported an MF annotation using the function companion, the original contributor of that manual annotation (BHF-UCL) was not preserved in the Noctua evidence, even though the original PMID was.  I am now listed as the sole contributor for that annotation, even though I only imported it.  
Maybe I am conflating two separate things here, but it seems that both the originator of the annotation and the curator making the Noctua model should get credit for providing the annotation in the Noctua-derived GPAD.
Here is the simple model I made:
http://noctua.berkeleybop.org/editor/graph/gomodel:595a9ee700000305

**Comment by ukemi** [comment]
We just mentioned this at our group meeting. It's important that imported annotations are not treated as new. Therefore the group with which they were originally associated should be the the one that is retained. I had mentioned being able to tell the difference between created and modified, but I'm not sure how important that is.

**Comment by ukemi** [comment]
Thining more, there is the complexity of importing an annotation and then adding 'annotation extension' data to it. In that case, do we want to retain only the original 'duplicate' annotation or do we want to create a new annotation with the additional extensions.

**Comment by vanaukenk** [comment]
@ukemi 
Yes, that's exactly what I was trying to test.  I imported an MF annotation and then just added an occurs_in 'annotation extension'.  
In that case, it seems that if we include the annotation extension with the MF annotation, then both groups should get credit in the Noctua-derived GPAD.
For the CC annotation, however, only the Noctua curator would get credit for that specific line of annotation.
Does that make sense?

**Comment by ukemi** [comment]
Makes perfect sense to me as long as we want to keep the extended annotation. But what should we use as evidence for the extended annotation? The original evidence isn't entirely correct. If you go back and read the original paper, it might not support the extended annotation.

**Comment by vanaukenk** [comment]
Yes, @ukemi; you're right.  If the evidence is not the same, and I would be willing to bet that in many cases it's not, then the paper evidence for the extended MF annotation is not complete.  In which case, we should probably not include the AE.

**Comment by cmungall** [comment]
On 6 Jul 2017, at 7:24, David Hill wrote:

> Thining more, there is the complexity of importing an annotation and 
> then adding 'annotation extension' data to it. In that case, do we 
> want to retain only the original 'duplicate' annotation or do we want 
> to create a new annotation with the additional extensions.

In this case, full provenance would be tracked in the Noctua model, but 
as far as the GAF is concerned it would look like the full annotation, 
including extension came from the source. I think that is as good as we 
can hope for with GAF.

If people *really* want to see their own group on the exported GAF it's 
always possible to manually go in and change the providedBy.

**Comment by balhoff** [comment]
@cmungall how should the provider be rendered in the GPAD? I believe IRIs and CURIEs would violate the spec. If that doesn't matter, should we just use the full IRI? I don't believe the provider label is available within Minerva presently. Even if it were, using the label would seem to defeat the purpose of having an identifier.

**Comment by kltm** [comment]
@balhoff I think we also have that in https://github.com/geneontology/noctua/issues/380

**Comment by cmungall** [comment]
An IRI or a CURIE for assigned by in GPAD would make a lot more sense, but would require a lot of coordination with @tonysawfordebi MODs etc as the use of 'labels' like MGI, UniProtKB is fairly ossified.

**Comment by balhoff** [comment]
Okay, it sounds like I will need to hold off here until I can use the label, after https://github.com/geneontology/noctua/issues/380.
