### ISSUE TITLE
Another property chain to fix

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/minerva#124]
Hi,

Looking at the Inference Explanations for the Wnt inference model

http://noctua.berkeleybop.org/editor/graph/gomodel:5966411600000538

( ?x1 negatively_regulates ?x2 ) ∧ ( ?x2 negatively_regulates ?x3 ) → ( ?x1 negatively_regulates ?x3 )

This property chain is incorrect.  

negatively_regulates over negatively_regulates should yield positively_regulates.

This should fix the resulting inference that WNT1 is involved_in_negative_regulation of canonical Wnt signaling pathway.

Note that once we also remove the regulates over part_of yields regulates relations (already a ticket), then that will also fix the inference that WNT1 is involved _in_positive_regulation of canonical Wnt signaling pathway.

Thx.

**Comment by balhoff** [comment]
Thanks @vanaukenk! This is a result of `negatively regulates` being marked as a Transitive property in RO. Clearly this is wrong. I opened an issue with RO: https://github.com/oborel/obo-relations/issues/182

**Comment by balhoff** [comment]
This is fixed in the RO source now.

**Comment by cmungall** [comment]
Jim's fix is merged and in the latest release of RO, which will be seen
next time minerva restarts

**Comment by kltm** [comment]
Minerva has just been restarted.

**Comment by balhoff** [comment]
The unwanted property chain is still there. I'm guessing GO's `ro_import.owl` needs updating.
