### ISSUE TITLE
Remove relations from GPAD qualifiers list

### ISSUE THREAD

**Issue by balhoff** [geneontology/minerva#126]
From today's Noctua call I have the impression that it would be preferable to reduce the allowable GPAD relations, possibly only to:

* enables
* involved_in
* part_of

The other relations currently allowed are:

* acts_upstream_of
* acts_upstream_of_or_within
* involved_in_regulation_of
* involved_in_negative_regulation_of
* involved_in_positive_regulation_of
* involved_in_or_involved_in_regulation_of

Should these be eliminated? @thomaspd @vanaukenk @ukemi @cmungall

The list is defined here: https://github.com/geneontology/minerva/blob/master/minerva-converter/src/main/resources/org/geneontology/minerva/legacy/sparql/gpad-basic.rq#L26-L36

**Comment by ukemi** [comment]
Hi @balhoff 

I think we only want to disable the output of:

- involved_in_negative_regulation_of
- involved_in_positive_regulation_of
- involved_in_or_involved_in_regulation_of

with the idea that a curator should request an instantiated term in the ontology if they do not generate an annotation to one of the 'regulation of x' terms.

We want to retain annotations with the:

- enables
- involved_in
- part_of
- acts_upstream_of
- acts_upstream_of_or_within

It seems that there are also some that are missing. We now have 'causally upstream of, positive effect' and 'causally upstream of, negative effect', but it appears that the corresponding qualifiers are missing:
enables o 'causally upstream of, negative effect'->acts_upstream_of_negatively
enables o 'causally upstream of, positive effect'->acts_upstream_of_positively

**Comment by dosumis** [comment]
@ukemi - agree with all.  Missing qualifier:  contributes_to
