### ISSUE TITLE
Missing inferred annotations

### ISSUE THREAD

**Issue by dosumis** [geneontology/minerva#131]
We now have rules in place to ensure inference of 'enables'  from component functions and inference of 'contributes_to' for parts of complexes.  These annotations are not yet showing up in GPAD inference.

e.g.  this should have ATP2a1 enables 'ATPase activity' :

http://noctua.berkeleybop.org/editor/graph/gomodel:5970219a00000402
http://noctua.berkeleybop.org/workbench/annpreview/?model_id=gomodel:5970219a00000402

This inference is a required for the majority of patterns in MF refactoring. I assume this inference  is not showing up because of a need for annotation of the enabled_by/enables edge. 

@ukemi  @vanaukenk  - if this is the case - any suggestions for how best to fix?  Ideal would be to pull annotation from the enables_by edge on compound MF of which this is a part but that may be hard to achieve.

This should have a number of contributes_to annotations including "GSK3B contributes_to 'protein serine-threonine kinase activity'"

http://noctua.berkeleybop.org/editor/graph/gomodel:596ef51500000088
http://noctua.berkeleybop.org/workbench/annpreview/?model_id=gomodel:596ef51500000088

I assume these are not showing up because the relation needs to be green-lighted as a qualifier.

CC @ukemi @cmungall @vanaukenk

**Comment by balhoff** [comment]
@dosumis your `ATP2a1 enables 'ATPase activity'` inference is happening, see here: http://noctua.berkeleybop.org/workbench/inferredrelations/?model_id=gomodel:5970219a00000402&barista_token=

I think you're right that it would show up in the annotation preview if the evidence requirements were met.

**Comment by balhoff** [comment]
@dosumis `contributes_to` should show up in GPAD after the next Minerva restart.

**Comment by vanaukenk** [comment]
@dosumis @balhoff 

Does this model still exist?

http://noctua.berkeleybop.org/editor/graph/gomodel:5970219a00000402

I'm not able to view it in Noctua and I don't see it in the list of gpad outputs on Jenkins.

Just wanted to look it over to see how the patterns and inferences are working.  Thx.

**Comment by balhoff** [comment]
Probable explanation for missing model: https://github.com/geneontology/noctua/issues/469

**Comment by kltm** [comment]
@balhoff Minerva rebuilt and restarted.

**Comment by balhoff** [comment]
@dosumis looks like `contributes_to` annotations are coming out now.
