### ISSUE TITLE
Correctly output NOT qualifier in GPAD (and GAF?)

### ISSUE THREAD

**Issue by kltm** [geneontology/minerva#149]
This is the minerva companion item for https://github.com/geneontology/noctua/issues/218 . More discussion can be found on that thread.

I believe that this work would mostly be oriented around the sparql for the output and the embedded blazegraph; /minerva-converter/src/main/java/org/geneontology/minerva/legacy/sparql/GPADSPARQLExport.java 

@balhoff @yy20716 @cmungall

**Comment by cmungall** [comment]
@yy20716 @kltm can we call this done?

**Comment by balhoff** [comment]
There is an open pull request I've been meaning to look at—will do now.
