### ISSUE TITLE
Minerva doesn't seem to produce proper CAM models from GAF files

### ISSUE THREAD

**Issue by dougli1sqrd** [geneontology/minerva#152]
The RDF models that the minerva-cli produces when producing GO CAM (lego) RDF models from GAF don't seem to include evidence models. 

The command is invoked similar to: 
`minerva-cli.sh ontology_file.ttl --gaf gaf_file.gaf --gaf-lego-individuals --skip-merge --format turtle -o output.ttl`

Triples of GAF files seem to be firstly class declarations, and then the annotations proceed as RDF in the following manner:

    :i rdf:type owl:NamedIndividual, ?SomeClass;
       :r :j .

Where `:i :r :j` is the annotation from a GAF line in a triple format. One would expect if this is a GO CAM (lego) model there would be the entire evidence RDF for each triple (like in Noctua). For example, we should also have:

    :_b owl:annotatedSource :i ;
          owl:annotatedProperty :r ;
          owl:annotatedTarget :j .
    :_b <http://geneontology.org/lego/evidence> :e .

Where `:e a [ rdfs:subClassOf* ECO:0000000 ]` where ECO is the evidence ontology.

On rdf.geneontology.org, one can perform a sparql query for all individuals that are instances of ECO:
```
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX metago: <http://geneontology.org/>
SELECT ?e ?cam
WHERE {
  ?etype rdfs:subClassOf* <http://purl.obolibrary.org/obo/ECO_0000000> .
  GRAPH ?cam {
    ?g metago:graphType metago:gafCam .
    ?e a ?etype .
  }
}
```
And there are no results. The first line of the GRAPH block restricts the graphs to only those that come from processing GAF files. There will be no results. 

It seems that Minerva should be taking into account the full GO-CAM model, to be just like Noctua models (except degenerate).

**Comment by kltm** [comment]
@cmungall So we'll be switching from the minerva-cli.sh command in the Makefile now to an ontobio command for these.

**Comment by balhoff** [comment]
It would be interesting to test using the DOS-DP instance graph templates for this. But I haven't implemented that part of the spec yet.

**Comment by dougli1sqrd** [comment]
@cmungall Okay I'll try playing with the ontobio version of this then.
