### ISSUE TITLE
GPAD: Filter out all annotations to root MF unless evidence is ND

### ISSUE THREAD

**Issue by cmungall** [geneontology/minerva#154]
At go doc meeting, we agree on a rule. We're not sure if this is already implemented.

Any annotation to the root MF node MUST be filtered out UNLESS evidence='ND'

cc @ukemi @vanaukenk @thomaspd

**Comment by cmungall** [comment]
I think we might already have this

https://github.com/geneontology/minerva/blob/110bb0cdb482fc5b5242e8db0f519041c9f91f38/minerva-converter/src/main/java/org/geneontology/minerva/legacy/sparql/GPADSPARQLExport.java#L150-L151

**Comment by balhoff** [comment]
https://github.com/geneontology/minerva/pull/130/files

**Comment by pgaudet** [comment]
Hi @cmungall 
I am not sure what's the context of this ticket (you are documenting which page?) but I thought this was a hard rule, not just a filter. Contributing groups should be asked to fix these. 

Thanks, Pascale

**Comment by balhoff** [comment]
This should already be happening.
