### ISSUE TITLE
Return label if present directly on individual 

### ISSUE THREAD

**Issue by balhoff** [geneontology/minerva#155]

**Comment by kltm** [comment]
I'm not sure how this would work in practice. An individual return object currently looks like:

```json
        "individuals": [
            {
                "id": "gomodel:5798651000000002/5798651000000009",
                "type": [
                    {
                        "type": "class",
                        "id": "UBERON:0001833",
                        "label": "lip"
                    }
                ],
                "annotations": [
                    {
                        "key": "hint-layout-y",
                        "value": "318"
                    }

```

Would this be the addition of a new field at the top-level, with `id` and `type`? As it stands now, I can mine `rdfs:label` from the annotations. It might be good to make that special and elevate it.

**Comment by vanaukenk** [comment]
@balhoff @kltm 

Is this still an issue?  

If so, can we assign it to someone and give it a meaningful label?  Thx.

**Comment by balhoff** [comment]
This was going to be for @goodb's Reactome models, but I think it ended up that this already worked. Can we close this @goodb?

**Comment by goodb** [comment]
Yes, close away.  This works as it should now.
