### ISSUE TITLE
Provide a stable URL and filtered production GPAD files

### ISSUE THREAD

**Issue by ukemi** [geneontology/minerva#160]
We need a stable URL to point to when we pick up GPAD files for our automated load. We also need to have the GPAD files filtered so they only contain annotations from models that are categorized as production. Once these are in place, we can test load our Noctua-generated annotations into MGI.

**Comment by ukemi** [comment]
May be a duplicate with https://github.com/geneontology/go-site/issues/431

**Comment by balhoff** [comment]
I think this is duplicating the go-site ticket so I'll close.
