### ISSUE TITLE
GPAD export should not create annotations from inconsistent model

### ISSUE THREAD

**Issue by balhoff** [geneontology/minerva#168]
See https://github.com/geneontology/noctua/issues/546

**Comment by balhoff** [comment]
@kltm what would be the best way to return an error for a GPAD request? I can throw an exception and I think an HTTP error response will be generated, but can we signal to Noctua that the cause is "inconsistent ontology" so that it can be presented to the user?

**Comment by kltm** [comment]
Okay, it has been a while, but I believe that some types of thrown errors in Minerva will automatically get wrapped up and sent back across the wire. What we've done so far is leave it to the clients to interpret these. 
For the clients, we'd either want a generalized error detection lib (e.g. a lib version of things like https://github.com/geneontology/noctua/blob/master/js/NoctuaEditor.js#L1482) or have Minerva try and catch and structure these for client display.
I think the main reason we started down the path of the former is that Minerva was leaky enough and enough odd things went wrong it was easier to expose issues to the clients and do debugging from there. With things being tighter now, we may want to revisit the use of response messages in signalling the clients.

**Comment by kltm** [comment]
Whoops, I answered the wrong question.
Simply, you'd want to fill in `message-type`, `message`, and other slots as appropriate:
https://github.com/berkeleybop/bbop-response-barista/blob/master/tests/core.test.js

**Comment by balhoff** [comment]
Okay, thanks, I've done this now. The error message is displayed properly over the Annotation Preview workbench. If Export GPAD is used, a page with the text `apparently could not resolve model` is shown.

**Comment by kltm** [comment]
Huh, that worked? I half expected those clients to be so minimal that they would drop error messages. Great!

**Comment by balhoff** [comment]
Note to @cmungall @dougli1sqrd: the Noctua-to-GPAD Jenkins job will now skip inconsistent models and log an error with the model IRI.
