### ISSUE TITLE
SGD label resolution

### ISSUE THREAD

**Issue by cmungall** [geneontology/minerva#17]
Labels are rendered in 536d71c500000004 (Yeast Phosphate Starvation)

Examples 
```
Individual: <http://purl.obolibrary.org/obo/#536d71c500000004%2F5595c4cb00000232>

    Annotations: 
        <http://purl.org/dc/elements/1.1/date> "2015-01-05"^^xsd:string,
        <http://purl.org/dc/elements/1.1/contributor> "GOC:pt"^^xsd:string
    
    Types: 
        <http://identifiers.org/sgd/S000005952>
 ```

Labels are *not* rendered in 5525a0fc00000061 (annotation consistency RB)

Example of OWL:
```
Individual: <http://purl.obolibrary.org/obo/#5525a0fc00000061%2F5595c4cb00000521>

    Annotations:
        <http://purl.org/dc/elements/1.1/date> "2015-05-01"^^xsd:string,
        <http://purl.org/dc/elements/1.1/contributor> "http://orcid.org/0000-0003-2468-9933"^^xsd:string

    Types:
        <http://identifiers.org/sgd/S000004529>
```

**Comment by cmungall** [comment]
Note that S000004529 has been in the GAF a long time, so the hypothesis that this is a newly added gene doesn't hold

> SGD     S000004529      TEM1            GO:0007096      SGD_REF:S000086185|PMID:16039591        TAS             P       GTP-binding protein of the Ras superfamily      YML064C|Ras family GTPase TEM1  gene      taxon:559292    20060314        SGD

**Comment by hdietze** [comment]
Added a quick test for: `<http://identifiers.org/sgd/S000005952>`
Seems to work on the Golr query level perfectly well.

**Comment by hdietze** [comment]
We already had a similar test case for: `<http://identifiers.org/sgd/S000004529>`
Seems to also work on the Golr level.

**Comment by cmungall** [comment]
Was a cache issue, @hdietze committed an improved cacheing mechanism
