### ISSUE TITLE
Update GPAD relations list

### ISSUE THREAD

**Issue by balhoff** [geneontology/minerva#170]
Need to include all relations listed here: http://wiki.geneontology.org/index.php/Annotation_Relations

**Comment by ukemi** [comment]
Thanks @balhoff, always best to open a ticket. Just to make sure this is completely spelled out, these relations will populate column 3 in the GPAD file, which is also know as the qualifier. In addition to these, we should also have enables for MF annotations, and part_of and colocalizes_with for CC annotations. We should also allow NOT as a qualifier. @vanaukenk and @cmungall , does this look complete?

**Comment by ukemi** [comment]
Looking at the wiki, we will also allow contributes_to for MF annotations.
