### ISSUE TITLE
GPAD annotations to PR:0000001

### ISSUE THREAD

**Issue by ukemi** [geneontology/minerva#174]
We have begun to test loading the new GPAD files into the MGI resource. Our QC checks have detected annotations to PR:0000001.  The annotations are listed below. They appear to be coming from isoform annotations. This is a simple model to look at (the good news is the correct annotations are also generated):
gomodel:5745387b00001874

object is not in GPI file: PR:000000001
PR	000000001	part_of	GO:0005829	PMID:9819391	ECO:0000007			20160823	GO_Noctua		noctua-model-id=gomodel:5745387b00001874|model-state=production|contributor=GOC:krc
****
object is not in GPI file: PR:000000001
PR	000000001	part_of	GO:0005886	PMID:9819391	ECO:0000314			20160823	GO_Noctua		noctua-model-id=gomodel:5745387b00001874|model-state=production|contributor=GOC:krc
****
object is not in GPI file: PR:000000001
PR	000000001	enables	GO:0098772	PMID:12771146	ECO:0000314			20161216	MGI	preceded_by(GO:0005515),has_input(CHEBI:18348)	contributor=http://orcid.org/0000-0001-7476-6306|model-state=production|noctua-model-id=gomodel:581e072c00000473
****
object is not in GPI file: PR:000000001
PR	000000001	enables	GO:0005515	PMID:12771146	ECO:0000314			20161216	MGI	preceded_by(GO:0005515),has_input(CHEBI:18348)	contributor=http://orcid.org/0000-0001-7476-6306|model-state=production|noctua-model-id=gomodel:581e072c00000473
****
object is not in GPI file: PR:000000001
PR	000000001	enables	GO:0005546	PMID:12771146	ECO:0000314			20161216	MGI	preceded_by(GO:0005515),has_input(CHEBI:18348)	contributor=http://orcid.org/0000-0001-7476-6306|model-state=production|noctua-model-id=gomodel:581e072c00000473
****
object is not in GPI file: PR:000000001
PR	000000001	enables	GO:0005096	PMID:12771146	ECO:0005801			20161118	MGI	preceded_by(GO:0005515),has_input(PR:000004201)	contributor=http://orcid.org/0000-0001-5501-853X|model-state=production|noctua-model-id=gomodel:581e072c00000473
****
object is not in GPI file: PR:000000001
PR	000000001	enables	GO:0032266	PMID:12771146	ECO:0000314			20161216	MGI	has_input(CHEBI:26034)	contributor=http://orcid.org/0000-0001-7476-6306|model-state=production|noctua-model-id=gomodel:581e072c00000473
****
object is not in GPI file: PR:000000001
PR	000000001	part_of	GO:0120038	PMID:26627310	ECO:0000304			20170127	GO_Noctua	part_of(CL:0002613),part_of(GO:0043005),capable_of_part_of(GO:0021756),capable_of_part_of(GO:0035249),capable_of_part_of(GO:0098989),capable_of_part_of(GO:1905114),enables(GO:0004972),enables(GO:0098960),involved_in(GO:0021756),involved_in(GO:0035249),involved_in(GO:0098989),involved_in(GO:1905114)	noctua-model-id=gomodel:586fc17a00000381|contributor=http://orcid.org/0000-0001-7476-6306|model-state=production
****
object is not in GPI file: PR:000000001
PR	000000001	part_of	GO:0120038	PMID:26627310	ECO:0000304			20170127	GO_Noctua	part_of(CL:0002613),part_of(GO:0043005),capable_of_part_of(GO:0021756),capable_of_part_of(GO:0035249),capable_of_part_of(GO:0098989),capable_of_part_of(GO:1905114),enables(GO:0004972),enables(GO:0098960),involved_in(GO:0021756),involved_in(GO:0035249),involved_in(GO:0098989),involved_in(GO:1905114)	noctua-model-id=gomodel:586fc17a00000381|contributor=http://orcid.org/0000-0001-7476-6306|model-state=production
****
object is not in GPI file: PR:000000001
PR	000000001	part_of	GO:0017146	PMID:26627310	ECO:0000304			20170127	GO_Noctua	part_of(CL:0002613),part_of(GO:0043005),capable_of_part_of(GO:0021756),capable_of_part_of(GO:0035249),capable_of_part_of(GO:0098989),capable_of_part_of(GO:1905114),enables(GO:0004972),enables(GO:0098960),involved_in(GO:0021756),involved_in(GO:0035249),involved_in(GO:0098989),involved_in(GO:1905114)	noctua-model-id=gomodel:586fc17a00000381|contributor=http://orcid.org/0000-0001-7476-6306|model-state=production
****
object is not in GPI file: PR:000000001
PR	000000001	part_of	GO:0017146	PMID:26627310	ECO:0000304			20170127	GO_Noctua	part_of(CL:0002613),part_of(GO:0043005),capable_of_part_of(GO:0021756),capable_of_part_of(GO:0035249),capable_of_part_of(GO:0098989),capable_of_part_of(GO:1905114),enables(GO:0004972),enables(GO:0098960),involved_in(GO:0021756),involved_in(GO:0035249),involved_in(GO:0098989),involved_in(GO:1905114)	noctua-model-id=gomodel:586fc17a00000381|contributor=http://orcid.org/0000-0001-7476-6306|model-state=production
****
object is not in GPI file: PR:000000001
PR	000000001	part_of	GO:0043005	PMID:26627310	ECO:0000314			20170127	GO_Noctua	overlaps(CL:0002613)	noctua-model-id=gomodel:586fc17a00000381|contributor=http://orcid.org/0000-0001-7476-6306|model-state=production
****
object is not in GPI file: PR:000000001
PR	000000001	part_of	GO:0120038	PMID:26627310	ECO:0000304			20170127	GO_Noctua	part_of(CL:0002613),part_of(GO:0043005),capable_of_part_of(GO:0021756),capable_of_part_of(GO:0035249),capable_of_part_of(GO:0098989),capable_of_part_of(GO:1905114),enables(GO:0004972),enables(GO:0098960),involved_in(GO:0021756),involved_in(GO:0035249),involved_in(GO:0098989),involved_in(GO:1905114)	noctua-model-id=gomodel:586fc17a00000381|contributor=http://orcid.org/0000-0001-7476-6306|model-state=production
****
object is not in GPI file: PR:000000001
PR	000000001	part_of	GO:0017146	PMID:26627310	ECO:0000304			20170127	GO_Noctua	part_of(CL:0002613),part_of(GO:0043005),capable_of_part_of(GO:0021756),capable_of_part_of(GO:0035249),capable_of_part_of(GO:0098989),capable_of_part_of(GO:1905114),enables(GO:0004972),enables(GO:0098960),involved_in(GO:0021756),involved_in(GO:0035249),involved_in(GO:0098989),involved_in(GO:1905114)	noctua-model-id=gomodel:586fc17a00000381|contributor=http://orcid.org/0000-0001-7476-6306|model-state=production
****
object is not in GPI file: PR:000000001
PR	000000001	part_of	GO:0017146	PMID:26627310	ECO:0000304			20170127	GO_Noctua	part_of(CL:0002613),part_of(GO:0043005),capable_of_part_of(GO:0021756),capable_of_part_of(GO:0035249),capable_of_part_of(GO:0098989),capable_of_part_of(GO:1905114),enables(GO:0004972),enables(GO:0098960),involved_in(GO:0021756),involved_in(GO:0035249),involved_in(GO:0098989),involved_in(GO:1905114)	noctua-model-id=gomodel:586fc17a00000381|contributor=http://orcid.org/0000-0001-7476-6306|model-state=production
****
object is not in GPI file: PR:000000001
PR	000000001	part_of	GO:0043005	PMID:26627310	ECO:0000314			20170127	GO_Noctua	overlaps(CL:0002613)	noctua-model-id=gomodel:586fc17a00000381|contributor=http://orcid.org/0000-0001-7476-6306|model-state=production
****
object is not in GPI file: PR:000000001
PR	000000001	part_of	GO:0043005	PMID:26627310	ECO:0000314			20170127	GO_Noctua	overlaps(CL:0002613)	noctua-model-id=gomodel:586fc17a00000381|contributor=http://orcid.org/0000-0001-7476-6306|model-state=production
****
object is not in GPI file: PR:000000001
PR	000000001	part_of	GO:0043005	PMID:26627310	ECO:0000314			20170127	GO_Noctua	overlaps(CL:0002613)	noctua-model-id=gomodel:586fc17a00000381|contributor=http://orcid.org/0000-0001-7476-6306|model-state=production
****
object is not in GPI file: PR:000000001
PR	000000001	part_of	GO:0120038	PMID:26627310	ECO:0000304			20170127	GO_Noctua	part_of(CL:0002613),part_of(GO:0043005),capable_of_part_of(GO:0021756),capable_of_part_of(GO:0035249),capable_of_part_of(GO:0098989),capable_of_part_of(GO:1905114),enables(GO:0004972),enables(GO:0098960),involved_in(GO:0021756),involved_in(GO:0035249),involved_in(GO:0098989),involved_in(GO:1905114)	noctua-model-id=gomodel:586fc17a00000381|contributor=http://orcid.org/0000-0001-7476-6306|model-state=production
****
object is not in GPI file: PR:000000001
PR	000000001	part_of	GO:0042622	PMID:27613864	ECO:0000304			20170130	GO_Noctua	part_of(CL:0000287),part_of(EMAPA:17168),part_of(UBERON:0000966),overlaps(GO:0005794),overlaps(GO:0097458)	contributor=http://orcid.org/0000-0001-7476-6306|model-state=production|noctua-model-id=gomodel:586fc17a00000482
****
object is not in GPI file: PR:000000001
PR	000000001	involved_in	GO:0050908	PMID:27613864	ECO:0000304			20170130	GO_Noctua	occurs_in(CL:0000287),occurs_in(EMAPA:17168),occurs_in(UBERON:0000966)	contributor=http://orcid.org/0000-0001-7476-6306|model-state=production|noctua-model-id=gomodel:586fc17a00000482
****

**Comment by cmungall** [comment]
Where are you getting these from?

you should be getting them from this job

https://build.berkeleybop.org/job/export-lego-to-gpad-sparql/lastSuccessfulBuild/artifact/legacy/

e.g.
https://build.berkeleybop.org/job/export-lego-to-gpad-sparql/lastSuccessfulBuild/artifact/legacy/mgi.gpad/*view*/

there are no annotations directly to a PRO ID. However, there are inferred usages of PR:1 in the inferred extensions. These are correct but uninformative. We can filter these.

Note in the preview
http://noctua.berkeleybop.org/workbench/annpreview/?model_id=gomodel:5745387b00001874&barista_token=

you will see annotations to PR:1. Why? Well, it's correct but redundant. Why isn't the redundancy being detected? Because in neo we use the CHEBI class for protein, not the PRO class:

```
id: PR:Q9QWY8-1
name: mASAP1/isom1 Mmus
synonym: "mASAP1/isom1" BROAD []
synonym: "Q9QWY8-1" RELATED []
xref: UniProtKB:Q9QWY8-1
is_a: CHEBI:36080 ! protein
relationship: in_taxon NCBITaxon:10090
relationship: has_gene_template MGI:MGI:1342335
```
