### ISSUE TITLE
Do we need the model-state:production property in the GPAD file?

### ISSUE THREAD

**Issue by ukemi** [geneontology/minerva#175]
It was a nice initial sanity check, but now all of the annotations are generated from production models. It seems that this is redundant. If not, I will add the property to MGI.

**Comment by cmungall** [comment]
I would like to keep it. It's easy for files to become dissociated from their original context

**Comment by balhoff** [comment]
This is what is actually being used to filter for the production models. You can still go to the jenkins job and view the output for a model with any status.
