### ISSUE TITLE
Make OWL model retrieved from Noctua more usable (handle the neo import problem)

### ISSUE THREAD

**Issue by goodb** [geneontology/minerva#178]
This has come up in enough places it needs its own issue to refer to.  The problem is that go-cam OWL models include owl:imports <http://purl.obolibrary.org/obo/go/extensions/go-lego.owl> which includes https://github.com/geneontology/neo which is very large.  This makes it impossible to open the model in Protege and a hassle to deal with in code.  Since 99.9% of neo is irrelevant to any given go-cam model, lets find a way to reduce the import to something more manageable for downstream consumers.  (This may also impact developers working on the noctua/minerva stack but this issue is specifically in reference to consumers of the go-cams).  

Ideas from @cmungall on https://github.com/geneontology/go-site/issues/558#issuecomment-377647594 : 
> We can provide a pre-generated combined OWL file with an import module merged in, that would allow for cross-model exploration.
> 
> For people who want to look at individual models in Protege, we can provide a docker container that makes a module and writes a catalog file. But really Protege needs better dynamic module creation abilities.

**Comment by goodb** [comment]
@vanaukenk This would generally be me and @balhoff and maybe Seth and Chris (though that could be said for every ticket).  I think this a low-priority issue for now as its only important for developers (and not a total blocker) and the focus right now is on getting things in place for users.

**Comment by vanaukenk** [comment]
@goodb - is this issue now addressed with the more recent work on neo?  

Thx.

**Comment by goodb** [comment]
@vanaukenk not quite.  Its related to what i was discussing with @balhoff at the end of the software call.  Hopefully close to closing.
