### ISSUE TITLE
enables_o_occurs_in -> is_active_in ?

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/minerva#179]
We have discussed this in the past, but I would like to confirm whether we want this relation chain for populating the derived GPAD output from GO-CAM models:

enables_o_occurs_in -> is_active_in

Right now, all GP-CC annotations resolve to using the part_of relation.

https://www.ebi.ac.uk/ols/ontologies/ro/properties?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0002432

@balhoff @cmungall @thomaspd @ukemi

**Comment by balhoff** [comment]
The current chain is in a SWRL rule: `enables(?x, ?y) ⋀ 'occurs in'(?y, ?z) → 'part of'(?x, ?z)`.

It has to be a rule rather than a property chain because of some circularity issues. So I would replace this rule with a similar one producing `is active in`. However there is a comment in RO on the existing rule:

> This rule is dubious: added as a quick fix for expected inference in GO-CAM.  The problem is most acute for transmembrane proteins, such as receptors or cell adhesion molecules, which have some subfunctions inside the cell (e.g. kinase activity) and some subfunctions outside (e.g. ligand binding).  Correct annotation of where these functions occurs leads to incorrect inference about the location of the whole protein.  This should probably be weakened to "... -> overlaps"

I think @dosumis wrote that—maybe he can weigh in. Personally I find using `part of` to relate gene products to their locations to be odd (I know it is traditional in GO). I would choose `located in` or something else (and move `is active in` as a subproperty). But that still wouldn't address @dosumis's concern, since `located in` says "the target is entirely within the location".

**Comment by cmungall** [comment]
How about:

 * `enables(?x, ?y) ⋀ 'occurs in'(?y, ?z) → 'is active in'(?x, ?z)`
 * new relation: `located at` def: *either located in or attached to*
 * `'is active in' subPropertyOf 'located at'`
 * `'located in' subPropertyOf 'located at'`
* `'located at' subPropertyOf 'overlaps'`

**Comment by dosumis** [comment]
Why is located_at needed?

**Comment by balhoff** [comment]
@cmungall `located in` is currently not a subproperty of `overlaps`. Should it be? Is it possible to get all of GO to switch to `located in` instead of `part of`? :-)

**Comment by cmungall** [comment]
> located in is currently not a subproperty of overlaps. Should it be?

I don't think so - consider bolus of food located_in the esophagus, no parts in common

>  Is it possible to get all of GO to switch to located in instead of part of

my proposal was actually located_at, and the curators would have a choice of whether to make a functionally string statement (is-active-in) vs a weaker one (located-at: no implication of function, and weaker than located in)

**Comment by cmungall** [comment]
> Why is located_at needed

it's the weakest case. For when a curator is not confident to make any assertion about function, but subsuming the is-active-in case

**Comment by vanaukenk** [comment]
@cmungall 

Can we make a final decision on whether or not we want to include this for the 1.0 release or wait until 2.0?  If I'm understanding correctly, this is the proposal for RO:

overlaps (RO:0002131)
-located at (RO:new)
--located in (RO:0001025)
--is active in (RO:0002432)

And we are suggesting that curators annotate to 'located at' or 'is active in'.

Besides the GPAD output, we would need to update the relations lists in the graph editor and the relation used on the CC only form.

Thx.

**Comment by vanaukenk** [comment]
Talking with @ukemi about this, we want to make sure that the ontology and gp2term relations align properly.  This would suggest we need some more lead time to think this through, so how about keeping the SWRL for now and investigating further wrt adding a new term to RO and what relation(s) we ultimately want in both places (ontology and annotations).

**Comment by balhoff** [comment]
@vanaukenk do you mean go ahead and edit the rule to be: `enables(?x, ?y) ⋀ 'occurs in'(?y, ?z) → 'is active in'(?x, ?z)`, and defer any changes to the relations of `is active in`?

**Comment by balhoff** [comment]
This relation chain (`enables_o_occurs_in -> is_active_in`) is part of RO. Give current GO practice, I'm wondering if we should then remove the SWRL rule from RO:

`enables(?x, ?y), 'occurs in'(?y, ?z) -> 'part of'(?x, ?z)`

There are a few other axioms suggested above. We should review decide which to add and then finally close this issue. @vanaukenk @ukemi

**Comment by vanaukenk** [comment]
Closing this for now, as the 'is active in' inference is generated in the GPAD output.

Note, however, that we still need to either delete the SWRL rule from RO that is also generating the 'part of' inference or filter the redundant 'part of' CC annotations from the GPAD output.

See #390
