### ISSUE TITLE
Fix lego2gaf/gpad pipeline

### ISSUE THREAD

**Issue by cmungall** [geneontology/minerva#18]
cc @rbalakri 

Last ran in 2014:
http://build.berkeleybop.org/job/export-lego-to-legacy/

Will need updating, specifically to ensure
- taxon present
- evidence

**Comment by kltm** [comment]
Adding lego, gaf, and gpad as separate text as it does not seem to be picked-up by search otherwise.

**Comment by hdietze** [comment]
The jenkins job is now running again and is triggered by changes to the noctua-models git repository:
http://build.berkeleybop.org/job/export-lego-to-legacy/

**Comment by cmungall** [comment]
We should also add GAF, and load into the experimental golr/amigo (note we already load the lego models without downgrading into what is currently called 'complex_annotations'; this would be a separate path).

**Comment by balhoff** [comment]
This is obsolete now.
