### ISSUE TITLE
Document expectations about TBox axioms in ABox

### ISSUE THREAD

**Issue by cmungall** [geneontology/minerva#185]
I had assumed that a model only contained ABox axioms.

However, it seems that many contain TBox axioms - sometimes label declarations, sometimes just class declarations

https://github.com/geneontology/noctua-models/blob/master/models/586fc17a00000381.ttl
 - label axioms for CL, GO
 - declaration axioms for everything

https://github.com/geneontology/noctua-models/blob/master/models/59dc728000000555.ttl
 - label axioms for ZFA genes
 - declarations for ZFA and UBERON, not GO

Based on the current state I believe the formal documentation should say

 * clients MUST obtain TBox axioms from TBox graph, not model graph
 * minerva SHOULD NOT place TBox axioms in ABox graph, but in some cases these may leak through, due to owlapi weirdness

**Comment by balhoff** [comment]
I think the gene product classes get declared in the model because the terms are not in the Tbox (e.g. because of https://github.com/geneontology/neo/issues/17). However I'm not clear on the pathway by which the label annotations creep in (need to think about it further).

**Comment by cmungall** [comment]
Minerva is able to query solr to obtain labels and to inject these, I assume they got in this way.

**Comment by goodb** [comment]
I noticed this property hanging on this ZFIN class declared within 59dc728000000555 
<http://geneontology.org/lego/derived> "true"^^<http://www.w3.org/2001/XMLSchema#string> ;

What does this property mean?  Maybe this is a clue about where the class defs are leaking in - e.g. if Minerva is inferring them and needs to add them into the model to create required axioms.

**Comment by goodb** [comment]
Maybe a tangent from debugging how these came in through the editor/minerva path, but when generating GO-CAM models from other sources, I have hit cases where the required classes either do not exist in neo or just don't exist anywhere at all (e.g. complexes).  So far I've gotten around this either by creating them and adding them into the go-cam model owl file or just defaulting to an uninformative upper level class (e.g. macromolecular complex).  The Noctua (v1) editor appears to accept such additional classes if they are present in the models that it loads.  

This points to the use case of editors/importers needing a mechanism to propose new classes to be added to the global tbox (perhaps a v2 feature).  Also a question - are OWL models that follow the GO-CAM modeling practices but contain additional classes or refer to classes outside of the GOC TBox considered 'valid'?  Should they be allowed into GOC GO-CAM collections?  Should software that consumes go-cams try to work with them (the way Noctua is doing now) ?

**Comment by cmungall** [comment]
> This points to the use case of editors/importers needing a mechanism to propose new classes to be added to the global tbox (perhaps a v2 feature)
+1

I think we should impose some SHOULDs. I see the use case for inject TBox axioms info but there are problems here with axioms getting out of sync.
