### ISSUE TITLE
possible inconsistent reasoning

### ISSUE THREAD

**Issue by ukemi** [geneontology/minerva#186]
In model http://noctua.berkeleybop.org/editor/graph/gomodel:57c82fad00000868 there is a reasoned annotation to negative regulation of bone remodeling resulting from the (negative regulation of ossification) negatively_regulates (ossification) part_of (bone remodeling). However, we don't get the corresponding reasoned annotation to positive regulation of bone remodeling from the positive regulation chain over bone resorption. Any idea why? 

Note this is a good example of why the regulates_o_part_of chains are counter intuitive in GO-CAM models. Ideally we only want the asserted regulation of bone resorption.

**Comment by balhoff** [comment]
@ukemi it is entailed but you don't see it because 'positive regulation of bone resorption' is a subclass of 'positive regulation of bone remodeling'.

**Comment by balhoff** [comment]
We may want an option on the inference explanation workbench to show EVERYTHING.

**Comment by ukemi** [comment]
Ah! Got it.

**Comment by ukemi** [comment]
I just removed the asserted superclasses. The reasoner still infers the same hierarchy, but this also points to the flaw in the regulates-o-part_of chain. Intuitively positively/negatively regulating either resorption or ossification involved in remodeling should not positively/negatively regulate remodeling. I think it should just regulate it. This is related to the discussion we had last week on the GO-CAM call. I think there are cases where all we can say is regulates.
