### ISSUE TITLE
repeated annotation extensions

### ISSUE THREAD

**Issue by ukemi** [geneontology/minerva#187]
Annotation extensions should only be listed once in a GPAD file. For example, this is the first annotation in the MGI file:

!collated from production models in https://github.com/geneontology/noctua-models/ where col1 matches mgi
MGI	MGI:2685011	involved_in	GO:0098609	PMID:26258302	ECO:0000315	MGI:MGI:4867020		20160729	MGI	part_of(GO:0003183),part_of(GO:0007389),part_of(GO:0009653),part_of(GO:0016477),occurs_in(UBERON:0007151),occurs_in(UBERON:0007151),occurs_in(UBERON:0007151)	contributor=http://orcid.org/0000-0001-7476-6306|model-state=production|noctua-model-id=gomodel:56aac7ad00000038

This is due to the assertion of several processes that are part of one another occuring in the same structure. I think the model is correct, but the annotations extensions in the GPAD are redundant.  We should only be listing the occurs_in once.

**Comment by balhoff** [comment]
I see, these are separate instances but this is lost at the annotation extension level. Makes sense to collapse them. But why not have one instance of `mitral valve leaflet` in the model?

**Comment by ukemi** [comment]
@balhoff , you are correct. The model could be refined by asserting the location only on the most general complex. The occurrence in all the parts were inferred correctly.
