### ISSUE TITLE
Automate catalog.xml construction

### ISSUE THREAD

**Issue by goodb** [geneontology/minerva#188]
Would be really handy when setting this up if there were a routine that would collect the required ontologies, write the catalog.xml file for loading them locally, and add that automatically to the run script.

**Comment by cmungall** [comment]
You can use http://robot.obolibrary.org/mirror (can be called via command line, or JVM call)

**Comment by goodb** [comment]
Great.  Just need to add it to the build file, or at least to the build instructions.

**Comment by vanaukenk** [comment]
@goodb 
Is this issue addressed?  Is there anyone else who should be assigned?
