### ISSUE TITLE
Verify that we are not prone to memory leaks when iterating though multiple models

### ISSUE THREAD

**Issue by cmungall** [geneontology/minerva#190]
@yy20716 identified a memory issue with the OWLAPI, ontologies not being released when cycling through aboxes in the solr loader. He will post details here. We should make sure we are not vulnerable in minerva

**Comment by balhoff** [comment]
One thing to consider is that Minerva doesn't make any attempt to let go of previously loaded models. So it is expected the memory will grow at least to that extent.
