### ISSUE TITLE
Minerva returns labels with namespaces prefixed in some cases (e.g. GO:molecular_function)

### ISSUE THREAD

**Issue by kltm** [geneontology/minerva#195]
After the last minerva change (https://github.com/geneontology/minerva/pull/194), it seems that Minerva returns labels with namespaces prefixed in some cases (e.g. GO:molecular_function). For example, see http://noctua.berkeleybop.org/editor/graph/gomodel:5ae3b0f600001743

The expectation is that labels should never be prefixed.

This does not seems to affect ids and labels on writeback. That said, it may confuse users and cause confusion if somebody tries to mimic it for input.

**Comment by kltm** [comment]
tagging @cmungall and @balhoff

**Comment by cmungall** [comment]
The most obvious explanation is that the json-ld context mapping somehow injects this, but I don't see any evidence of this in the code. But the URI<->ID mapping is the most obvious place to check.

(I believe we still go through owltools for URI<->ID but this can now be entirely mediated through the json-ld context mechanism)

**Comment by cmungall** [comment]
FWIW, doesn't seem to show up on inference explanations:

http://noctua.berkeleybop.org/workbench/inferredrelations/?model_id=gomodel:5525a0fc00000075&barista_token=

**Comment by cmungall** [comment]
Also reported here: https://github.com/evidenceontology/evidenceontology/issues/168

**Comment by vanaukenk** [comment]
@kltm @balhoff 
Is this issue fixed?
I looked at the referenced GO-CAM model but can't tell.  There are other issues with that model, but I think it is just a test model so if we needed to fix those issues to check on the eco issue, I could do that.

**Comment by balhoff** [comment]
This should be fixed now. We are not getting ECO's OBI import module anymore at all.
