### ISSUE TITLE
Incorrect inferences generated when MF enabled_by a protein is part_of a metabolic process

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/minerva#197]
@pgaudet was making some new transcription models using UniProtKB accessions for proteins as the enabled_by entity.

When the MF enabled_by a protein is connected to 'transcription by RNA polymerase II' with a part_of relation, the reasoner is inferring that the MF is also part_of a 'protein metabolic process' and a 'peptide metabolic process'.

In brief, for 'protein metabolic process', the inferred annotation appears to come from reasoning that the MF enabled_by entity is a protein, that transcription is a metabolic process, that the protein is thus a participant in a metabolic process, and by the logical definition of 'protein metabolic process', the MF is also part_of a 'protein metabolic process':  'metabolic process' and ('has participant' some protein)

A comparative example model is here:

http://noctua.berkeleybop.org/editor/graph/gomodel:5b528b1100000113

Run the reasoner and specifically compare the last two entries.

And another made-up example, using a part_of relation to 'RNA metabolic process', to illustrate is here:

http://noctua.berkeleybop.org/editor/graph/gomodel:5b528b1100000111

The logical def for 'protein metabolic process' seems too broad to be used effectively for reasoning here, but we need to decide overall what the best course of action is.

@balhoff 
@cmungall 
@ukemi

**Comment by vanaukenk** [comment]
Note that most groups who've been making models so far use gene ids for their entities, which is likely why we didn't pick up on this earlier.

**Comment by vanaukenk** [comment]
@ukemi and I just also tested a mouse protein using PR:000036529 as the enabled_by id and can reproduce the behavior, i.e. use of a protein identifier results in inferred annotations to BP terms that contain 'has participant' protein in their logical definition.

**Comment by vanaukenk** [comment]
Here is a screenshot of one example of the reasoning that leads to these annotations:

![image](https://user-images.githubusercontent.com/1730534/43221570-360b0182-901b-11e8-9898-e6999918c7bc.png)

**Comment by ukemi** [comment]
Perhaps we need to distinguish active participants from passive participants. Inputs and outputs would be passive.

**Comment by cmungall** [comment]
We've talked about this issue for a while but inferentially we've been able to sweep it under the carpet since it doesn't come up in reasoning on just the ontology.

We need a more specific relation as @ukemi suggests. But I think it has to be more specific than passive participants, as we want to exclude byproducts.

**Comment by pgaudet** [comment]
Hi, 

Just to make sure I understand: For example this simple model: 
http://noctua.berkeleybop.org/editor/graph/gomodel:5b528b1100000112?barista_token=bqfhvinxtnbyfhin2g3n#
<img width="544" alt="image" src="https://user-images.githubusercontent.com/4782928/43246960-90c234d6-90b3-11e8-8080-da1b33715425.png">

The statements are correct: the RNA polymerase *protein* does the transcription; protein metabolic process should not be inferred. 

Can we modify the rules such that the type of the entity enabling a process is not taking into account for the process it mediates ? I cannot think if a case where that's necessary. 


Thanks, Pascale

**Comment by vanaukenk** [comment]
Here is a related example of unwanted inferences when using a protein accession as has_input for a DNA binding annotation:

http://noctua.berkeleybop.org/editor/graph/gomodel:5b528b1100000224

@RLovering

**Comment by vanaukenk** [comment]
See also:

https://github.com/oborel/obo-relations/pull/291
https://github.com/geneontology/go-ontology/pull/16797
https://github.com/geneontology/noctua/issues/584

**Comment by vanaukenk** [comment]
This appears to be fixed.
