### ISSUE TITLE
Send proper HTTP codes for SPARQL client errors

### ISSUE THREAD

**Issue by balhoff** [geneontology/minerva#203]
Currently malformed queries to the embedded SPARQL endpoint will return `500` server fault codes. These exceptions should be handled correctly to return client errors.

**Comment by kltm** [comment]
I had thought we were modeling this on the current Barista pattern, where it would have the same pattern for input and returns as other endpoints? This seems to be a separate system entirely.

**Comment by balhoff** [comment]
Can you explain more what you are looking for? Do you want to send the SPARQL query inside a JSON structure? What would you want to get back? If the endpoint allows arbitrary SPARQL queries, it will not be able to always fit the results into something like the JSON that the batch endpoint returns.

**Comment by kltm** [comment]
No problem.
Basically, (grossly) we're looking for an endpoint that takes something flavored like:

```json
{
            "uid": "xyz",
            "intention": "query",
            "provided-by": [
                "foo:bar",
                "bar:bib"
            ],
            "requests": [
                {
                    "entity": "meta",
                    "sparql": "SPARQL_QUERY",
                    "sparql-arguments": {"SPARQL_PROTOCOL_BITS": "FOO"}
                 }
            ]
}
```

and returns some variation of:

```json

{
 "packet-id": "2b54a15a3390a14",
 "uid": "GOC:kltm",
 "intention": "query",
 "signal": "rebuild",
 "message-type": "success",
 "message": "success",
 "data": {
  "id": "gomodel:55ad81df00000001",
  "modified-p": true,
  "query-response": {"SPARQL_JSON_RESPONSE": "BAR"}
}
```

This meshes with the proxy server parts of Barista.
