### ISSUE TITLE
Incorrect inferences for has input

### ISSUE THREAD

**Issue by ukemi** [geneontology/minerva#204]
While doing an annotation review of this annotation:

mASAP1/isom1/UnPhos1 Mmus | enables | protein binding | PMID:12771146 | direct assay evidence used in manual assertion |   |   | 20161216 | MGI | has_input(1-phosphatidyl-1D-myo-inositol 4,5-bisphosphate) | contributor=http://orcid.org/0000-0001-7476-6306\|model-state=production\|noctua-model-id=gomodel:581e072c00000473
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

from this model:
http://noctua.berkeleybop.org/editor/graph/gomodel:581e072c00000473

We can see that there is an inference of protein binding with input of a chemical. This seems incorrect or misleading.

I believe it is a result of these rules:
( ?x2 type molecular_function ) ∧ ( ?x3 directly_regulates ?x2 ) ∧ ( ?x3 type molecular_function ) ∧ ( ?x1 enables ?x2 ) → ( ?x3 has_input ?x1 )
,
( ?x1 type enzyme activator activity ) → ( ?x1 type molecular_function )
,
( ?x1 type binding ) ∧ ( ?x1 has_input ?x2 ) ∧ ( ?x2 type protein ) → ( ?x1 type protein binding )

We need to investigate and correct this. It might be traceable to having generic inputs.

**Comment by goodb** [comment]
@ukemi I think your assessment is correct regarding the explanation.  I'm wondering if this inference is generally desirable ?:
( ?x2 type molecular_function ) ∧ ( ?x3 directly_regulates ?x2 ) ∧ ( ?x3 type molecular_function ) ∧ ( ?x1 enables ?x2 ) → ( ?x3 has_input ?x1 )

**Comment by goodb** [comment]
I set up another model in noctua-dev to experiment:
http://noctua-dev.berkeleybop.org/editor/graph/gomodel:5b4695e900000439  

Experiments there show that many of the terms that appear in the 'gene product' searches are not typed as proteins (indeed often not typed as anything).  e.g. Cdk2 Mmus , Vipr1 Mmus.  This is also evident on the production Noctua.  If genes like these are swapped in for one that are typed as proteins (like [PR:Q8CEE6] mPASK Mmus) the inference in question in the ticket won't happen.  

I wonder if the reason we haven't noticed this problem before is that the reasoner has not known what kinds of gene products it has been looking at.  This seems like an important thing to fix.

**Comment by pgaudet** [comment]
This is the same problem I had with the transcription factor example, isn't it ?

**Comment by ukemi** [comment]
It is not exactly the same, but stems from the same errors. I think we really need to step back and look at the algebra of property chains, particularly for regulates relations.

**Comment by vanaukenk** [comment]
This seems to be fixed.
