### ISSUE TITLE
Inferences explanation giving an error

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/minerva#207]
Hi,

I was attempting to view the Inference explanations on the canonical Wnt model this morning, but am getting an error message:

Error (error): Could not successfully handle batch request. Exception: java.lang.NullPointerException.; your operation was likely not performed.

The model id is:

http://noctua.geneontology.org/editor/graph/gomodel:596ef51500000088

**Comment by balhoff** [comment]
@ukemi and I were just looking at this yesterday afternoon. I will try to figure out the problem.

**Comment by vanaukenk** [comment]
Thank you @balhoff

**Comment by vanaukenk** [comment]
The inferences explanations seems to be working fine again, so I'm closing this ticket.
