### ISSUE TITLE
xrefs between different cell and anatomy ontologies included in annotation extensions

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/minerva#210]
In one of our WB models, we get extra annotation extensions that look to be from xrefs between CL, UBERON, and WBbt.  This results in what seem to be 'redundant' annotation extensions that, even though they refer to IDs from different ontologies, do not necessarily add more biological information.

Here's an example line from our derived GPAD:

WB	WBGene00008748	part_of	GO:0005634	PMID:29853655	ECO:0000314			20180619	WB	part_of(CL:0000101),part_of(CL:0002242),part_of(UBERON:0001062),part_of(WBbt:0005406)	noctua-model-id=gomodel:5ae3b0f600001520|contributor=http://orcid.org/0000-0002-1706-4196|model-state=production

The model was made using WBbt:0005406 (ALM, a mechanosensory neuron) but we also get part_of extensions to CL:0000101 (sensory neuron), CL:0002242 (nucleate cell), and UBERON:0001062 (anatomical entity).

When we parse this line for import into WB, we are only taking the WBbt annotation extension, but I'm wondering if we need/want the additional extensions in the derived GPAD files since they are less granular than the original annotation and I am not sure how to interpret the comma-separated list wrt our current specifications for multiple annotation extensions.

Also, I may have missed it, but I was not able to see an inference explanation for CL:0002242 (nucleate cell).

**Comment by cmungall** [comment]
Adding the uberon-wbbt and cl-wbbt bridge into the imports will resolve the redundancies. Can we try this with worm first and then expand to other species @balhoff ?

**Comment by balhoff** [comment]
I did a quick check in Protégé and I don't see any unsatisfiable classes when I combine WBbt, Uberon, and the two bridges. This is a big improvement over the result last spring!

**Comment by ukemi** [comment]
This may be related to #335.

**Comment by vanaukenk** [comment]
This particular issue appears to be fixed.  If other cell and/or anatomy issues arise, we'll open separate tickets.
