### ISSUE TITLE
In some cases, class expressions disappear from individuals

### ISSUE THREAD

**Issue by kltm** [geneontology/minerva#218]
In some cases, possibly related to the removal or merging of GO terms in the ontology, individuals are appearing without class expressions. We currently have no mechanism for controlled repeat.

With gomodel:586fc17a00000381 as an example (go back about two weeks ago?). Tagging @balhoff @ukemi

**Comment by ukemi** [comment]
I am pretty sure what happened in this case was I had added a relationship that had modified one of the behavior nodes. It seemed like the relation between the modifier class and behavior disappeared, but the modifier class and the evidence still remained as 'unconnected' individuals.

**Comment by balhoff** [comment]
@ukemi should we close this, or investigate further?
