### ISSUE TITLE
Filter annotations with negative causality?

### ISSUE THREAD

**Issue by ukemi** [geneontology/minerva#220]
If we make an annotation that GP1 enables MF1 and MF1 is 'causally upstream of or within, negative effect' BP1, the resulting process annotation will be  'acts upstream of or within, negative effect'. If we load this into a MOD database and it is represented in a gaf or exported in a gaf, the qualifier is not reported and the negative effect is lost. Therefore the annotation is misleading. Should we filter these annotations out of the GPAD file? In the past curators may have annotated these to negative regulation of x, but that was not accurate.

Model: http://noctua.geneontology.org/editor/graph/gomodel:5c4605cc00001638
Annotation: Bmp4 Mmus | acts_upstream_of_or_within_negative_effect | limb joint morphogenesis | PMID:1 | mutant phenotype evidence used in manual assertion |   |   | 20190304 | MGI |   | noctua-model-id=gomodel:5c4605cc00001638\|contributor=http://orcid.org/0000-0001-7476-6306\|model-state=development
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by pgaudet** [comment]
Sounds like a good idea to filter these out.

**Comment by ukemi** [comment]
Or put the onus on the consuming groups? Ideally we would like to have the richer representation that is in the GPAD file and allow users to slice and dice the annotation sets they retrieve. So will it be the responsibility of the GOC to provide all of the data available and guide users with respect to its use, or do we want to provide different snapshots of the data as GOC products?  @kltm, what do you think?

**Comment by kltm** [comment]
@ukemi I think this is essentially saying that there would be different outputs from the GO that adhered to different GO Rule sets, which I think is probably a weird place to go. If the information is useful to somebody it should probably be included; if the information is useful to nobody it should be removed.

**Comment by ukemi** [comment]
@kltm I talked about this with @hdrabkin this morning as well. We agreed with what you are saying. So if we do not have the ability to display the annotation qualifiers at this point and we think that the annotations would be misleading displayed as they appear in gafs, it would be up to us to filter them appropriately. We might want to touch base about this on a mangers' call. One consequence of this might be confusing Users as to why the annotation sets they are getting from resource X aren't exactly the same as the ones they are getting from the GOC.

**Comment by goodb** [comment]
I would argue against taking this (or any other correct and useful) information out of the GPAD output.  Why waste the curator's efforts that created these annotations when there is a clear, tab-delimited even.. way of expressing it ? 

When GPADs are converted to GAF, there ought to be a rule that would prevent misleading information resulting from the inexpressiveness of the GAF format.  Such rules ought to be consolidated in a single library (e.g. ontobio) that can help keep things stable across resources.  

But in the end, the real solution is very straightforward for once.  GAF must die.  It is wasting our time.

**Comment by pgaudet** [comment]
I added this to our proposal to create a simpler GAF (or whatever the format - a file that would be more straightforward to interpret for users)
https://github.com/geneontology/go-annotation/issues/1932

I suggest we close this ticket here.
