### ISSUE TITLE
GP Class Type Ids not resolved

### ISSUE THREAD

**Issue by tmushayahama** [geneontology/minerva#221]
@kltm related to  (https://github.com/geneontology/neo/issues/38)

If you check the individual of a gene product, their respective type ids are not resolved to their curie. 

![image](https://user-images.githubusercontent.com/2273929/54303638-b0737d80-4580-11e9-9079-fcde808e5c70.png)

**More Info**
Looking at the same model, it seems like it works in production version but not in the dev

Response from Dev
![image](https://user-images.githubusercontent.com/2273929/54303564-7dc98500-4580-11e9-8be2-39ac2b7a5825.png)

Response from Prooduction (correct one)
![image](https://user-images.githubusercontent.com/2273929/54303593-93d74580-4580-11e9-9745-f0b87811c1f0.png)

**Comment by goodb** [comment]
@tmushayahama I believe this has been resolved.  Please confirm.
