### ISSUE TITLE
CURIEs & IRIs transformed

### ISSUE THREAD

**Issue by lpalbou** [geneontology/minerva#225]
@balhoff @kltm It can be a bit misleading that Minerva is transforming the results of a SPARQL query; I have seen that in the past where I was expecting to retrieve a IRI and was retrieving a transformed CURIE.

In @tmushayahama ART, this is causing an issue as he is chaining the results of SPARQL queries and was not expecting those variables to be transformed. There are workarounds on the client side, but we want to avoid too much logics or transformations on this end.

Proposed action: have a tag in minerva requests to block or enable the current transform in the response

**Comment by goodb** [comment]
turning off direct sparql query access
