### ISSUE TITLE
SPARQL - Finding models by PMID QUERY Timing out 

### ISSUE THREAD

**Issue by tmushayahama** [geneontology/minerva#227]
This query is timing out but not on the http://rdf-internal.berkeleybop.io/blazegraph/#query endpoint

### Query 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX metago: <http://model.geneontology.org/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX GO: <http://purl.obolibrary.org/obo/GO_>
PREFIX BP: <http://purl.obolibrary.org/obo/GO_0008150>
PREFIX MF: <http://purl.obolibrary.org/obo/GO_0003674>
PREFIX CC: <http://purl.obolibrary.org/obo/GO_0005575>
PREFIX modelState: <http://geneontology.org/lego/modelstate>
PREFIX providedBy: <http://purl.org/pav/providedBy>
PREFIX vcard: <http://www.w3.org/2006/vcard/ns#>
PREFIX has_affiliation: <http://purl.obolibrary.org/obo/ERO_0000066>
PREFIX enabled_by: <http://purl.obolibrary.org/obo/RO_0002333>
PREFIX evidence: <http://geneontology.org/lego/evidence>
PREFIX in_taxon: <http://purl.obolibrary.org/obo/RO_0002162>
PREFIX obo: <http://www.geneontology.org/formats/oboInOwl#>
SELECT distinct ?model ?modelTitle ?modelState ?date
	(GROUP_CONCAT(distinct ?entity;separator="@@") as ?entities)
	(GROUP_CONCAT(distinct ?orcid;separator="@@") as ?contributors)
	(GROUP_CONCAT(distinct ?providedBy;separator="@@") as ?groups)

WHERE{
GRAPH ?model {
?model dc:date ?date; dc:title ?modelTitle; modelState: ?modelState; providedBy: ?providedBy; dc:contributor ?orcid.
OPTIONAL {
?model providedBy: ?providedBy
}.
?axiom evidence: ?evidence.
?axiom owl:annotatedSource ?entity.
?evidence dc:source ?source.
BIND(REPLACE(?source, " ", "") AS ?source).
FILTER(?source="pmid:1234")
}

}

GROUP BY ?model ?modelTitle ?modelState ?date
ORDER BY DESC (?date)
LIMIT 50

### Error message
{  
   "packet-id":"2942213fbac76711b",
   "provided-by":[  

   ],
   "is-reasoned":false,
   "intention":"action",
   "message-type":"error",
   "message":"Could not successfully handle batch request. Exception: org.openrdf.query.QueryInterruptedException. java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.bigdata.bop.engine.QueryTimeoutException: Query deadline is expired.",
   "commentary":"org.openrdf.query.QueryInterruptedException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.bigdata.bop.engine.QueryTimeoutException: Query deadline is expired.\n\tat com.bigdata.rdf.sail.Bigdata2Sesame2BindingSetIterator.hasNext(Bigdata2Sesame2BindingSetIterator.java:184)\n\tat info.aduna.iteration.IterationWrapper.hasNext(IterationWrapper.java:68)\n\tat org.openrdf.query.QueryResults.report(QueryResults.java:155)\n\tat org.openrdf.query.resultio.QueryResultIO.write(QueryResultIO.java:634)\n\tat org.geneontology.minerva.json.SPARQLResultJSONRenderer.renderResults(SPARQLResultJSONRenderer.java:32)\n\tat org.geneontology.minerva.server.handler.OperationsImpl.handleSPARQLRequest(OperationsImpl.java:543)\n\tat org.geneontology.minerva.server.handler.JsonOrJsonpBatchHandler.m3Batch(JsonOrJsonpBatchHandler.java:183)\n\tat org.geneontology.minerva.server.handler.JsonOrJsonpBatchHandler.m3Batch(JsonOrJsonpBatchHandler.java:125)\n\tat org.geneontology.minerva.server.handler.JsonOrJsonpBatchHandler.m3BatchPost(JsonOrJsonpBatchHandler.java:78)\n\tat sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)\n\tat org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:151)\n\tat org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:171)\n\tat org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:195)\n\tat org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:104)\n\tat org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:402)\n\tat org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:349)\n\tat org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:106)\n\tat org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:259)\n\tat org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)\n\tat org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)\n\tat org.glassfish.jersey.internal.Errors.process(Errors.java:315)\n\tat org.glassfish.jersey.internal.Errors.process(Errors.java:297)\n\tat org.glassfish.jersey.internal.Errors.process(Errors.java:267)\n\tat org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:318)\n\tat org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:236)\n\tat org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1010)\n\tat org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:373)\n\tat org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:382)\n\tat org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:345)\n\tat org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:220)\n\tat org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:547)\n\tat org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:480)\n\tat org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:225)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:941)\n\tat org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:409)\n\tat org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:875)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:110)\n\tat org.eclipse.jetty.server.Server.handle(Server.java:349)\n\tat org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:441)\n\tat org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:936)\n\tat org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:801)\n\tat org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:224)\n\tat org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:51)\n\tat org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:586)\n\tat org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:44)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:598)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:533)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.bigdata.bop.engine.QueryTimeoutException: Query deadline is expired.\n\tat com.bigdata.relation.accesspath.BlockingBuffer$BlockingIterator.checkFuture(BlockingBuffer.java:1484)\n\tat com.bigdata.relation.accesspath.BlockingBuffer$BlockingIterator._hasNext(BlockingBuffer.java:1710)\n\tat com.bigdata.relation.accesspath.BlockingBuffer$BlockingIterator.hasNext(BlockingBuffer.java:1563)\n\tat com.bigdata.striterator.AbstractChunkedResolverator._hasNext(AbstractChunkedResolverator.java:365)\n\tat com.bigdata.striterator.AbstractChunkedResolverator.hasNext(AbstractChunkedResolverator.java:341)\n\tat com.bigdata.rdf.sail.Bigdata2Sesame2BindingSetIterator.hasNext(Bigdata2Sesame2BindingSetIterator.java:134)\n\t... 52 more\nCaused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.bigdata.bop.engine.QueryTimeoutException: Query deadline is expired.\n\tat java.util.concurrent.FutureTask.report(FutureTask.java:122)\n\tat java.util.concurrent.FutureTask.get(FutureTask.java:192)\n\tat com.bigdata.relation.accesspath.BlockingBuffer$BlockingIterator.checkFuture(BlockingBuffer.java:1454)\n\t... 57 more\nCaused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.bigdata.bop.engine.QueryTimeoutException: Query deadline is expired.\n\tat com.bigdata.rdf.sail.RunningQueryCloseableIterator.checkFuture(RunningQueryCloseableIterator.java:59)\n\tat com.bigdata.rdf.sail.RunningQueryCloseableIterator.close(RunningQueryCloseableIterator.java:73)\n\tat com.bigdata.rdf.sail.RunningQueryCloseableIterator.hasNext(RunningQueryCloseableIterator.java:82)\n\tat com.bigdata.striterator.ChunkedWrappedIterator.hasNext(ChunkedWrappedIterator.java:197)\n\tat com.bigdata.striterator.AbstractChunkedResolverator$ChunkConsumerTask.call(AbstractChunkedResolverator.java:222)\n\tat com.bigdata.striterator.AbstractChunkedResolverator$ChunkConsumerTask.call(AbstractChunkedResolverator.java:197)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\t... 1 more\nCaused by: java.util.concurrent.ExecutionException: com.bigdata.bop.engine.QueryTimeoutException: Query deadline is expired.\n\tat com.bigdata.util.concurrent.Haltable.get(Haltable.java:273)\n\tat com.bigdata.bop.engine.AbstractRunningQuery.get(AbstractRunningQuery.java:1516)\n\tat com.bigdata.bop.engine.AbstractRunningQuery.get(AbstractRunningQuery.java:104)\n\tat com.bigdata.rdf.sail.RunningQueryCloseableIterator.checkFuture(RunningQueryCloseableIterator.java:46)\n\t... 9 more\nCaused by: com.bigdata.bop.engine.QueryTimeoutException: Query deadline is expired.\n\tat com.bigdata.bop.engine.RunState.checkDeadline(RunState.java:832)\n\tat com.bigdata.bop.engine.RunState.startOp(RunState.java:753)\n\tat com.bigdata.bop.engine.AbstractRunningQuery.startOp(AbstractRunningQuery.java:789)\n\tat com.bigdata.bop.engine.QueryEngine.startOp(QueryEngine.java:1358)\n\tat com.bigdata.bop.engine.ChunkedRunningQuery$ChunkTaskWrapper.run(ChunkedRunningQuery.java:912)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat com.bigdata.concurrent.FutureTaskMon.run(FutureTaskMon.java:63)\n\tat com.bigdata.bop.engine.ChunkedRunningQuery$ChunkFutureTask.run(ChunkedRunningQuery.java:821)\n\t... 3 more\n"
}

**Comment by goodb** [comment]
I believe this should be closed.  Query by pmid via API e.g.
http://barista-dev.berkeleybop.org/search?pmid=PMID:123

Though @kltm  note that the above URL is not currently responsive from my location - reporting Cannot GET /search?pmid=PMID:123   Should it be ?

**Comment by kltm** [comment]
The test closing https://github.com/geneontology/noctua/issues/619 (http://barista-dev.berkeleybop.org/search?gp=http://identifiers.org/wormbase/WBGene00002246&offset=0&limit=2) does not seem to work either...looking into it.

**Comment by kltm** [comment]
Ugh, okay, this is "intended".

Basically, the dev machine switched over to a different branch to test copy and that branch does not have the proxy on it. See: https://github.com/geneontology/noctua/issues/606#issuecomment-510712122
I was *really* hoping to get action on https://github.com/geneontology/noctua/issues/620 first, but we'll have to go one way or another so as not to hold things up. I'll have a plan by the end of tomorrow.

**Comment by lpalbou** [comment]
@kltm I wasn't aware https://github.com/geneontology/noctua/issues/620 was a priority or blocking anything. I also had trouble understanding why a separate branch was deployed to test the model copy rather than just merging it on dev.

@tmushayahama 3 comments:
* although not fast, your query is working: http://yasgui.org/short/82komGlkD . Note that including only the required PREFIX would really improve readability
* I am pretty sure that any PMIDs added as evidence on statements are also copied in the model dc:source field (@kltm do you confirm ?), so you can use faster and simpler query: https://github.com/geneontology/api-gorest/blob/master/queries/sparql-pmids.js (that's what the gocam site has been using)
* Having said that, ben is right, it's better and more consistent now to use his API to search by PMIDs so no reason to use SPARQL here
