### ISSUE TITLE
Sparql Query Finding models by Species not giving results

### ISSUE THREAD

**Issue by tmushayahama** [geneontology/minerva#228]
Supporting https://github.com/geneontology/minerva/issues/226 issue here is an example of the query with empty results 
but works using http://rdf-internal.berkeleybop.io/blazegraph/#query

### Query

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX metago: <http://model.geneontology.org/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX GO: <http://purl.obolibrary.org/obo/GO_>
PREFIX BP: <http://purl.obolibrary.org/obo/GO_0008150>
PREFIX MF: <http://purl.obolibrary.org/obo/GO_0003674>
PREFIX CC: <http://purl.obolibrary.org/obo/GO_0005575>
PREFIX modelState: <http://geneontology.org/lego/modelstate>
PREFIX providedBy: <http://purl.org/pav/providedBy>
PREFIX vcard: <http://www.w3.org/2006/vcard/ns#>
PREFIX has_affiliation: <http://purl.obolibrary.org/obo/ERO_0000066>
PREFIX enabled_by: <http://purl.obolibrary.org/obo/RO_0002333>
PREFIX evidence: <http://geneontology.org/lego/evidence>
PREFIX in_taxon: <http://purl.obolibrary.org/obo/RO_0002162>
PREFIX obo: <http://www.geneontology.org/formats/oboInOwl#>
SELECT distinct ?model ?modelTitle ?modelState ?date
	(GROUP_CONCAT(distinct ?entity;separator="@@") as ?entities)
	(GROUP_CONCAT(distinct ?orcid;separator="@@") as ?contributors)
	(GROUP_CONCAT(distinct ?providedBy;separator="@@") as ?groups)

WHERE{
GRAPH ?model {
?model dc:date ?date; dc:title ?modelTitle; modelState: ?modelState; providedBy: ?providedBy; dc:contributor ?orcid.
OPTIONAL {
?model providedBy: ?providedBy
}.
?s enabled_by: ?entity.
?entity rdf:type ?identifier.
FILTER(?identifier != owl:NamedIndividual)
}
 .
?identifier rdfs:subClassOf ?v0 .
?identifier rdfs:label  ?name .
?v0 owl:onProperty  in_taxon: .
?v0 owl:someValuesFrom <http://purl.obolibrary.org/obo/NCBITaxon_6239>
}

GROUP BY ?model ?modelTitle ?modelState ?date
ORDER BY DESC (?date)
LIMIT 50

### Result 

{  
   "packet-id":"2942d07a0f5a8e123",
   "provided-by":[  

   ],
   "is-reasoned":false,
   "intention":"action",
   "signal":"meta",
   "message-type":"success",
   "message":"success: 0",
   "data":{  
      "sparql-result":{  
         "head":{  
            "vars":[  
               "model",
               "modelTitle",
               "modelState",
               "date",
               "entities",
               "contributors",
               "groups"
            ]
         },
         "results":{  
            "bindings":[  

            ]
         }
      }
   }
}

**Comment by goodb** [comment]
Use new route e.g. http://noctua-dev.berkeleybop.org:6800/search/?taxon=7955 
See https://github.com/geneontology/minerva/wiki/Minerva-Model-Search-API
