### ISSUE TITLE
Metago not working: Sparql query to find model stats

### ISSUE THREAD

**Issue by tmushayahama** [geneontology/minerva#229]
This query works on http://rdf-internal.berkeleybop.io/blazegraph/#query . 

### Use Cases

- To find all the contributors, groups, organisms, bps, gps of all models,
- To group by the model counts of the above 

 ### Query

 PREFIX metago: <http://model.geneontology.org/>
    PREFIX dc: <http://purl.org/dc/elements/1.1/>
    PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
    PREFIX has_affiliation: <http://purl.obolibrary.org/obo/ERO_0000066> 
    PREFIX hint: <http://www.bigdata.com/queryHints#>

    SELECT  ?cam
    WHERE    
    {
      ?cam metago:graphType metago:noctuaCam .
    }`

**Or If I remove the metago and use the plain url**
 PREFIX dc: <http://purl.org/dc/elements/1.1/>
    PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
    PREFIX has_affiliation: <http://purl.obolibrary.org/obo/ERO_0000066> 
    PREFIX hint: <http://www.bigdata.com/queryHints#>

    SELECT  ?cam
    WHERE    
    {
      ?cam <http://model.geneontology.org/graphType> <http://model.geneontology.org/noctuaCam> .
    }

### Result

empty result, []

**Comment by balhoff** [comment]
There is no `<http://model.geneontology.org/graphType>` predicate in Minerva. This is something @dougli1sqrd is adding in the public triplestore build.

**Comment by balhoff** [comment]
You can do something like this:

```sparql
PREFIX owl: <http://www.w3.org/2002/07/owl#>
SELECT  ?cam
WHERE    
{
  ?cam a owl:Ontology .
}
```
