### ISSUE TITLE
Make GPAD export uniprot-centric for human reactome models

### ISSUE THREAD

**Issue by goodb** [geneontology/minerva#245]
In cases where imported models may use vocabularies other than uniprot to identify genes, e.g. reactome entity ids, ensure that the gpad export process maps these to their uniprot counterparts (for human).

**Comment by ukemi** [comment]
Should we expand on this to make it go beyond just Reactome? Another example: MGI imports annotations from UniProtKB that are to mouse proteins. When we load those annotations, we convert the UniProtKB identifers to MGI gene identifiers and we export them as annotations to MGI genes (identifiers) in our gaf. Down the road, all of this will be done at the GOC. Would it make sense to have a unified strategy for data flow where in the primary resource, identifiers that come from the respected groups are retained, but when we output them, they are associated with the sanctioned identifiers from each of the respective MODs (ie are in their GPI files)? Just seems like we are going to have to face this problem again in the future as part of multiple data loads. @kltm @cmungall @vanaukenk

**Comment by kltm** [comment]
Noting: https://github.com/geneontology/go-site/issues/756#issuecomment-470240536
I believe that there is another Uniprot-centric one out there somewhere, but I'm having trouble finding it...

**Comment by ukemi** [comment]
I've made models for human genes using UniProt identifiers. Is that what you are looking for?

**Comment by ukemi** [comment]
http://noctua.berkeleybop.org/editor/graph/gomodel:586fc17a00000528

**Comment by kltm** [comment]
@ukemi I'm referring to a ticket that I believe exists that discusses the use of Uniprot for out put, similar to @cmungall 's comment in geneontology/go-site#756, but as a ticket item.

**Comment by ukemi** [comment]
Ah. OK sorry.

**Comment by goodb** [comment]
I do think that the sentiment expressed in geneontology/go-site#756 applies here and argues for a fairly general purpose solution as @ukemi was saying.  When working at the dumbed-down level of flat, tab-delimited export files, we should indeed try to keep the gene identifiers in as consistent a form as we can.  

Bringing this back into the Minerva space for a moment.  This implies that, assuming we allow for the use of identifiers within Noctua that are different from what we want to output generically (as I strongly think we do) then we need to define a protocol for delivering the mapping from whatever the other source is (e.g. reactome, ncbi gene, ensemble gene, etc.) to the default id space for that organism (e.g. UniProt for human).  

For the Reactome work, on this issue, I constructed a (one to many) mapping from reactome entity id to UniProt id. This could be applied at the point where GPAD is constructed to deliver the annotations in the UniProt id space.  Is it scalable to build a collection of mapping files like that in advance and load them into Minerva?  How many would we need ?  There is likely to be custom logic to apply depending on the source and target of the mappings.

**Comment by ukemi** [comment]
It was my understanding that this was the purpose of the GPI file. Each authority (MOD) would define valid identifiers for their organism's annotation space. For most (all?) MODS those would map to their gene identifiers.

**Comment by goodb** [comment]
@ukemi I think the issue occurs when there is more than one identifier representing what some users would assume is the same concept within the noctua/go-lego entity space.  The fact that that happens seems to indicate that the GPI files aren't the only place where entity ids are retrieved from.  That is certainly the case for the trouble I am causing with Reactome and REO..  My suggestion is that it ought to be okay to add additional identifiers into the mix as long as there is a way that Minerva can convert them to the default space for the given organism (as I guess could be determined by its GPI).  We want to have access to the mappings within go central software.

**Comment by goodb** [comment]
Closing as code currently implements uniprot-centric gpad export for human models.  If we want to expand on this concept, lets open a new issue as that would likely touch many different projects (neo, go-site, gpis, etc.)

**Comment by ukemi** [comment]
@goodb We still need some curators to sanity check the annotations that are coming from the models. @deustp01 and I still haven't had a chance to do that yet.

**Comment by goodb** [comment]
@ukemi yes, GPAD not done.  Though I think uniprot part is.  Consolidating over to https://github.com/geneontology/pathways2GO/issues/52

**Comment by ukemi** [comment]
Good to separate out the tasks.
