### ISSUE TITLE
Add IntAct to import chain

### ISSUE THREAD

**Issue by cmungall** [geneontology/minerva#25]

**Comment by nataled** [comment]
Added for historical tracking purposes:

Query (CM):

  Do you have a conversion of IntAct already? E.g. for
  http://www.ebi.ac.uk/intact/complex/details/EBI-767678

  with has_part relationships to the UniProt classes

Response (DN):
  No, we do not have such a translation. In fact, we don't yet even have an import of the (possible not-in-PRO) proteoforms described there. The first step we must take is to develop an accurate mapping between IntAct proteoforms and PRO proteoforms (good headway made on this, using Reactome as a test case). Then, we'd create the PRO terms for those proteoforms (I do not yet even have an estimate of the upper bound for this). With those in hand, we would then tackle the issue of placing the IntAct complexes in a hierarchy.

Follow-up (CM):
  OK, for our purposes we don't need the hierachy, just the parts in OWL (not even necessarily closed) and a parent of 'complex'

**Comment by nataled** [comment]
I understand the "parts in OWL" need (you mean the proteoforms, as we call them). But not sure what is meant by "parent of 'complex'"

**Comment by cmungall** [comment]
E.g.
http://wwwdev.ebi.ac.uk/intact/complex/details/EBI-8790722

==>

    SubClassOf 'GO:protein complex' AND
      has_part some PR:P31376 AND
      ...
      has_part some PR:Q03388

**Comment by nataled** [comment]
Understood. Thanks.
