### ISSUE TITLE
Task 3 - API - add search models by ontology terms other than GO

### ISSUE THREAD

**Issue by lpalbou** [geneontology/minerva#291]
Task requirement from Noctua Landing Page Project

This will be a three steps task:
- [x] include ontologies such as Uberon, CL in blazegraph
- [x] make sure one can perform a closure search (eg retrieve models also containing the more specific/children terms of the specified term)
- [x] Provide the API route for NLP UI

Also linked to https://github.com/geneontology/minerva/issues/230

**Comment by goodb** [comment]
@lpalbou out of curiosity, what is the NLP UI ?  Is the API route for this expected to be any different from the API used to drive the search?  

if you have time, a list test cases and expected results are always handy.

**Comment by goodb** [comment]
@lpalbou the search as it stands has a parameter ?goterm that should probably have been named something more generic like ?term .  That searches over all ontology terms used to provide an rdf:type used in the models, including anatomy etc.  

I've just done some successful tests with an extension to this that does query expansion down the subclass tree.  

1. When I commit this, do you want this generic ontology parameter renamed to e.g. "term" 
2. Do you want query expansion to be optional or always on?  
3. Do we need query expansion to run down the "part of" children as well as the subclasses ?  If yes, this needs further specification.  e.g. we might not want to expand down from biological processes to molecular function parts etc.

**Comment by goodb** [comment]
For testing this week.  Will deploy this with the parameter goterm changed to term , with closure search always on and only looking at subclass descendants, not part of.

**Comment by lpalbou** [comment]
@goodb sorry for the delay.

NLP stands for [Noctua Landing Page](https://github.com/geneontology/noctua-landing-page), based on the Noctua Search of @tmushayahama . So it is the same project / search that we have been discussing.

A prototype is available on dev: http://noctua-dev.berkeleybop.org/workbench/noctua-landing-page and ping me on Gitter to setup a demo and give you more contexts.

> ?goterm that should probably have been named something more generic like ?term 
> When I commit this, do you want this generic ontology parameter renamed to e.g. "term"

Yes please. @tmushayahama you will have to adjust your queries.

> Do you want query expansion to be optional or always on?

Optional at the moment. It could become permanent if we were to highlight/explain the matched results in the response.

> on and only looking at subclass descendants, not part of.

Sounds good at the moment. @vanaukenk any preference ?

Thanks Ben

**Comment by goodb** [comment]
@lpalbou ahh..  in my previous worlds NLP stands for something a bit different.  I thought maybe you were talking about one of the tools the worm base developers have for pre-processing text. Thanks for clarifying.   I made query expansion optional and updated docs.  I am working in this branch now in case anyone was keen to test anything before it gets PRd into dev. https://github.com/geneontology/minerva/tree/bugfixes-on-blazegraph-conversion.

**Comment by goodb** [comment]
RE: https://github.com/geneontology/minerva/issues/230#issuecomment-606984333 

The most recent PR (not yet available on dev) makes expansion optional.  By default it is off.  Adding the &expand parameter will return results from all subclasses of the submitted term.  If you want to search by root terms I will need to do some optimization.  

Let me know about priority on that optimization.

**Comment by goodb** [comment]
^ @tmushayahama

**Comment by tmushayahama** [comment]
referring to https://github.com/geneontology/minerva/issues/230#issuecomment-606984333

@goodb root term was only an example, but It is giving "Query Timeout Exception" on other most higher up terms as well, I also tried with 
**"catalytic activity"**
http://barista-dev.berkeleybop.org/search?offset=0&limit=50&term=GO:0003824&count
or **"biological regulation"**
http://barista-dev.berkeleybop.org/search?offset=0&limit=50&term=GO:0065007
and same time out exception. I don't know where the threshold is.

I was extra: I tried these big terms below, term = "localization" works
![image](https://user-images.githubusercontent.com/2273929/78104043-456f3180-73a3-11ea-8934-6386781a3926.png)

For later, it will be nice to send it as an error message for all exceptions. For now it is 200ok

tagging @vanaukenk @lpalbou

**Comment by lpalbou** [comment]
Referring to https://github.com/geneontology/minerva/issues/230#issuecomment-606984333.

Let's discuss it with @vanaukenk . I would not concern with aspect terms (MF/BP/CC) but one would want to be able to search over catalytic_activity indeed.

@tmushayahama ben has increased the timeout in its commit. It could be sufficient for now but we'll have to see where this comes from. @goodb is it in the SPARQL query ? Or in some subsequent queries you do further annotate the results before sending them back to tremayne ?

Thanks

**Comment by goodb** [comment]
@lpalbou its in the sparql query over the model collection.  Kind of surprised it was such a problem.  Will need to look at it to see what's up.

**Comment by tmushayahama** [comment]
Thanks @goodb @lpalbou for the quick response. @vanaukenk @lpalbou should I make search  by exact term default and subtype can be turned on? Or subtype is always on?
