### ISSUE TITLE
Task 3 - API - add search models by date (specific & range)

### ISSUE THREAD

**Issue by lpalbou** [geneontology/minerva#292]
Task requirement from Noctua Landing Page Project

Provide an API route to search for models whose date is either a specific date or a date range.

Also linked to https://github.com/geneontology/minerva/issues/230

Note: this will be revisited when we review our strategy on dates (eg created/last modified date)

**Comment by tmushayahama** [comment]
@goodb @lpalbou I think a tiny issue is the date range to be inclusive with the either boundary or all. 
right now it is 
`from date < date < to date`, however from Tuesday to Wednesday always retrieve 0 results
Depending on the use case maybe one of these
`from date <= date < to date`
`from date <= date <= to date`
f`rom date < date <= to date`
