### ISSUE TITLE
Task 3 - API - add route to list the currently existing model states

### ISSUE THREAD

**Issue by lpalbou** [geneontology/minerva#293]
Task requirement from Noctua Landing Page Project

Create a route /states that will provide the list of all distinct states currently registered in the models. 

Also linked to https://github.com/geneontology/minerva/issues/230

Note: this is needed on the UI side to avoid hardcoded list of states

**Comment by goodb** [comment]
I suggest that the allowed list of model states should be stored in the noctua configuration file or something along those lines.

**Comment by lpalbou** [comment]
+1 to add to the configuration file. But not a priority, can still use hardcoded. Closing ticket that can be reopened later.

**Comment by vanaukenk** [comment]
@tmushayahama - is the list of model states in Noctua still hard-coded?  I suspect it is based on https://github.com/geneontology/noctua-form/issues/158
