### ISSUE TITLE
Task 3 - API - add route to return the number of models for a set of contributors

### ISSUE THREAD

**Issue by lpalbou** [geneontology/minerva#294]
Task requirement from Noctua Landing Page Project

For a given set of contributors, return a list of { contributor: id, models: xxx } detailing the number of models associated to each contributor.

Also linked to https://github.com/geneontology/minerva/issues/230

**Comment by goodb** [comment]
The existing search api does a UNION on repeated contributor and group parameters.  e.g.
/search/?contributor=http%3A%2F%2Forcid.org%2F0000-0002-1706-4196&contributor=http%3A%2F%2Forcid.org%2F0000-0003-1813-6857&contributor=http%3A%2F%2Forcid.org%2F0000-0002-8688-6599

retrieves all model metadata, including contributors, for any of the models contributed by one of those three orcids.

So.. the requested information is there now to be had by parsing that response.  

Is such client-side parsing problematic?

**Comment by tmushayahama** [comment]
@lpalbou maybe you can reword this in simple form. And disregards comment if this is not helpful @goodb  I believe it is a completely new api route/endpoint i.e. GET api/contributors 

## Endpoint

**api/contributors**

- Default I am not sure

## Parameters

| Parameter                          | Format             | Comments                                                                                           |
| ---------------------------------- | ------------------ | -------------------------------------------------------------------------------------------------- |
| **contributors**         | list\<contributor> | A list of one or more contributors from barista list                               |

## Return

A list of **Contributor<orcid, model_count>** and each item has


| Parameter              | Format             | Comments                                              |
| ---------------------- | ------------------ | ----------------------------------------------------- |
| **orcid**           | string                | A contributor's orcid                                            |
| **model count**      | number         | Number of that contributor models        |

**Comment by goodb** [comment]
@lpalbou yup, could you clarify a bit here?

**Comment by lpalbou** [comment]
Sorry for the long delay; it didn't helped to be out for a month.

**Context**: the left panel of the Noctua landing page allows to browse by contributors. Before, @tmushayahama used to send its own queries to get the number of models for each contributor but we want those numbers to be provided by the API.

So yes, this is a new route, taking as parameter a set of orcids and returning a list of same size with the total number of models for each of the orcid provided.

**Example**:
Input: orcid1, orcid2, .. orcidx
output: { orcid1 : nb_models_1 ; orcid2 : nb_models_2; ... orcidx: nb_models_x }

**Comment by vanaukenk** [comment]
@tmushayahama - do you know if this metadata is now provided by the API?
If the work is done here, please go ahead and close the ticket.  Thx.
