### ISSUE TITLE
Task 2 - API - Documentation

### ISSUE THREAD

**Issue by lpalbou** [geneontology/minerva#298]
Ticket to keep track on ongoing efforts on documentation.

Minerva API documentation is here: https://github.com/geneontology/minerva/wiki/Minerva-Model-Search-API

**To discuss**:
* It would be nice to have a more general documentation of the API, also including the /contributors & /groups (barista side) as well as /species (minerva). Since all queries are passing through barista, I propose the documentation of the API to be created & maintained there.
* It seems most (if not all ?) those routes are accessible to the public without token. Once Noctua is stable enough in production with the noctua landing page, I think it would be great to communicate officially on it from the go website.

**Comment by kltm** [comment]
@lpalbou For the first point, barista or it's environs will likely be the landing spot for a lot of documentation as there is no public (or even developer) access to minerva on a properly setup system.
Barista is part of the editorial system and editorial systems are not to be made available to the general public. Any data of interest to the public will be made available through the pipeline products and deployments.

**Comment by goodb** [comment]
@kltm @lpalbou I don't want to be responsible for documenting barista. 

Lets keep in mind the point of this.  It is to allow UI developers (namely @tmushayahama ) to make effective use of the services.  As of now, there is no plan that I am aware of to open things up further than that, so as long as @tmushayahama can do his work, we have doc mvp.  

I do think that it would be better to have one place for all the documentation that he and any future UI developers need.  I don't really like the idea of service documentation 'living within standard libraries'.  I think that steepens the learning curve (though the concept is nice if those libraries are evolving quickly and if the doc is auto-generated).  Consolidation of hand-written documentation in either Minerva or Barista or Noctua or whatever repo would be a good thing.  (At this point I could also see the value consolidating all of those code repos, but that is another discussion.). Wherever the central developer doc goes, I would of course be happy to contribute to it for the services that I develop.

**Comment by lpalbou** [comment]
@kltm I will close this ticket as I don't think we'll go any further on that, but it will be nice at some point to consolidate those documentations.
