### ISSUE TITLE
Change wire data structure so that inferred type information is held within the individual

### ISSUE THREAD

**Issue by kltm** [geneontology/minerva#3]
Currently, the data portion of the response looks like:

```json
{
       "individuals-i": [
            {
                "id": "123",
                "type": []
            }
        ],
        "individuals": [
            {
                "id": "123",
                "type": []
            }
        ]
}
```

The preferred format would be:

```json
{
        "individuals": [
            {
                "id": "123",
                "type": [],
                "inferred-type": []
            }
        ]
}
```

Eliminating the "individuals-i" top-level completely.

**Comment by cmungall** [comment]
Sounds good. Let's remember to update the documentation

**Comment by hdietze** [comment]
Seems to work in preliminary tests. Waiting for @kltm  to confirm and close the ticket.

**Comment by kltm** [comment]
Looking good here now--thanks!

**Comment by hdietze** [comment]
Quick optimization to minimize the JSON: If there are no inferences listed, assume that the asserted types are also the inferred types. 
*Side remark:* if the model is inconsistent, there will be no valid inferences.
