### ISSUE TITLE
Model with activity enabled_by compound

### ISSUE THREAD

**Issue by lpalbou** [geneontology/minerva#302]
<img width="1680" alt="Screen Shot 2020-03-30 at 10 55 54 AM" src="https://user-images.githubusercontent.com/24249870/77945401-72bdc180-7275-11ea-844d-830317dde51c.png">

In this model, @tmushayahama was able to create a model with a compound as an enabler of an activity (see Kanamycin A on the right).

- [ ] autocomplete should not allow for the selection of a compound (not using CHEBI molecular_entity) as an enabler but probably only biomacromolecule (CHEBI_33694) @cmungall ?
- [ ] would shex currently catch that mistake or do we have to update the schema ? (@goodb ?)

**Comment by ukemi** [comment]
If you run the reasoner the little red error box appears in the upper left showing a Shex failure. If you click on the box you get an unfriendly but accurate description of why it failed.

**Comment by ukemi** [comment]
I should probably also point out that this works on development.

**Comment by lpalbou** [comment]
Thanks for the feedback, two comments:
* The autocomplete probably should still not allows curators to enter compound as enabler
* I don't think we have a SHEX validator on noctua form ? (@tmushayahama). I thought that each time the model is updated, noctua form was receiving a response with possible errors to highlight in the UI ?

**Comment by tmushayahama** [comment]
@lpalbou 

That is the same closure on shex and there is no validation on noctua form 
![image](https://user-images.githubusercontent.com/2273929/77950484-6a698480-727d-11ea-9b35-e8f89122a229.png)

**Comment by vanaukenk** [comment]
@tmushayahama 
We should restrict the 'Gene Product' field to only allow for an InformationBiomacromolecule (CHEBI:33695) OR a ProteinContainingComplex (GO:0033291)

**Comment by tmushayahama** [comment]
@vanaukenk thanks, so I will put also OR protein containing complex. 

@lpalbou @goodb double check to align with shex, Golr will be 
...
fq: document_category:"ontology_class"
fq: isa_closure:"CHEBI:33695" OR isa_closure:"GO:0032991"
q: keyword
...

Thanks @thomaspd for the catch

**Comment by lpalbou** [comment]
@tmushayahama as I understand, you are doing GOLr queries on the fly to fill your autocomplete ?  It seems you were using a closure of CHEBI_23367 (molecular_entity), so indeed changing it to CHEBI_33695 would do the trick and with a OR:
```
fq=isa_closure:("CHEBI:33695" "GO:0032991")
```

This issue is related to the ticket on autocomplete: https://github.com/geneontology/minerva/issues/236 . I would suggest autocomplete to become a priority for the next cycle after May as we need to have something more unified across UIs and SHEX.

**Comment by vanaukenk** [comment]
@lpalbou 

We are working towards aligning the autocompletes on the form with the ShEx.  

See, for example:
https://github.com/geneontology/noctua-form/issues/66

It is definitely on our radar, although with the caveat that the ShEx has still been under discussion a bit on the GO-CAM specs calls.

Thx.

**Comment by vanaukenk** [comment]
Tested on noctua-dev and appears to be working as expected.
