### ISSUE TITLE
question about GPAD generation with field values

### ISSUE THREAD

**Issue by krchristie** [geneontology/minerva#315]
The MGI GO group has a question about the generation of GPAD files from Noctua. We'd like to know if the process of generating a GPAD file excludes any information that was present in the Noctua model. Specifically, we were talking about the with field and whether the with field of an IMP annotation is a faithful reflection of what the curator entered in the Noctua model, whether the value is something like "MGI:MGI:12343567", "MGI:1234567", or null.

@balhoff - From an email exchange with @kltm, he thinks you are likely the person to answer this question. If not, please tag or assign to the appropriate person.

Thanks!

**Comment by balhoff** [comment]
Hi @krchristie GPAD export will always be lossy relative to everything that can be expressed in a Noctua model. The 'with' value field is exported exactly as it was entered, whenever the evidence it's used with is included in a GPAD line. 

See this model: http://noctua.geneontology.org/editor/graph/gomodel:5df932e000000958

And the annotation preview here: http://noctua.geneontology.org/workbench/annpreview/?model_id=gomodel:5df932e000000958

**Comment by krchristie** [comment]
> Hi @krchristie GPAD export will always be lossy relative to everything that can be expressed in a Noctua model. 

This isn't really what I was concerned about. I don't have a problem with the extra stuff from a model not being exported to GPAD.

> The 'with' value field is exported exactly as it was entered, whenever the evidence it's used with is included in a GPAD line.

Will the curator get a warning if they have put a value into the 'with' field but have forgotten or missed the fact that there is no evidence used in the appropriate place for the 'with' field to be exported into the GPAD?

If not, I think that is a significant problem. It's really not practical to have to go look at the annotation preview for every model I make to confirm that I haven't made any mistakes.

**Comment by balhoff** [comment]
@krchristie maybe we can find a time to talk about this during the GOC meeting next week, because I think an interface to check that the with field is appearing would pretty much just look like the annotation preview. I may just be lacking imagination here.

**Comment by krchristie** [comment]
@balhoff - An interface to manually check that the with field is appearing is exactly the annotation preview. [As an aside regarding the annotation preview, I'd like some additional stuff there, including sorting, filtering, and exporting. I find it tedious to check annotation previews for large models.]

However, what I want is to NOT have to MANUALLY check the annotation preview for mistakes like a missing with field that didn't export due to lack of evidence. This could be very time consuming to check if I have entered a lot of annotations, especially if I have a mix of annotations that do and do not contain with information. If I have entered a with field, then I think it should be apparent that I want it, so if there is no evidence on it such that it will not export to GPAD, that should obviously be an error. I'd like some sort of alert to tell me to fix this, without having to manually check through the entire annotation preview.

I'll be happy to find a time to talk during the GOC meeting to discuss this.

**Comment by vanaukenk** [comment]
@krchristie @balhoff 
I would like to join you whenever you find time to discuss this issue.  
Thx.

**Comment by ukemi** [comment]
Me too.

**Comment by vanaukenk** [comment]
I'm going to close this ticket for now, as I think it relates more to implementing real-time error checking into Noctua than to the actual GPAD output code.

That said, I will also open a new ticket in the minerva repo to itemize and track GPAD output checking for https://github.com/orgs/geneontology/projects/52
