### ISSUE TITLE
Add model title to ShEx validation report

### ISSUE THREAD

**Issue by dustine32** [geneontology/minerva#318]
Hey @goodb ,

Is it reasonable to add the model title to the ShEx report created with option `-r 'report-file'` ?
```
filename        model_id        OWL_consistent  shex_valid      validation_time_milliseconds    axioms  model_title
null    http://model.geneontology.org/b0bff868-74c1-414c-b4ea-b0da5b29e4ce      true    true    1527    25      MGI:MGI:1891751
null    http://model.geneontology.org/e6c5c81c-2adf-4280-b95e-3f16f6c0d214      true    true    922     45      MGI:MGI:1860303
null    http://model.geneontology.org/3d5219f4-4287-4563-895c-8787564f76db      true    true    811     25      MGI:MGI:88519
null    http://model.geneontology.org/9986105e-9440-45d7-a243-fb362c044774      true    true    394     7       MGI:MGI:103169
```

**Comment by goodb** [comment]
Yes perfectly reasonable.  good ticket.

**Comment by dustine32** [comment]
@goodb I seem to not be getting the title out in the reports.

I see the `model_title` header so it looks like I have your new code and have built it. This occurs for testing models in a blazegraph journal file (`-i /tmp/blazegraph-models.jnl`, created from an N-quads file w/ blazegraph-runner) as well as `.ttl` files directly (`-i models_ttl_dir/`). I've confirmed that the models have the `title` annotation `http://purl.org/dc/elements/1.1/title` but maybe something's still up with my models that would break this?

Basic cmd for .ttl directory
```
bin$ ./minerva-cli.sh --validate-go-cams --shex 
-i /Users/ebertdu/go/gocamgen/one_off_shex/ 
-r /Users/ebertdu/go/gocamgen/shex_test_20200609.tsv 
-e /Users/ebertdu/go/gocamgen/shape_explanation_test_20200609.txt 
--pipeline-output-file /Users/ebertdu/go/gocamgen/minerva-shex-report_test_20200609.json 
--ontojournal /tmp/blazegraph-lego.jnl
```
The `-r` report looks like:
```
filename        model_title     model_id        OWL_consistent  shex_valid      validation_time_milliseconds    axioms
MGI_MGI_1336880.ttl     http://model.geneontology.org/c1ecccb3-a487-4aba-b418-62640cdb8199      true    true    3459    27
```

If you'd like I can send you some small example model files (`.jnl` and `.ttl`) for testing. Also, FYI I'm running this locally with Java 11. Maybe it's environmental.

**Comment by goodb** [comment]
@dustine32 please send a .ttl file
