### ISSUE TITLE
noctua_sgd.gpad has a space in the PMID field, typo in PMID field

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/minerva#319]
Sorry to be the bearer of bad news, but we have strange things in our GPAD just obtained from http://release.geneontology.org/2020-05-02/products/annotations/noctua_sgd.gpad.gz

There are several cases of spaces in the "PMID: 0000000" field (expect PMID:0000) and an errant PMD: prefix elsewhere.  Seems these should trigger some checks somewhere:
> SGD	S000003464	enables	GO:0044183	**PMID: 19412159**	ECO:0000314			20200429	SGD		model-state=production|noctua-model-id=gomodel:5e72450500002948|contributor=http://orcid.org/0000-0001-5472-917X

> SGD	S000001905	acts_upstream_of_or_within	GO:0043335	**PMID: 32320318**	ECO:0000315			20200428	SGD		noctua-model-id=gomodel:5e72450500002870|model-state=production|contributor=http://orcid.org/0000-0001-5472-917X

Also fun is 
> SGD	S000003214	part_of	GO:0010494	**PMD**:26359986	ECO:0000314			20200127	SGD		contributor=http://orcid.org/0000-0001-9799-5523|model-state=production|noctua-model-id=gomodel:5df932e000001486

**Comment by kltm** [comment]
There are two steps here then. The first would be to fix the (likely) typos in the original annotations (I'm guessing copy/paste errors). The second would be to make sure that minerva is validating IDs at least to the extent of making sure spaces are not present.

**Comment by suzialeksander** [comment]
I've gone through and manually fixed the spaces/typos.  But I suspect this will still be an issue im the future as more curators copy/paste into Noctua, as PubMed (and other sources) provide the "PMID: 11111" format, space included.

**Comment by ukemi** [comment]
It happens all the time for ontology developers too. One check that I always do when using the graph editor is to look at the evidence statement once I've made the annotation. The title appears. This helps not only for the space case above but also when you miss a digit on the end or just make a typo if you are entering the PMID by hand. The title will be from a completely unrelated paper.
