### ISSUE TITLE
Annotations from Noctua models not reaching Xenbase GPAD on snapshot.

### ISSUE THREAD

**Issue by malcolmfisher103** [geneontology/minerva#328]
In the time between June 14th and June 22nd nearly 300 annotations have disappeared from the Xenbase GPAD file (http://snapshot.geneontology.org/products/annotations/noctua_xenbase.gpad.gz). The missing annotations can still be found in the latest release version (http://release.geneontology.org/2020-06-01/products/annotations/noctua_xenbase.gpad.gz). Please find attached a file with the annotations that have been lost ([Missing.lines.txt](https://github.com/geneontology/noctua-models/files/4838529/Missing.lines.txt)).

 Some of these may be the result of legitimate changes in models but in many cases entire models are no longer represented. I can still go to the models in Noctua and see the annotations in the 'Workbenches' menu's 'Annotation preview' or 'Export GPAD' option from the 'Model' menu, see [this model](http://noctua.berkeleybop.org/editor/graph/gomodel:581e072c00000295?model_id=gomodel:581e072c00000295) for an example.

Have any extra  QC checks been added in the last couple of weeks that might account for this? I am not seeing any obvious problem or commonalities with the models that have been lost.

**Comment by goodb** [comment]
@malcolmfisher103 one quick clarification.  When you say
" I can still go to the models in Noctua and see the annotations in the 'Workbenches' menu's 'Annotation preview' or 'Export GPAD' option from the 'Model' menu, see this model for an example"

When you use the export to GPAD option or annotation preview right now, are those the GPAD lines that you expect to see?   If those are correct, then the difference is some kind of downstream filter in the pipeline.  If not, then something is happening with the minerva GPAD generating service.  We haven't actively changed Minerva GPAD generation, but lots of other things (e.g. ontology changes) could impact it.

**Comment by malcolmfisher103** [comment]
Yes, the lines are what I would expect, and what was in the older release version of the GPAD.

**Comment by hdrabkin** [comment]
Also posted in #335 Alka-Selzer moment
I discovered today that between 6/17 and 6/18, we lost over 50% of our Noctua annotations:
6/17 NOCTUA Annotations:
Total Number of Genes Annotated to: 1027
Total Number of Annotations: 6716

6/18 NOCTUA Annotations:
Total Number of Genes Annotated to: 551 <<<<<<<<<< 476 loss
Total Number of Annotations: 3111 <<<<<<<<<< 3605 loss

**Comment by malcolmfisher103** [comment]
The new code release from around the 21st seems to have fixed this issue. We have recovered the lost Xenbase Noctua based annotations in the snapshot gpad file.
