### ISSUE TITLE
Filter 'do not annotate' terms from GPAD export

### ISSUE THREAD

**Issue by balhoff** [geneontology/minerva#332]
See https://github.com/geneontology/go-annotation/issues/2827#issuecomment-591035944

**Comment by vanaukenk** [comment]
@balhoff @ukemi 

Are inferred annotations stored, and hence, available for querying from the Noctua landing page, or are they only generated on the fly using the reasoner?

I was just wondering if I could use the Noctua landing page to find any WB production models that have inferred annotations to 'molecular function regulator' but it doesn't look like I can do this.

**Comment by balhoff** [comment]
Not in Noctua, but it may be possible to do a query against the triplestore for this.

**Comment by vanaukenk** [comment]
Okay, thanks @balhoff

**Comment by balhoff** [comment]
@vanaukenk try taking a look at these models: https://api.triplydb.com/s/uqrgWCUQS

**Comment by vanaukenk** [comment]
Closing this ticket as we've decided to keep the 'do not annotate' terms and instead flag them as warnings in accordance with [go-rule-8](https://github.com/geneontology/go-site/blob/master/metadata/rules/gorule-0000008.md)

See #417 for update
