### ISSUE TITLE
Search API: add ability to search my model id

### ISSUE THREAD

**Issue by tmushayahama** [geneontology/minerva#333]
From landing page https://github.com/geneontology/noctua-landing-page/issues/24

Add ability to the search api to search models by model id

https://github.com/geneontology/minerva/issues/230

tag @goodb

**Comment by goodb** [comment]
Okay @tmushayahama I believe this is working now on noctua-dev - e.g. http://noctua-dev.berkeleybop.org:6800/search/models/?id=gomodel:5b91dbd100000826 

Note that it currently only supports one id at a time.  We can make it a multi-valued search if you want, just let me know.  Please close the issue if you are happy with it.

**Comment by tmushayahama** [comment]
@goodb  thank you.
Is it possible for it to accept a list of ids (just like any other params) example http://noctua-dev.berkeleybop.org:6800/search/models/?id=gomodel:5b91dbd100000826&id=gomodel%3A5ef3cfb000000012 should return 2 models

**Comment by goodb** [comment]
@tmushayahama hey your link works now :) http://noctua-dev.berkeleybop.org:6800/search/models/?id=gomodel:5b91dbd100000826&id=gomodel%3A5ef3cfb000000012

**Comment by tmushayahama** [comment]
@goodb ohhh yesss thanks so much, it just integrated well with its siblings of filters :)

![image](https://user-images.githubusercontent.com/2273929/88120413-ae0f3380-cb77-11ea-97fe-65bec25fe546.png)
