### ISSUE TITLE
root types missing for complex portal entity

### ISSUE THREAD

**Issue by goodb** [geneontology/minerva#339]
http://noctua-amigo.berkeleybop.org/amigo/term/ComplexPortal:CPX-4082

No root types reported in minerva response.  

complex is apparently missing as a type in golr. ping @kltm 

reported by @tmushayahama

**Comment by tmushayahama** [comment]
Thanks @goodb
I will also tag @vanaukenk @lpalbou @ukemi from our software call discussion for https://github.com/geneontology/noctua-form/issues/111 issue

**Comment by goodb** [comment]
@kltm I think we have a curie-URI mapping problem in neo.  Minerva seems to think that
ComplexPortal:CPX-998  means https://www.ebi.ac.uk/complexportal/complex/CPX-9
but NEO seems to think that it means 
http://purl.obolibrary.org/obo/ComplexPortal_CPX-998 

We are missing root types for these because neo and hence our ontology blazegraph verison of neo doesn't have the ebi URI.

**Comment by balhoff** [comment]
See also https://github.com/geneontology/neo/issues/17

**Comment by goodb** [comment]
Update on secondary problem discovered here.  Minerva has the ability to render partial responses as well as rendering the entire model (as json output).  Right now, it only adds root types when rendering the entire model.  If you add a single individual to a model in the graph editor you can see that the response does not contain root types.  If you then save and reload the model it will.  I'm thinking right now that it should probably add the root types in both situations.

**Comment by kltm** [comment]
@goodb 

Would this be a good time to start thinking about taking the NEO builder apart and reworking it, or just adding more complexity to something that can be approached already?

For the secondary issue (root types in partial--aka update--responses), yes that would be ideal. I think there has been some question as to how useful partial update responses are, but if we are ever in a world where we need to edit large models, we may want to come back to them.

**Comment by goodb** [comment]
@kltm I added the root types for partial model response - pr above.  
Based on the conversation on the Tuesday schema call, I would await stabilization of the GPAD/GPI spec before making big changes to the NEO builder.  

We ought to be able to cure this particular ill by fixing the namespace declaration somewhere..  The thread from @balhoff suggests there are more problems like this lurking though.

**Comment by goodb** [comment]
this is not specifically a minerva kind of a problem.  Fix neo synchronization issues and this goes away.
