### ISSUE TITLE
Model-level annotations missing in some cases (title)

### ISSUE THREAD

**Issue by kltm** [geneontology/minerva#344]
It looks like not all model-level annotations are returned in some cases.

For example, currently, http://noctua.geneontology.org/editor/graph/gomodel:5ee8120100002602 returns no `title` annotation for "get" "model", even though it is found in the model in GH and in the display generated from the Minerva search API. It seems like most other models do not have this issue.

The cases that we found were on noctua.geneontology.org (previous `master` code). It's unknown if this occurs elsewhere, but we are looking. (I'd also note a nodding similarity to https://github.com/geneontology/minerva/pull/341, but may be entirely unrelated.)

@goodb @vanaukenk

**Comment by goodb** [comment]
@kltm are you running this with the most recent master - post PR from last week?  I was having problems with titles not showing up as well, but the upgrade to the OWL-API version appeared to resolve them.

**Comment by goodb** [comment]
(meaning prior to that update, I was specifically having problems seeing the titles when running minerva command line validation.   In my case, the update fixed the problem.)  My issues consolidated around models that imported go-lego-reacto.owl - by and large all the recently created or edited models.

**Comment by kltm** [comment]
@goodb No, we are still using the last bit of `master` code. We can try and update and see if that sorts it out. Should I rebuild the journal as well, or would that not matter (just quicker to do without, but no biggie)

@vanaukenk We can do this when you're ready. Let's pick a time and I can cycle the production server with the latest code. An announcement can be a notice of the hiccup plus when we will do the fix (and as a warning to save before then).

**Comment by goodb** [comment]
Rebuilding the journal will not matter.  Yes, please try with new code.  I think it will cure this ailment.

**Comment by vanaukenk** [comment]
Thanks @kltm and @goodb 

How about we cycle the production server sometime after 4pm EDT today?
Once we have a set time, I can send out an announcement.

**Comment by vanaukenk** [comment]
Note to Noctua curators:
If your model title is currently not displaying properly in the graph or form editors, please add a new title and re-save your model.

**Comment by goodb** [comment]
@vanaukenk I don't think that is really a good idea.  If the bug is what I think it is, the titles are there, just not showing up.  Adding a new title will have the effect of creating multiple titles and render the models incorrect with respect to the schema.  Better to just wait for the reset.

**Comment by ukemi** [comment]
I might have done this already by accident, so you can test it. I thought that I had forgotten to add one.
http://noctua.geneontology.org/editor/graph/gomodel:5ee8120100003329

**Comment by vanaukenk** [comment]
Okay @goodb 

I think what is happening, though, is that curators are working on some models and then when they try to save, they can't because there isn't a title.
Should we instead just tell curators not to use Noctua until we fix this bug?

**Comment by lpalbou** [comment]
@kltm popping up an idea: in that kind of situation, it could be nice to have a simple function that save all pending changes (flush in memory -> blazegraph) before turning off minerva. Then we wouldn't need to ask curators to save their models on short notice and it wouldn't matter if they can not save because of a temporary data flow issue (eg library not returning fields)
