### ISSUE TITLE
Minerva Search API to provide modified-p tag

### ISSUE THREAD

**Issue by lpalbou** [geneontology/minerva#348]
Currently, the bbop library returns a modified_p tag that indicates if there are any pending changes to a model that have not yet been saved (in memory != stored). When searching for models through the Minerva API, also return the same tag field for each model retrieved.

**Use case**: when activating the review mode, the tag will be used to indicate to users if there are any pending changes to a model. In ART, it will be used to check if a model can be bulk edit or if it has to be saved first.

**Comment by kltm** [comment]
I would assume that this should follow the same pattern as the metadata return (that we used for the previous interface):

`"modified-p": false`

```json
{
   "id":"gomodel:5b91dbd100002057",
   "date":"2019-01-04",
   "title":"C. elegans PMK pathway for defense response in the hypodermis",
   "state":"development",
   "contributors":["http://orcid.org/0000-0002-3013-9906"],
   "groups":["http://www.wormbase.org"],
   "query_match":{}
}
```

**Comment by goodb** [comment]
Do you care if its 'modified' versus 'modified-p' ?  I have it working with the search results looking like this:

```
{
  "n": 2,
  "models": [
    {
      "id": "gomodel:R-HSA-997272",
      "date": "2020-10-28",
      "title": "Reactome:unexpanded:Inhibition of voltage gated Ca2+ channels via Gbeta/gamma subunits",
      "state": "development",
      "contributors": [
        "http://orcid.org/0000-0002-7334-7852",
        "https://reactome.org/content/detail/R-HSA-997272"
      ],
      "groups": [
        "https://reactome.org",
        "http://geneontology.org"
      ],
      "query_match": {
        "http://purl.obolibrary.org/obo/GO_0015467": [
          "http://model.geneontology.org/R-HSA-1013020"
        ]
      },
      "modified": false
    },
    {
      "id": "gomodel:R-HSA-1296041",
      "date": "2020-10-22",
      "title": "Reactome:unexpanded:Activation of G protein gated Potassium channels",
      "state": "development",
      "contributors": [
        "https://reactome.org/content/detail/R-HSA-1296041"
      ],
      "groups": [
        "https://reactome.org"
      ],
      "query_match": {
        "http://purl.obolibrary.org/obo/GO_0015467": [
          "http://model.geneontology.org/R-HSA-1013020"
        ]
      },
      "modified": false
    }
  ],
  "sparql": "add \u0027debug\u0027 parameter to see sparql request"
}
```

**Comment by kltm** [comment]
@goodb Apologies for the old-style predicate marking, but ` "modified-p": false,` is already appearing in results for model-level responses, so I think it would be good it keep it consistent if possible.

**Comment by goodb** [comment]
k.  done.  `"modified-p":false`
