### ISSUE TITLE
Model in store vs memory: inferred section and equals

### ISSUE THREAD

**Issue by lpalbou** [geneontology/minerva#366]
Hi @balhoff , we were looking at models in store (left) vs in memory (right):

![Screen Shot 2021-01-06 at 10 44 08 AM](https://user-images.githubusercontent.com/24249870/103808116-51f87880-500c-11eb-852c-92c49bfba570.png)

@tmushayahama was worried, but I think the highlighted difference is normal as the "inferred" part is certainly not stored and is probably only added to the in memory representation once the reasoner runs that model. @balhoff can you confirm ?

The other question I have related to that, is on the .equals method : model1.equals(model2)
It seems, because of that difference (presence/absence of inferred section), the equals would not state the models are the same. Is it the behavior we want ? do we want to surcharge the equals() method and add a equals(testWithInference) ? Not critical at the moment, but to get your opinion.

**Comment by balhoff** [comment]
>  I think the highlighted difference is normal as the "inferred" part is certainly not stored and is probably only added to the in memory representation once the reasoner runs that model.

Correct.

**Comment by lpalbou** [comment]
Discussed today, normal behavior, closing this ticket. Thanks @balhoff

**Comment by tmushayahama** [comment]
I think to take the confusion away, in case this happens and needed in the future, maybe 2 different equals are needed. deepEqual, vs shallow equal. Or modelEqualWithoutReasoning etc or just a documentation @balhoff @lpalbou

**Comment by lpalbou** [comment]
The model.equals(model) was doing exactly what it was supposed to be. Technically a model + inferences is not the same model and it we want to compare just the models, then removing the inferred part of it is easy. Let’s see in the future if we have another use for it, otherwise I think we are good.
