### ISSUE TITLE
Landing Page and ART search issue

### ISSUE THREAD

**Issue by lpalbou** [geneontology/minerva#370]
During this morning call, we were looking for a GO-term in ART. We noticed the number of results was 128 but ART was showing only 2 results. Same behavior on the noctua landing page (**see update below**).

~~After checking the API calls:~~
* ~~Query 1: http://barista-dev.berkeleybop.org/search//models?offset=0&limit=50&term=GO:0036498&expand&count~~
* ~~Query 2: http://barista-dev.berkeleybop.org/search//models?offset=0&limit=150&term=GO:0036498&expand~~

~~It appears the API is indeed returning (at least) 128 models. In effect, the second query seems to indicate even more (around 150) but possibly there was some redundancy in the various matches and this hopefully goes down to 128. Possibly NLP and ART are only using one of the models field, but not all ?~~

## Action items (see update below)
- [ ] ~~make sure both ART and NLP are using the full list of models from the API query 2 (e.g. models[0].query_match, ... models[x].query_match etc)~~
- [ ] ~~double check the full concatenated list of matching models, and once duplicates are removed, hopefully confirm that we do have 128 models; if we don't, this would indicate a bug at the API level~~
- [ ] ~~@vanaukenk @ukemi confirm this is working on this case (GO:0036498) on both NLP and ART; try to double check on some other random search~~

**Comment by tmushayahama** [comment]
After the merge, now the results are not sorted by date DESC. I think now its hard to find models for recent @balhoff @lpalbou
