### ISSUE TITLE
Search API query_match not giving matches if multiple matches in one model

### ISSUE THREAD

**Issue by tmushayahama** [geneontology/minerva#375]
From https://github.com/geneontology/minerva/pull/374

found a bug where the query_match is no longer matching multiple occurrence in one model (it only matches the first). For example lets say one model has 3 "lipid transport" if a search by term is made, it gives result of query_match of 1 instead of 3. 

n (number of models) is correct but query_match (number of matches is not correct
http://localhost:3400/search/models?offset=0&limit=50&term=GO:0036498&expand&debug

**it is now showing only one match like** 
![image](https://user-images.githubusercontent.com/2273929/111541985-6359b180-872e-11eb-95f1-4f016a1f792d.png)

**Instead of multiple query matches**
![image](https://user-images.githubusercontent.com/2273929/111541861-37d6c700-872e-11eb-93b6-f3233a127990.png)

@balhoff @lpalbou @vanaukenk @ukemi

**Comment by vanaukenk** [comment]
@tmushayahama 

I'm closing this one, as I think this is working as expected in ART.

Please reopen if there's anything more to do.
