### ISSUE TITLE
add is_active_in and located_in

### ISSUE THREAD

**Issue by sierra-moxon** [geneontology/minerva#385]
http://noctua-dev.berkeleybop.org/editor/graph/gomodel:ZFIN_ZDB-GENE-990415-160 is not pushed out in the noctua-gpad file.

@dustine32 discovered two relations that need to be added in the SPARQL query in gpad-basic.rq: 'located_in', 'is_active_in'.
He also noticed we need to add the two relations to the PREFIX section at the top.
PREFIX located_in: <http://purl.obolibrary.org/obo/RO_0001025>
PREFIX is_active_in: <http://purl.obolibrary.org/obo/RO_0002432>

**Comment by balhoff** [comment]
Somewhat related: #179
