### ISSUE TITLE
Taxon ID without label

### ISSUE THREAD

**Issue by tmushayahama** [geneontology/minerva#388]
In production there is one taxon without a label, specifically **NCBITaxon:2697049** Selecting it results in 5 models, mostly Patrick's  SARS models as shown below.

![image](https://user-images.githubusercontent.com/2273929/120734501-d822c900-c49d-11eb-96ac-273f1c45f4c9.png)

tagging @balhoff @vanaukenk @lpalbou @ukemi @dustine32 @kltm 

For more information, it comes from search api for taxa, http://barista.berkeleybop.org/search/taxa

**Comment by cmungall** [comment]
I suspect go-lego.owl only includes taxslim which was created before SARS-CoV-2 existed. We should update taxslim, but more broadly, what are the implications of including all of ncbitaxon on go-lego?

**Comment by balhoff** [comment]
We will need to test its impact on Arachne.

**Comment by vanaukenk** [comment]
See also:  https://github.com/geneontology/noctua-landing-page/issues/30

**Comment by cmungall** [comment]
this seems like a dupe. I think we should close this one as there is more info on the other ticket
