### ISSUE TITLE
QC checking for Noctua GPAD outputs for gene-centric models

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/minerva#389]
This ticket is to itemize the things we want to check in the Noctua GPAD output of the gene-centric MOD import GO-CAMs.

**Please note:**

Some of the items listed below will, if necessary, be linked to additional tickets when specific actions are required to correct errors.

Likewise, the granularity of the checklist below should increase as we add even more specific checks.

- [ ] Check annotated entity ids

- [ ] Check negation

- [ ] Check gp2term relations
        - https://github.com/geneontology/minerva/issues/390
        
- [ ] Check GO ids

- [ ] Check references

- [ ] Check evidence

- [ ] Check with/from

- [ ] Check interacting taxon

- [ ] Check date

- [ ] Check assigned by

- [ ] Check annotation extensions

- [ ] Check annotation properties

**Comment by ukemi** [comment]
For reference:
https://github.com/geneontology/pipeline/issues/237
https://github.com/geneontology/pipeline/issues/238

**Comment by ukemi** [comment]
QC checks for MGI mid-late June are here: https://drive.google.com/drive/folders/1-_UtaNNdXZcBGcSGNaWHo43LvNyGOKPk

**Comment by ukemi** [comment]
@vanaukenk do you want to leave this ticket open? Should I move it to the new GPAD project?

**Comment by ukemi** [comment]
Closing this one for now. We may revisit this as other MODS progress further.
