### ISSUE TITLE
We shouldn't output both part_of and is_active_in annotations in the GPAD from models

### ISSUE THREAD

**Issue by ukemi** [geneontology/minerva#390]
The GPAD being generated from models is outputting both part_of and is_active_in annotations when an MF occurs in a CC. This creates confusion for downstream resources who filter duplicates. If they consider these annotations to be duplicates, then we filter out one of the statements, but if we don't consider them to be duplicates and don't display the whole set of new qualifiers, they look like duplicate annotations. We should solve this at the reasoner level by either inferring one statement or the other. If a gene product enables a function that occurs in a CC, then it is active in the cc. Is it a part of that CC or is it located in that CC? We should think about the current structure of the ontology as we consider this.

**Comment by balhoff** [comment]
The part_of inference comes from a SWRL rule in RO, which we added pretty much for supporting GPAD output, prior to changing to is_active_in.

**Comment by vanaukenk** [comment]
@ukemi @balhoff 

Do we just need to delete that SWRL rule, then?

A separate, but perhaps related, issue would be to check existing production GO-CAMs to make sure we don't have cases where an MF 'occurs in' a protein-containing complex (or child term).

**Comment by ukemi** [comment]
I suspect that for the latter, there will be lots of this kind of clean-up.

**Comment by vanaukenk** [comment]
Note, however, that we still need to either delete the SWRL rule from RO that is also generating the 'part of' inference or filter the redundant 'part of' CC annotations from the GPAD output.

**Comment by balhoff** [comment]
SWRL rule will be deleted by this PR: https://github.com/oborel/obo-relations/pull/468

**Comment by vanaukenk** [comment]
This work is completed.
