### ISSUE TITLE
Update all 'directly' regulates relations to just 'regulates' relations

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/minerva#392]
For existing GO-CAM models we want to update any 'directly' regulates relations (and positive/negative children) to just use 'regulates' relations (and positive/negative children).

Note that we'll also want to check for use of 'directly activates' and 'directly inhibits'.

See also:  https://github.com/geneontology/go-shapes/issues/255

**Comment by lpalbou** [comment]
There are currently 23 GO-CAMs on the production servers using directly regulates & children:
```
http://model.geneontology.org/60ad85f700001873
http://model.geneontology.org/60ad85f700000309
http://model.geneontology.org/5835403200000017
http://model.geneontology.org/57c82fad00000695
http://model.geneontology.org/57c82fad00000403
http://model.geneontology.org/5745387b00001254
http://model.geneontology.org/5716c41300000389
http://model.geneontology.org/5716c41300000277
http://model.geneontology.org/60ad85f700000259
http://model.geneontology.org/60ad85f700000189
http://model.geneontology.org/60ad85f700000110
http://model.geneontology.org/6086f4f200000223
http://model.geneontology.org/5e72450500000000
http://model.geneontology.org/5df932e000002650
http://model.geneontology.org/5d29221b00001995
http://model.geneontology.org/5c4605cc00004193
http://model.geneontology.org/5b91dbd100002241
http://model.geneontology.org/5b91dbd100002057
http://model.geneontology.org/5b528b1100000489
http://model.geneontology.org/5b318d0900000302
http://model.geneontology.org/5ae3b0f600001579
http://model.geneontology.org/5ae3b0f600001522
http://model.geneontology.org/568b0f9600000284
```

For models on the dev server, it's quite a different story with currently 858 models using those relations, including reactome models:
```
http://model.geneontology.org/a1a2a3a402
http://model.geneontology.org/a1a2a3a401
http://model.geneontology.org/56d1143000003364
http://model.geneontology.org/8b595d9e-fc3c-4598-82b5-35c067c4226f
http://model.geneontology.org/5b318d0900000689
http://model.geneontology.org/R-HSA-977225
http://model.geneontology.org/R-HSA-975957
http://model.geneontology.org/R-HSA-975871
http://model.geneontology.org/R-HSA-975163
http://model.geneontology.org/R-HSA-975155
http://model.geneontology.org/R-HSA-975144
http://model.geneontology.org/R-HSA-975110
http://model.geneontology.org/R-HSA-9668328
http://model.geneontology.org/R-HSA-9664873
http://model.geneontology.org/R-HSA-9648895
http://model.geneontology.org/R-HSA-9645460
http://model.geneontology.org/R-HSA-9639288
http://model.geneontology.org/R-HSA-9634638
http://model.geneontology.org/R-HSA-9634635
http://model.geneontology.org/R-HSA-9633012
http://model.geneontology.org/R-HSA-9022692
http://model.geneontology.org/R-HSA-9020558
http://model.geneontology.org/R-HSA-9018519
...
```

For reference, SPARQL query: https://api.triplydb.com/s/GfM68R29y

**Comment by vanaukenk** [comment]
Thank you @lpalbou !
I'll start taking a closer look at the models on production Noctua.

**Comment by vanaukenk** [comment]
@lpalbou 
Thanks for sharing the SPARQL query above.
If I also wanted to know which models with 'development' status use these relations, can I alter the query above, or do we need to query a different data source? Or something else?
I'm particularly interested in the 'development' status models on production Noctua, but we should also know about Noctua-dev, too, if possible.

**Comment by vanaukenk** [comment]
### Production Models on Production Noctua 
                                                                
http://model.geneontology.org/60ad85f700001873	EGFR signaling pathway, D.mel. Alliance Model						
http://model.geneontology.org/60ad85f700000309	Notch Signaling, D.mel. Alliance Model								
http://model.geneontology.org/5835403200000017	mouse-Ncapg2-transcription									
http://model.geneontology.org/57c82fad00000695	F13a1 and F13b-mouse-blood clotting								
http://model.geneontology.org/57c82fad00000403	Lhx1-mouse-epiblast											
http://model.geneontology.org/5745387b00001254	Mouse-Pds5a-mutation														
http://model.geneontology.org/5716c41300000389	Human-CXCL17-Macrophage chemotaxis							
http://model.geneontology.org/5716c41300000277	Mouse-Cxcl17-macrophage chemotaxis								
http://model.geneontology.org/60ad85f700000259	Activin Signaling (Actbeta), D.mel. Alliance Model						
http://model.geneontology.org/60ad85f700000189	BMP Signaling (dpp), D.mel. Alliance Model							
http://model.geneontology.org/60ad85f700000110	JAK-STAT, D.mel. Alliance Model									
http://model.geneontology.org/6086f4f200000223	Canonical Wnt Signaling Pathway Model, D.mel wg-fz2, Alliance Model		
http://model.geneontology.org/5e72450500000000	ZDB-PUB-190219-8 sas10 and mpp10								
http://model.geneontology.org/5df932e000002650	ZDB-PUB-181017-10 - Mga modulates BMP by antigonizing Bs69			
http://model.geneontology.org/5d29221b00001995	Gm34220 PMID:26658965										
http://model.geneontology.org/5c4605cc00004193	ZDB-PUB-180805-1											
http://model.geneontology.org/5b91dbd100002241	DBL-1 pathway in C. elegans epidermis in response to fungal infection		
http://model.geneontology.org/5b91dbd100002057	C. elegans PMK pathway for defense response in the hypodermis			
http://model.geneontology.org/5b528b1100000489	XBP-1 is a Cell-Nonautonomous regulator of Stress Resistance and Longevity	
http://model.geneontology.org/5b318d0900000302	Mouse IRE1-mediated unfolded protein response						
http://model.geneontology.org/5ae3b0f600001579	ZDB-PUB-070601-1											
http://model.geneontology.org/5ae3b0f600001522	ZDB-PUB-161204-10											
http://model.geneontology.org/568b0f9600000284	C. elegans antibacterial innate immune response in the intestine### ###

**Comment by lpalbou** [comment]
Even if that's a little confusing, note we have two types of dev:
- prod & dev servers
- on each of them, prod & dev models

This query https://api.triplydb.com/s/u9bAgCP2D would for instance also show the state (prod or dev model) as well as the title.

To get that information from the prod server, you have to target: http://rdf.geneontology.org/blazegraph/sparql
And to get that information from the dev server, you have to target: http://rdf-internal.berkeleybop.io/blazegraph/sparql

It's unfortunately poorly documented, but at least now it's written somewhere (hopefully) clearly.

PS: the same applies for https://github.com/geneontology/minerva/issues/391

**Comment by vanaukenk** [comment]
Okay, I think I've got it.
I can now see the full list of models that use the 'directly regulates' or child relations.
Some of the 'development' status models are definitely active works in progress, others as you said are Reactome models, while still others could probably be deleted.
We'll need to discuss more widely the implications of this change for the Reactome models; I'm less concerned about the manually constructed models, although we'll want to be very transparent about what will happen and why.
@ukemi @dustine32

**Comment by vanaukenk** [comment]
We also need to talk about using the RO subset tags to populate relations in Noctua.  Curators find, and use, too many relations not in the GO-CAM specs.

**Comment by vanaukenk** [comment]
Note: we will also need to remove these relations from the Noctua graph editor relations drop down (maybe we can only remove them from the top of the list right now?) so curators don't use them once we've updated the existing data.  In the future, we should make use of RO subsets for GO-CAM relations.

**Comment by vanaukenk** [comment]
- [ ] Add replace_relations.tsv to https://github.com/geneontology/noctua-models/tree/master/migrations
- [ ] Test relations update on noctua-dev with diff, if possible
- [ ] Remove 'directly regulates', 'directly positively regulates' and 'directly negatively regulates' from the top of the graph editor relations pop-up on noctua-dev and noctua
- [ ] Update relations on production noctua during 2022-05-12 outage

**Comment by vanaukenk** [comment]
@thomaspd @tmushayahama @ukemi @cmungall  

On the Alliance Pathway views, we distinguish between direct and indirect regulation by the type of line between nodes.  If we switch over to just using 'regulates' relations we should only have one type of line and change the Alliance display accordingly.  

I just want to double-check that this is the desired outcome wrt Alliance Pathway views.

Here's an example of a model we currently display where solid lines denote direct regulation and dashed lines indirect regulation:

![image](https://user-images.githubusercontent.com/1730534/167499295-a517de38-e88b-4cd0-9e41-5c038591fd2d.png)

**Comment by vanaukenk** [comment]
[Most recent list ](https://docs.google.com/spreadsheets/d/1fJJHMzwJ6kGMQB0MKC9-pmG6PUCjIJx0zeKKQQOtEwo)(from 2022-05-25) of GO-CAMs that use 'directly regulates' and 'regulates' relations.

**Comment by vanaukenk** [comment]
After discussions about causal MF relations and a new proposal, this change is no longer needed.
