### ISSUE TITLE
Suppress UBERON annotation extensions when an EMAPA structure is present

### ISSUE THREAD

**Issue by ukemi** [geneontology/minerva#395]
In some cases, annotations generated by models include an additional UBERON structure in annotation extensions that already have an EMAPA identifier. We need to suppress this.

Example:

MGI | MGI:2676312 | acts_upstream_of_or_within | GO:0048286 | PMID:18632686 | ECO:0000315 | MGI:MGI:3809668 |   | 20121017 | MGI | results_in_development_of(EMAPA:32692),results_in_development_of(UBERON:0000061) | noctua-model-id=gomodel:MGI_MGI_2676312\|contributor=http://orcid.org/0000-0001-5501-853X\|model-state=production

Note the results_in_development_of(UBERON:0000061). This is 'anatomical structure' and is not necessary.

**Comment by cmungall** [comment]
isn't there an issue with the inferred uberon class regardless of whether there is an EMAPA extension, in that it is uninformative?

Uberon has an antislim for excluding high level classes

**Comment by ukemi** [comment]
This might be true. Since I have been focusing on the MGI imports, the ones I looked at all have an EMAPA and then the inferred extension to the uninformative UBERON class.

**Comment by balhoff** [comment]
The reason we get this uninformative inference is that we don't bridge EMAPA to Uberon, because of logical inconsistencies. Something we could do is add a minimal bridge, to just put an upper Uberon layer above EMAPA and not get redundant domain/range inferences.

**Comment by ukemi** [comment]
Would that be the most appropriate solution though? Without being able to resolve the logical inconsistencies, It might be better to just take care of this at the level of the GPAD generation. If there is an asserted relationship using an EMAPA class, suppress any relationship to an UBERON class in the GPAD.

**Comment by ukemi** [comment]
I just tested this this morning as part of the MGI import testing on dev and it worked.

Input:
MGI:MGI:2676312 |   | RO:0002264 | GO:0048286 | MGI:MGI:3807143\|PMID:18632686 | ECO:0000315 | MGI:MGI:3809668 |   | 2012-10-17 | MGI | RO:0002296(EMAPA:32692) | creation-date=2012-10-17\|modification-date=2012-10-17\|comment=anatomy alveolar system ;  MA:0000416\|comment=cell type type II pneumocyte ; CL:0002063\|comment=has_participant(CL:0002063)\|contributor-id=https://orcid.org/0000-0001-5501-853X

Output:
MGI | MGI:2676312 | acts_upstream_of_or_within | GO:0048286 | PMID:18632686 | ECO:0000315 | MGI:MGI:3809668 |   | 20121017 | MGI | results_in_development_of(EMAPA:32692) | contributor=https://orcid.org/0000-0001-5501-853X\|noctua-model-id=gomodel:MGI_MGI_2676312\|model-state=production

@balhoff , you can go ahead and merge this into production unless @vanaukenk also wants to have a look.

**Comment by ukemi** [comment]
Still good in the latest round trip. File provided by @dustine32 last night

MGI | MGI:2676312 | acts_upstream_of_or_within | GO:0048286 | PMID:18632686 | ECO:0000315 | MGI:MGI:3809668 |   | 20121017 | MGI | results_in_development_of(EMAPA:32692) | contributor=https://orcid.org/0000-0001-5501-853X\|noctua-model-id=gomodel:MGI_MGI_2676312\|model-state=production\|creation-date=2012-10-17\|import-date=2021-08-09

@balhoff, this one is also ready to go.
