### ISSUE TITLE
Do not create root MF annotations based on root BP annotations

### ISSUE THREAD

**Issue by ukemi** [geneontology/minerva#396]
In the GPAD output, do not create root molecular function annotations from a model of a root BP annotation. 

Example:
This annotation is stated literally in the model:

MGI | MGI:2153470 | involved_in | GO:0008150 | GO_REF:0000015 | ECO:0000307 |   |   | 20011206 | MGI |   | noctua-model-id=gomodel:MGI_MGI_2153470\|contributor=http://orcid.org/0000-0001-7476-6306\|model-state=production

This annotation should not be created:

MGI | MGI:2153470 | enables | GO:0003674 | GO_REF:0000015 | ECO:0000307 |   |   | 20011206 | MGI | part_of(GO:0008150) | noctua-model-id=gomodel:MGI_MGI_2153470\|contributor=http://orcid.org/0000-0001-7476-6306\|model-state=production

**Comment by ukemi** [comment]
It looks like this one worked and can be moved into production as well. Checking imports and outputs for MGI:2153470 I see this:

Input annotations:
MGI:MGI:2153470 |   | RO:0002327 | GO:0005515 | MGI:MGI:2152614\|PMID:11682631 | ECO:0000353 | PR:Q920H1 |   | 2005-10-03 | MGI |   | creation-date=2001-12-06\|modification-date=2005-10-03\|comment=Scgb3a2\|contributor-id=https://orcid.org/0000-0003-2689-5511\|contributor-id=https://orcid.org/0000-0001-7476-6306

MGI:MGI:2153470 |   | RO:0001025 | GO:0005576 | MGI:MGI:2152614\|PMID:11682631 | ECO:0000314 |   |   | 2001-12-06 | MGI |   | creation-date=2001-12-06\|modification-date=2001-12-06\|contributor-id=https://orcid.org/0000-0001-7476-6306

MGI:MGI:2153470 |   | RO:0002331 | GO:0008150 | MGI:MGI:2156816\|GO_REF:0000015 | ECO:0000307 |   |   | 2001-12-06 | MGI |   | creation-date=2001-12-06\|modification-date=2001-12-06\|contributor-id=https://orcid.org/0000-0001-7476-6306

Output annotations:
MGI | MGI:2153470 | enables | GO:0005515 | PMID:11682631 | ECO:0000353 | PR:Q920H1 |   | 20051003 | MGI | has_input(PR:Q920H1) | contributor=https://orcid.org/0000-0001-7476-6306\|noctua-model-id=gomodel:MGI_MGI_2153470\|contributor=https://orcid.org/0000-0003-2689-5511\|model-state=production |  

MGI | MGI:2153470 | located_in | GO:0005576 | PMID:11682631 | ECO:0000314 |   |   | 20011206 | MGI |   | contributor=https://orcid.org/0000-0001-7476-6306\|noctua-model-id=gomodel:MGI_MGI_2153470\|model-state=production | 
 
MGI | MGI:2153470 | involved_in | GO:0008150 | GO_REF:0000015 | ECO:0000307 |   |   | 20011206 | MGI |   | contributor=https://orcid.org/0000-0001-7476-6306\|noctua-model-id=gomodel:MGI_MGI_2153470\|model-state=production |  

@vanaukenk , do you want to double-check for worm annotations?

**Comment by vanaukenk** [comment]
@ukemi 
WB didn't have any root BP annotations in the annotation set we uploaded this time around.
I did double-check other root node annotations that we have and they all seem fine.
Feel free to close this ticket and move to Done if you want.

**Comment by ukemi** [comment]
I think @balhoff should close once these are merged into production. Then I will move to 'done' on the project board.

**Comment by ukemi** [comment]
Actually, I take it back. It looks like we are filtering out asserted root MF annotations. Here is an example where the MF annotation is stripped when it shouldn't be:

input:
MGI:MGI:98392 |   | RO:0002327 | GO:0003674 | MGI:MGI:2156816\|GO_REF:0000015 | ECO:0000307 |   |   | 2012-06-08 | MGI |   | creation-date=2012-06-08\|modification-date=2012-06-08\|contributor-id=https://orcid.org/0000-0003-2689-5511

MGI:MGI:98392 |   | RO:0002432 | GO:0005575 | MGI:MGI:2156816\|GO_REF:0000015 | ECO:0000307 |   |   | 2012-06-08 | MGI |   | creation-date=2012-06-08\|modification-date=2012-06-08\|contributor-id=https://orcid.org/0000-0003-2689-5511

MGI:MGI:98392 |   | RO:0002331 | GO:0008150 | MGI:MGI:2156816\|GO_REF:0000015 | ECO:0000307 |   |   | 2012-06-08 | MGI |   | creation-date=2012-06-08\|modification-date=2012-06-08\|contributor-id=https://orcid.org/0000-0003-2689-5511

output:
MGI | MGI:98392 | involved_in | GO:0008150 | GO_REF:0000015 | ECO:0000307 |   |   | 20120608 | MGI |   | noctua-model-id=gomodel:MGI_MGI_98392\|contributor=https://orcid.org/0000-0003-2689-5511\|model-state=production

MGI | MGI:98392 | is_active_in | GO:0005575 | GO_REF:0000015 | ECO:0000307 |   |   | 20120608 | MGI |   | noctua-model-id=gomodel:MGI_MGI_98392\|contributor=https://orcid.org/0000-0003-2689-5511\|model-state=production

**Comment by balhoff** [comment]
@ukemi looking at that model here: http://noctua-dev.berkeleybop.org/editor/graph/gomodel:MGI_MGI_98392

Is the distinguishing feature the fact that there is a separate MF instance that is not connected to a BP? So it gets to stay?

**Comment by ukemi** [comment]
Correct.

**Comment by balhoff** [comment]
Fix for this is in `dev` branch now.

**Comment by ukemi** [comment]
@dustine32 will the pipeline run automatically to generate the new GPAD?

**Comment by dustine32** [comment]
@ukemi Nope, but I just started it now. Hopefully will be done in about 9hrs.

**Comment by ukemi** [comment]
Thanks @dustine32. I'm committed to work on a different project on Fridays, but let me know when it successfully completes and I will throw it in a new QC folder.

**Comment by ukemi** [comment]
Asserted MFs are back:

noctua_mgi output posted by: @dustine32 

MGI | MGI:98392 | involved_in | GO:0008150 | GO_REF:0000015 | ECO:0000307 |   |   | 20120608 | MGI |   | noctua-model-id=gomodel:MGI_MGI_98392\|contributor=https://orcid.org/0000-0003-2689-5511\|model-state=production\|creation-date=2012-06-08\|import-date=2021-08-09

MGI | MGI:98392 | is_active_in | GO:0005575 | GO_REF:0000015 | ECO:0000307 |   |   | 20120608 | MGI |   | noctua-model-id=gomodel:MGI_MGI_98392\|contributor=https://orcid.org/0000-0003-2689-5511\|model-state=production\|creation-date=2012-06-08\|import-date=2021-08-09

MGI | MGI:98392 | enables | GO:0003674 | GO_REF:0000015 | ECO:0000307 |   |   | 20120608 | MGI |   | noctua-model-id=gomodel:MGI_MGI_98392\|contributor=https://orcid.org/0000-0003-2689-5511\|model-state=production\|creation-date=2012-06-08\|import-date=2021-08-09


AND

The MF annotations are being suppressed correctly. From the example above here are the annotation in the new file. There is no root MF annotation based on the GO:0008150 annotation.

MGI:2153470 | enables | GO:0005515 | PMID:11682631 | ECO:0000353 | PR:Q920H1 |   | 20051003 | MGI | has_input(PR:Q920H1) | contributor=https://orcid.org/0000-0001-7476-6306\|noctua-model-id=gomodel:MGI_MGI_2153470\|creation-date=2001-12-06\|contributor=https://orcid.org/0000-0003-2689-5511\|model-state=production\|import-date=2021-08-09

MGI:2153470 | involved_in | GO:0008150 | GO_REF:0000015 | ECO:0000307 |   |   | 20011206 | MGI |   | contributor=https://orcid.org/0000-0001-7476-6306\|noctua-model-id=gomodel:MGI_MGI_2153470\|creation-date=2001-12-06\|model-state=production\|import-date=2021-08-09

MGI:2153470 | located_in | GO:0005576 | PMID:11682631 | ECO:0000314 |   |   | 20011206 | MGI |   | contributor=https://orcid.org/0000-0001-7476-6306\|noctua-model-id=gomodel:MGI_MGI_2153470\|creation-date=2001-12-06\|model-state=production\|import-date=2021-08-09

@balhoff, this one is ready to go.

**Comment by balhoff** [comment]
I made a test model on noctua-dev, and it looks like BP and CC are both output, as I would expect: http://noctua-dev.berkeleybop.org/editor/graph/gomodel:615f7bec00000027

Excluding MFs that are part of root BP was the exact request in this ticket, so we need to re-think, if some groups want them and some don't.

**Comment by balhoff** [comment]
@vanaukenk I think that should work without too much trouble.

**Comment by vanaukenk** [comment]
Thanks very much @balhoff 
We appreciate it!

**Comment by suzialeksander** [comment]
If a test model is needed, gomodel:6115be0900001245 should produce a ND MF annotation as well, currently it's just producing ND-BP & ND-CC.  AMD2 Scer = S000002650

**Comment by ukemi** [comment]
This morning I used the new file that Dustin created to check several MGI markers that have both root MF annotations and non-root BP annotations. The MF annotations are appearing in the GPAD file. @suzialeksander once you confirm that this is working for SGD, I think we can let this one move over to 'merge into production'.

**Comment by suzialeksander** [comment]
This looks like it's working (dev and prod) as far as producing an intentional MF ND, but the annotation preview is also adding the not-incorrect-but-entirely-unhelpful `part_of(biological_process),occurs_in(cellular_component)` in the annotation extension field.  I can't think of a case where an ND should have anything in the AE??

**Comment by vanaukenk** [comment]
Thanks for testing @suzialeksander 
Wrt the annotation extensions, we'd have to implement a new rule for suppressing those root annotations extensions if curators want that.  
We can discuss more on a call and open a new ticket for that, if needed.

**Comment by ukemi** [comment]
I would suggest we roll this into a bigger project about annotation extension output in general. I see lots of 'correct' but pretty much completely uninformative annotation extensions in my models. This will also impinge on the detection of duplicates discussion.

**Comment by suzialeksander** [comment]
I'm slowly catching back up after the break, what exactly should I wait for before I start checking prod for these ND MFs? Is there an update being pushed or is there still more discussion needed? 

Note to self also check gomodel:61b2b68300000293

**Comment by vanaukenk** [comment]
@suzialeksander - does everything look okay if you make an equivalent model on noctua-dev.
This fix hasn't been rolled out into production yet, so it'd be good to check dev before we do.
Thx.

**Comment by suzialeksander** [comment]
Yes, http://noctua-dev.berkeleybop.org/workbench/annpreview/?model_id=gomodel:61b9325200000056 looks like we want- three annotations including a ND

**Comment by ukemi** [comment]
Just to be sure, looking at the model above that @suzialeksander checked. The only reason the MF annotation is generated is because there are NO other MF annotations anywhere and this has an ND evidence code, correct? What if there was an annotation in another model to an MF with literature support. Would the MF annotation coming from this model be suppressed?

**Comment by balhoff** [comment]
@ukemi is that a question for me? The Minerva code only thinks about one model at a time.

**Comment by pgaudet** [comment]
I expected there would be some filtering at the generation of export files?
