### ISSUE TITLE
Inferred type decoration

### ISSUE THREAD

**Issue by kltm** [geneontology/minerva#4]
This is to bookmark a possible feature discussed with @hdietze. 
Essentially, inferred types could have an additional property that give a hint about the rational/genesis of an inferred type. This would not prevent "dupe scanning", but it would give more context for downstream consumers to figure out what to do with the information.

**Comment by kltm** [comment]
At some point, maybe on the wiki, it would be good to document some of our expectations for what is returned. Maybe we could sit down at some point and have a doc afternoon.

**Comment by cmungall** [comment]
Another way to think about this is a generLied predictions framework. Owl
reasoners give predictions with p=1 but we may want to leverage other kinds
of predictions in the future

**Comment by kltm** [comment]
Cool, yes--I'd like to keep all this supple enough that we don't have to revisit many assumptions if we want to add something like that later.

**Comment by vanaukenk** [comment]
See #437 
Curators would like unique evidence on inferred annotations and some indication of how the inference was made.
