### ISSUE TITLE
Do PomBase identifiers have root type values in minerva?

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/minerva#408]
It's possible to enter various PomBase names or identifiers into Noctua but then they don't display on the Noctua form table. because minerva doesn't have the information about the root type of PomBase entities.  The values/ids are there.

This is related to https://github.com/geneontology/noctua-form/issues/122

Perhaps the neo journal loaded into minerva is not up-to-date?

@kltm @balhoff - can you take a look/advice?

Discussed with @tmushayahama on a workbenches call

**Comment by kltm** [comment]
@balhoff minerva production is running as: ```--arachne -g http://skyhook.berkeleybop.org/go-lego-reacto.owl --set-important-relation-parent http://purl.obolibrary.org/obo/LEGOREL_0000000```

The operative thing being: http://skyhook.berkeleybop.org/go-lego-reacto.owl. This is the same as noctua-dev.

**Comment by kltm** [comment]
Also see possibly quite relevant PomBase GPI issue: https://github.com/geneontology/noctua/issues/727#issuecomment-908775024

**Comment by balhoff** [comment]
@kltm isn't there more to the command line? Like `--ontojournal`, etc.?

**Comment by kltm** [comment]
Of course--and a lot of other stuff--but I trimmed out anything local or not related.

**Comment by balhoff** [comment]
Okay. `http://skyhook.berkeleybop.org/go-lego-reacto.owl` doesn't have genes; we need NEO for that. But anyway maybe the GPI change will fix the issue.

**Comment by kltm** [comment]
Pausing temporarily while we sort: https://github.com/geneontology/noctua/issues/727#issuecomment-909694414 .
When done, I'd like to bounce noctua-dev to see if the issue gets cleared on a complete rebuild of the datastores on the server.

**Comment by vanaukenk** [comment]
This looks to be fixed on production.  See:  http://noctua.geneontology.org/workbench/noctua-form/?model_id=gomodel%3A60ff660000001748
