### ISSUE TITLE
Some PRO annotations are missing from the GPAD

### ISSUE THREAD

**Issue by ukemi** [geneontology/minerva#410]
During our check for the import/output process @LiNiMGI noticed that there we annotations missing from the output file when a PRO identifier was used as the primary object. For example:

In our input file that @dustine32 used, there are these annotations:

PR:Q8BIF2-1 |   | RO:0002264 | GO:0000381 | MGI:MGI:5140633\|PMID:21747913 | ECO:0000314 |   |   | 2012-04-30 | MGI |   | creation-date=2012-04-30\|modification-date=2012-04-30\|comment=all three isoforms\|contributor-id=https://orcid.org/0000-0003-2689-5511

PR:Q9DA08-1 |   | BFO:0000050 | GO:0005671 | MGI:MGI:4462751\|PMID:20508642 | ECO:0000314 |   |   | 2021-07-29 | MGI |   | creation-date=2012-06-11\|modification-date=2021-07-29\|contributor-id=https://orcid.org/0000-0003-2689-5511\|contributor-id=https://orcid.org/0000-0002-9796-7693

These appear to be loaded correctly by the loader:
http://noctua-dev.berkeleybop.org/editor/graph/gomodel:MGI_MGI_106368
http://noctua-dev.berkeleybop.org/editor/graph/gomodel:MGI_MGI_1922815

And these entries are in our GPI file (just in case the GPAD generator uses it):
PR:Q8BIF2-1	mRBFOX3/iso:1	RNA binding protein fox-1 homolog 3 isoform 1 (mouse)	mRBFOX3/iso:1|Fox-3-L (mouse)|Fox3v1 (mouse)	PR:000000001	NCBITaxon:10090	MGI:MGI:106368			UniProtKB:Q8BIF2-1	

PR:Q9DA08-1	mSGF29/iso:1	SAGA-associated factor 29 isoform 1 (mouse)	mSGF29/iso:1	PR:000000001	NCBITaxon:10090	MGI:MGI:1922815			UniProtKB:Q9DA08-1

**Comment by ukemi** [comment]
Now looking at this and wondering if it is bacause the GO terms were recently obsoleted or merged. Looks like the latter annotation was recently changed to GO:0140672.

**Comment by ukemi** [comment]
Scratch that idea. It might explain some but not all.

**Comment by balhoff** [comment]
Some explanations:
- http://noctua-dev.berkeleybop.org/editor/graph/gomodel:MGI_MGI_106368 model is inconsistent
- http://noctua-dev.berkeleybop.org/editor/graph/gomodel:MGI_MGI_1922815 obsolete GO term seems to be filtering the annotation later in the pipeline

**Comment by ukemi** [comment]
A few more:
PR:Q8CCH7-1 |   | RO:0002327 | GO:0008134 | MGI:MGI:3711633\|PMID:17445768 | ECO:0000353 | PR:Q08369 |   | 2009-04-10 | MGI |   | creation-date=2008-01-24\|modification-date=2009-04-10\|comment=EMBL:ABP96991 Fog2s\|contributor-id=https://orcid.org/0000-0003-2689-5511

PR:Q8CGN4-2 |   | RO:0002327 | GO:0005515 | MGI:MGI:2682643\|PMID:12776190 | ECO:0000353 | PR:A2AM29 |   | 2011-12-07 | MGI |   | creation-date=2011-12-07\|modification-date=2011-12-07\|comment=ECO:0000068; inferred from yeast 2-hybrid assay\|comment=isoform a and b fF(-1 and 12)   but not c and d (-3  -4)\|contributor-id=https://orcid.org/0000-0003-2689-5511

PR:000037287 |   | RO:0002327 | GO:0043565 | MGI:MGI:4867351\|PMID:21084637 | ECO:0000314 |   |   | 2014-01-17 | MGI |   | creation-date=2014-01-17\|modification-date=2014-01-17\|comment=evidence in vitro binding assay ; ECO:0000148\|comment=sumolyated version of PR:000037285; binds "P3" DNA domain\|contributor-id=https://orcid.org/0000-0003-2689-5511

**Comment by ukemi** [comment]
Zfpm2    MGI:1334444
Bcor   MGI:1918708 
Pax6 MGI:97490

**Comment by balhoff** [comment]
@ukemi [transcription factor binding](http://purl.obolibrary.org/obo/GO_0008134) is in the 'do not annotate' subset. The GPAD export filters these out (not sure why I didn't remember this yesterday). That's the explanation for the Zfpm2 issues, at least.

**Comment by ukemi** [comment]
Here is a list of PRO IDs that are in the import file that are not in the output file. Hopefully they will all come back:
PR:000037287
PR:000044810
PR:P63015-1
PR:Q61043-3
PR:Q61043-4
PR:Q8BIF2-1
PR:Q8BIF2-4
PR:Q8BIF2-5
PR:Q8CCH7-1
PR:Q8CCJ4
PR:Q99KW3-1
PR:Q9DA08-1
PR:Q9EPR2-2

**Comment by ukemi** [comment]
It looks like some of these are still going missing in the file. Below I have listed the input annotations and the model where they are imported. I will add more, but need to do other things for the next little while.

PR:000037287 |   | RO:0002327 | GO:0043565 | MGI:MGI:4867351\|PMID:21084637 | ECO:0000314 |   |   | 2014-01-17 | MGI |   | creation-date=2014-01-17\|modification-date=2014-01-17\|comment=evidence in vitro binding assay ; ECO:0000148\|comment=sumolyated version of PR:000037285; binds "P3" DNA domain\|contributor-id=https://orcid.org/0000-0003-2689-5511
------- Imported (gomodel:MGI_MGI_97490), but could be a 'do not annotate' term. I thought this was fixed?-----------

PR:000044810 |   | RO:0001025 | GO:0005622 | MGI:MGI:3823138\|PMID:18996085 | ECO:0000314 |   |   | 2015-04-13 | MGI | BFO:0000050(CL:0000023) | creation-date=2015-04-13\|modification-date=2015-04-13\|contributor-id=https://orcid.org/0000-0001-5501-853X
------- Imported (gomodel:MGI_MGI_1353427), but could be a 'do not annotate' term. I thought this was fixed?-----------

PR:P63015-1 |   | RO:0002264 | GO:0045944 | MGI:MGI:4867351\|PMID:21084637 | ECO:0000314 |   |   | 2014-01-22 | MGI | RO:0002233(MGI:MGI:88516) | creation-date=2014-01-22\|modification-date=2014-01-22\|comment=p43  the sumolyated version of p32; assayed on alpha/beta crystalin promoter\|contributor-id=https://orcid.org/0000-0003-2689-5511
------- Imported (gomodel:MGI_MGI_97490)  [GO:0045944] positive regulation of transcription by RNA polymerase II-----------

**Comment by ukemi** [comment]
PR:Q61043-3 |   | RO:0001025 | GO:0005813 | MGI:MGI:5805714\|PMID:27565344 | ECO:0000314 |   |   | 2020-02-26 | MGI |   | creation-date=2020-02-26\|modification-date=2020-02-26\|contributor-id=https://orcid.org/0000-0001-5501-853X
PR:Q61043-3 |   | RO:0002264 | GO:0007052 | MGI:MGI:5805714\|PMID:27565344 | ECO:0000315 |   |   | 2020-02-26 | MGI | BFO:0000066(GO:0005634) | creation-date=2020-02-26\|modification-date=2020-02-26\|contributor-id=https://orcid.org/0000-0001-5501-853X
PR:Q61043-4 |   | RO:0001025 | GO:0005829 | MGI:MGI:5805714\|PMID:27565344 | ECO:0000314 |   |   | 2020-02-26 | MGI | BFO:0000050(CL:0000540)
PR:Q61043-4 |   | RO:0002264 | GO:0045666 | MGI:MGI:5805714\|PMID:27565344 | ECO:0001273 |   |   | 2020-02-26 | MGI | BFO:0000066(EMAPA:16894)
PR:Q61043-4 |   | RO:0002264 | GO:1904780 | MGI:MGI:5805714\|PMID:27565344 | ECO:0001273 |   |   | 2020-02-26 | MGI | BFO:0000066(EMAPA:16894),RO:0002233(PR:Q61043-3)\|BFO:0000066(EMAPA:16894),RO:0002233(UniProtKB:O08788)
------- Imported (gomodel:MGI_MGI_105108) model inconsistent will fix on MGI side--------

PR:Q8BIF2-1 |   | RO:0002264 | GO:0000381 | MGI:MGI:5140633\|PMID:21747913 | ECO:0000314 |   |   | 2012-04-30 | MGI |   | creation-date=2012-04-30\|modification-date=2012-04-30\|comment=all three isoforms\|contributor-id=https://orcid.org/0000-0003-2689-5511
PR:Q8BIF2-1 |   | RO:0002327 | GO:0005515 | MGI:MGI:5050057\|PMID:21177649 | ECO:0000353 | PR:Q8VIJ6 |   | 2014-06-13 | MGI |   | creation-date=2014-06-13\|modification-date=2014-06-13\|contributor-id=https://orcid.org/0000-0003-2689-5511
PR:Q8BIF2-1 |   | RO:0001025 | GO:0005634 | MGI:MGI:5140633\|PMID:21747913 | ECO:0000314 |   |   | 2012-04-30 | MGI |   | creation-date=2012-04-30\|modification-date=2012-04-30\|comment=predominantly nuclear  but not exclusively\|contributor-id=https://orcid.org/0000-0003-2689-5511
PR:Q8BIF2-4 |   | RO:0002264 | GO:0000381 | MGI:MGI:5140633\|PMID:21747913 | ECO:0000314 |   |   | 2012-05-01 | MGI |   | creation-date=2012-05-01\|modification-date=2012-05-01\|comment=all three isoforms\|contributor-id=https://orcid.org/0000-0003-2689-5511
PR:Q8BIF2-4 |   | RO:0001025 | GO:0005737 | MGI:MGI:5140633\|PMID:21747913 | ECO:0000314 |   |   | 2012-04-30 | MGI |   | creation-date=2012-04-30\|modification-date=2012-04-30\|comment=predominantly cytoplasmic but not exclusively\|contributor-id=https://orcid.org/0000-0003-2689-5511
PR:Q8BIF2-5 |   | RO:0002264 | GO:0000381 | MGI:MGI:5140633\|PMID:21747913 | ECO:0000314 |   |   | 2012-05-01 | MGI |   | creation-date=2012-05-01\|modification-date=2012-05-01\|comment=all three isoforms\|contributor-id=https://orcid.org/0000-0003-2689-5511
PR:Q8BIF2-5 |   | RO:0002327 | GO:0005515 | MGI:MGI:5050057\|PMID:21177649 | ECO:0000353 | PR:Q8VIJ6 |   | 2014-06-13 | MGI |   | creation-date=2014-06-13\|modification-date=2014-06-13\|contributor-id=https://orcid.org/0000-0003-2689-5511
PR:Q8BIF2-5 |   | RO:0001025 | GO:0005634 | MGI:MGI:5140633\|PMID:21747913 | ECO:0000314 |   |   | 2012-04-30 | MGI |   | creation-date=2012-04-30\|modification-date=2012-04-30\|comment=this isoform is exclusively nuclear\|contributor-id=https://orcid.org/0000-0003-2689-5511
PR:Q8BIF2-5 | NOT | RO:0001025 | GO:0005737 | MGI:MGI:5140633\|PMID:21747913 | ECO:0000314 |   |   | 2012-04-30 | MGI |   | creation-date=2012-04-30\|modification-date=2012-04-30\|comment=this isoform is exclusively nuclear\|contributor-id=https://orcid.org/0000-0003-2689-5511
------- Imported (gomodel:MGI_MGI_106368) model inconsistent will fix on MGI side--------

PR:Q8CCH7-1 |   | RO:0002327 | GO:0008134 | MGI:MGI:3711633\|PMID:17445768 | ECO:0000353 | PR:Q08369 |   | 2009-04-10 | MGI |   | creation-date=2008-01-24\|modification-date=2009-04-10\|comment=EMBL:ABP96991 Fog2s\|contributor-id=https://orcid.org/0000-0003-2689-5511
-------Imported (gomodel:MGI_MGI_1334444)- [GO:0008134] transcription factor binding- 'do not annotate set'?-------

PR:Q8CCJ4 |   | RO:0002327 | GO:0005515 | MGI:MGI:3609918\|PMID:11591653 | ECO:0000353 | PR:Q9D828 |   | 2008-08-28 | MGI |   | creation-date=2006-02-01\|modification-date=2008-08-28\|contributor-id=https://orcid.org/0000-0003-2689-5511\|contributor-id=https://orcid.org/0000-0003-3394-9805
-------Imported (gomodel:MGI_MGI_1919375) don't know why this one failed-------

PR:Q99KW3-1 |   | RO:0002264 | GO:0009790 | MGI:MGI:4881391\|PMID:20510926 | ECO:0000315 |   |   | 2017-12-20 | MGI |   | creation-date=2017-12-20\|modification-date=2017-12-20\|contributor-id=https://orcid.org/0000-0002-9796-7693
PR:Q99KW3-1 |   | RO:0001025 | GO:0032420 | MGI:MGI:4881391\|PMID:20510926 | ECO:0000314 |   |   | 2017-12-20 | MGI | BFO:0000050(CL:0000202) | creation-date=2017-12-20\|modification-date=2017-12-20\|contributor-id=https://orcid.org/0000-0002-9796-7693
PR:Q99KW3-1 |   | RO:0001025 | GO:0120044 | MGI:MGI:4881391\|PMID:20510926 | ECO:0000314 |   |   | 2017-12-20 | MGI | BFO:0000050(CL:0000202) | creation-date=2017-12-20\|modification-date=2017-12-20\|contributor-id=https://orcid.org/0000-0002-9796-7693
-------Imported (gomodel:MGI_MGI_1349410)- don't know why these failed-------

PR:Q9DA08-1 |   | BFO:0000050 | GO:0005671 | MGI:MGI:4462751\|PMID:20508642 | ECO:0000314 |   |   | 2021-07-29 | MGI |   | creation-date=2012-06-11\|modification-date=2021-07-29\|contributor-id=https://orcid.org/0000-0003-2689-5511\|contributor-id=https://orcid.org/0000-0002-9796-7693
-------Imported (Sgf29 (MGI:MGI:1922815)- annotation to obsolete term-------

PR:Q9EPR2-2 |   | RO:0001025 | GO:0005622 | MGI:MGI:2683415\|PMID:11278438 | ECO:0000314 |   |   | 2011-04-20 | MGI |   | creation-date=2004-01-22\|modification-date=2011-04-20\|contributor-id=https://orcid.org/0000-0003-2689-5511\|contributor-id=https://orcid.org/0000-0001-7476-6306
-------Imported (gomodel:MGI_MGI_1913600 )- intracellular anatomical structure- do not annotate?-------

**Comment by ukemi** [comment]
I will fix the inconsistent models. @balhoff, can you help with these?

PR:000044810 |   | RO:0001025 | GO:0005622 | MGI:MGI:3823138\|PMID:18996085 | ECO:0000314 |   |   | 2015-04-13 | MGI | BFO:0000050(CL:0000023) | creation-date=2015-04-13\|modification-date=2015-04-13\|contributor-id=https://orcid.org/0000-0001-5501-853X
------- Imported (gomodel:MGI_MGI_1353427), but could be a 'do not annotate' term. I thought this was fixed?-----------

PR:Q8CCH7-1 |   | RO:0002327 | GO:0008134 | MGI:MGI:3711633|PMID:17445768 | ECO:0000353 | PR:Q08369 |   | 2009-04-10 | MGI |   | creation-date=2008-01-24|modification-date=2009-04-10|comment=EMBL:ABP96991 Fog2s|contributor-id=https://orcid.org/0000-0003-2689-5511
-------Imported (gomodel:MGI_MGI_1334444)- [GO:0008134] transcription factor binding- 'do not annotate set'?-------

PR:Q8CCJ4 |   | RO:0002327 | GO:0005515 | MGI:MGI:3609918|PMID:11591653 | ECO:0000353 | PR:Q9D828 |   | 2008-08-28 | MGI |   | creation-date=2006-02-01|modification-date=2008-08-28|contributor-id=https://orcid.org/0000-0003-2689-5511\|contributor-id=https://orcid.org/0000-0003-3394-9805
-------Imported (gomodel:MGI_MGI_1919375) don't know why this one failed-------

PR:Q99KW3-1 |   | RO:0002264 | GO:0009790 | MGI:MGI:4881391|PMID:20510926 | ECO:0000315 |   |   | 2017-12-20 | MGI |   | creation-date=2017-12-20|modification-date=2017-12-20|contributor-id=https://orcid.org/0000-0002-9796-7693
PR:Q99KW3-1 |   | RO:0001025 | GO:0032420 | MGI:MGI:4881391|PMID:20510926 | ECO:0000314 |   |   | 2017-12-20 | MGI | BFO:0000050(CL:0000202) | creation-date=2017-12-20|modification-date=2017-12-20|contributor-id=https://orcid.org/0000-0002-9796-7693
PR:Q99KW3-1 |   | RO:0001025 | GO:0120044 | MGI:MGI:4881391|PMID:20510926 | ECO:0000314 |   |   | 2017-12-20 | MGI | BFO:0000050(CL:0000202) | creation-date=2017-12-20|modification-date=2017-12-20|contributor-id=https://orcid.org/0000-0002-9796-7693
-------Imported (gomodel:MGI_MGI_1349410)- don't know why these failed-------

PR:Q9EPR2-2 |   | RO:0001025 | GO:0005622 | MGI:MGI:2683415|PMID:11278438 | ECO:0000314 |   |   | 2011-04-20 | MGI |   | creation-date=2004-01-22|modification-date=2011-04-20|contributor-id=https://orcid.org/0000-0003-2689-5511\|contributor-id=https://orcid.org/0000-0001-7476-6306
-------Imported (gomodel:MGI_MGI_1913600 )- intracellular anatomical structure- do not annotate?-------

**Comment by balhoff** [comment]
Closing; see #412 for issue with filtering do-not-annotate.
