### ISSUE TITLE
Creation dates are missing from GPAD outputs

### ISSUE THREAD

**Issue by ukemi** [geneontology/minerva#411]
The inputs for import look like this:
MGI:MGI:1922815 |   | BFO:0000050 | GO:0140672 | MGI:MGI:4462728\|PMID:20562830 | ECO:0000314 |   |   | 2021-07-29 | MGI |   | creation-date=2012-09-17\|modification-date=2021-07-29\|contributor-id=https://orcid.org/0000-0002-9796-7693\|contributor-id=https://orcid.org/0000-0001-7476-6306

Note the 'creation-date=2012-09-17' property

The imported model has this annotation:
dc:created: 2012-09-17

The output GPAD looks like this:
MGI | MGI:1922815 | part_of | GO:0140672 | PMID:20562830 | ECO:0000314 |   |   | 20210729 | MGI |   | contributor=https://orcid.org/0000-0001-7476-6306\|noctua-model-id=gomodel:MGI_MGI_1922815\|model-state=production\|contributor=https://orcid.org/0000-0002-9796-7693

Note that the creation date property is missing.

**Comment by ukemi** [comment]
ping @linimgi

**Comment by vanaukenk** [comment]
@ukemi - is this different from #397  ?

**Comment by ukemi** [comment]
oops. duplicate
