### ISSUE TITLE
Annotation missing from the MGI GPAD

### ISSUE THREAD

**Issue by ukemi** [geneontology/minerva#412]
This is in our input file, but I can't see it in the exported GPAD:
MGI:MGI:101776 |   | RO:0001025 | GO:0005622 | MGI:MGI:1344237\|PMID:10482234 | ECO:0000314 |   |   | 2009-06-22 | MGI | BFO:0000050(CL:0000100) | creation-date=2009-06-22\|modification-date=2009-06-22\|comment=cell type primary cell line cell ; CL:0000001   motor neuron ; CL:0000100\|comment=evidence inferred from immunofluorescence ; ECO:0000007\|contributor-id=https://orcid.org/0000-0003-3394-9805

It is imported correctly in this model:
http://noctua-dev.berkeleybop.org/editor/graph/gomodel:MGI_MGI_101776

**Comment by balhoff** [comment]
[intracellular anatomical structure](http://purl.obolibrary.org/obo/GO_0005622) is in the 'do not annotate' subset, and is filtered out by the GPAD export.

**Comment by ukemi** [comment]
I'm not sure I am happy with this. This used to only be a warning, but the annotations were still allowed. When did it become a hard and fast rule?  @pgaudet?

**Comment by balhoff** [comment]
It's been this way in the Minerva GPAD export for a very long time (don't remember the discussion from that time). Easy to remove if not wanted.

**Comment by pgaudet** [comment]
These are not a hard check in the 'normal' rules. I do have a problem with the various implementations of the rules, I am not sure where that came from. It would be awesome if the rules could be harmonized and the go-site/rules be the 'source of truth' 

Thanks, Pascale

**Comment by pgaudet** [comment]
PS: @balhoff please remove the check on export


However can something be done in the UI to avoid that these annotations are made in the first place? 

Thanks, Pascale

**Comment by balhoff** [comment]
Someone must have asked for it in 2018: https://github.com/geneontology/minerva/issues/180

**Comment by pgaudet** [comment]
fair enough ! ;)

**Comment by vanaukenk** [comment]
`However can something be done in the UI to avoid that these annotations are made in the first place?`

I think the answer is for newly generated annotations, 'yes' but the annotations that resulted in this ticket are coming in from a whole genome import.

@ukemi @tmushayahama - Let's discuss options on today's workbenches call.

**Comment by ukemi** [comment]
Thinking about this over the weekend, I now wonder if this was requested because these annotations were being inferred from more complicated GO-CAM models. This is something we need to check. If so, this is once again part of the difficult case of being between two worlds. If it is the case, there are a few paths forward:

1.  Just allow all annotations to the 'uninformative' terms. Do they hurt things?
2. Ban all these annotations, which means that groups like MGI (~2400) will lose lots of annotations. 
3. Figure out a way to keep these annotations from the imports, but not generate new ones from bona-fide GO_CAM models.
4. Something outside of the box?

**Comment by balhoff** [comment]
I made the change and merged into `dev`: #418 This will appear on noctua-dev next time @kltm updates.

**Comment by ukemi** [comment]
In the new file, these annotations are appearing:

MGI | MGI:101776 | located_in | GO:0005622 | PMID:10482234 | ECO:0000314 |   |   | 20090622 | MGI | part_of(CL:0000100) | creation-date=2009-06-22\|model-state=production\|noctua-model-id=gomodel:MGI_MGI_101776\|contributor=https://orcid.org/0000-0003-3394-9805\|import-date=2021-08-09

@balhoff looks like this one is ready to go too.

**Comment by balhoff** [comment]
Core issue covered by #417.
