### ISSUE TITLE
Add 'existence starts and ends during' to allowed annotation extension relations

### ISSUE THREAD

**Issue by balhoff** [geneontology/minerva#413]
See https://github.com/geneontology/noctua/issues/740.

**Comment by ukemi** [comment]
We are also missing some 'overlaps' AEs. But shouldn't we have a global look at the enxtensions to create a list of ones we really want to see? Sorry if I sound a bit like a broken record.

**Comment by balhoff** [comment]
> But shouldn't we have a global look at the enxtensions to create a list of ones we really want to see? 

Agree. Do you want to hold off on this one, or just put it in and plan to do that as well?

**Comment by balhoff** [comment]
Oops this is a dupe of #406.
