### ISSUE TITLE
Do not filter out GPAD annotations for 'do not annotate' violations

### ISSUE THREAD

**Issue by balhoff** [geneontology/minerva#417]
See https://github.com/geneontology/minerva/issues/412#issuecomment-916926970.

**Comment by vanaukenk** [comment]
I believe this is working as expected looking at this model:  http://noctua.geneontology.org/editor/graph/gomodel:ZFIN_ZDB-GENE-070117-2369

We can re-open or create a new ticket, if needed.

**Comment by vanaukenk** [comment]
Model checked on dev:  http://noctua-dev.berkeleybop.org/workbench/annpreview/?model_id=gomodel:MGI_MGI_88047

Annotation to 'embryo development' shown in GPAD output.
