### ISSUE TITLE
Update minerva search api for handling date information

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/minerva#419]
Hi,

Before each Noctua maintenance shutdown, I check the Noctua admin site for any unsaved models (I do it on the admin site since it's easy to sort by save status).

In doing so, though, I uncovered a discrepancy between the last modified date shown on the Noctua landing page vs the Noctua form and graph editors for one of the models.

On the Noctua landing page, the date last modified was 2021-07-26:

![image](https://user-images.githubusercontent.com/1730534/133106887-7c14523b-6c10-43bb-a9fc-c3ed4a3e918a.png)

While on the various Noctua annotation interfaces, the date last modified was 2021-09-02:

![image](https://user-images.githubusercontent.com/1730534/133107099-6cf46bfb-c9bd-4340-bc48-3c43e759e667.png)

We discussed this on Friday's workbenches call and @tmushayahama suggested that we need to check the minerva search api to make sure that it is accessing the date correctly, especially since we recently updated the ShEx so that date = modification_date.

![image](https://user-images.githubusercontent.com/1730534/133107452-d6583f69-084d-44a3-a58f-e0f246a930ff.png)

@balhoff @kltm - please let us know if you need more info

Thx.

**Comment by balhoff** [comment]
@vanaukenk it could be a discrepancy between when the model was last saved vs. the last changes in memory. I think the date from the search API would indicate when the model was last saved to disk.

**Comment by vanaukenk** [comment]
Thanks @balhoff 
So, the date on the landing page is the date the model was last saved to disk, while the dates on the other Noctua UIs are the last modification dates stored in memory?
Does that also mean that the modifications made to the two models on 2021-09-02 hadn't made their way to disk on 2021-09-09 when I checked model status prior to the maintenance shutdown?

**Comment by balhoff** [comment]
I might need to discuss with Seth or Tremayne, but that may be right. Noctua knows if there are unsaved changes. Is that what the red X means in your screenshot?

**Comment by vanaukenk** [comment]
Yes, on the Noctua landing page, the red X means that the model has unsaved changes.

Thx.

**Comment by vanaukenk** [comment]
I'm closing this ticket for now - not sure if there's anything actionable to do here.  We can reopen if needed.
