### ISSUE TITLE
Define merge operation in minervaJSON specification

### ISSUE THREAD

**Issue by cmungall** [geneontology/minerva#42]
A non-Noctua use case in merging models, e.g. for analysis or visualization.

A naive OWL-level merge will render all model-level annotations at the top level. This is not a massive issue for analysis applications that will ignore these anyway. But it would be useful to retain knowledge of which model each node and edge belonged to.

An alternate way to conceive of a merge is as a collection of models (akin to imports in OWL). The data model would then be:

```
models : [
  model1,
  ...
]
```

Where model_N would the current mJSON spec.

Alternatively, we may prefer to merge, but have the merge operation add additional axiom annotations. This may be easiest for retaining 1:1 between OWL and JSON

**Comment by kltm** [comment]
This should probably be thought about in the light of geneontology/noctua#112.

Another approach would be to simply decorate nodes and edges with metadata and let the client deal (easy enough to sort into different graphs before render, for example).

As well, would need coordination with https://github.com/berkeleybop/bbop-response-barista.
