### ISSUE TITLE
Remove the noctua GPAD file has_participant annotation extensions

### ISSUE THREAD

**Issue by ukemi** [geneontology/minerva#425]
I thought that the decision had been made that the has_participant relation would not be used for annotation. I have relagated all the ones made manually by MGI curators to a comment in the imports, but I see them being emitted from GO-CAM models in the GPAD.

MGI	MGI:2685011	involved_in	GO:0003183	PMID:26258302	ECO:0000315	MGI:MGI:4867020		20160729	MGI	has_participant(UBERON:0007151)	contributor=https://orcid.org/0000-0001-7476-6306|model-state=production|noctua-model-id=gomodel:56aac7ad00000038

**Comment by pgaudet** [comment]
This may be where the annotations using 'has_participant' we see in P2GO are coming from?

**Comment by ukemi** [comment]
Assigning to you @balhoff. Please reassign if this isn't appropriate.

**Comment by ukemi** [comment]
These are not in the MGI GPAD output that Dustin recently made for MGI.

**Comment by ukemi** [comment]
@balhoff can you confirm this was done and can you close this ticket? I don't see any has_participant extensions in the MGI file on snapshot.

**Comment by balhoff** [comment]
Done.
