### ISSUE TITLE
Add Root Types for WBls:0000075 ZFS:0100000

### ISSUE THREAD

**Issue by tmushayahama** [geneontology/minerva#428]
@balhoff @vanaukenk Addition of 2 new relationships according to this issue https://github.com/geneontology/noctua-form/issues/152 requires updating the root types of minerva response in order for it to be parsed, read and displayed on the Noctua Form. Can you add WBls:0000075 and ZFS:0100000 to minerva m3Batch as root types.

![image](https://user-images.githubusercontent.com/2273929/135935227-a60989a0-b4a2-464f-b1f3-8622f1deac3a.png)

**Comment by vanaukenk** [comment]
@balhoff Yes, you're right and I agree.
  
So, we'd make [WBls:0000075](http://noctua-amigo.berkeleybop.org/amigo/term/WBls:0000075) and [ZFS:0100000](http://noctua-amigo.berkeleybop.org/amigo/term/ZFS:0100000) subclasses of [UBERON:0000105](http://purl.obolibrary.org/obo/UBERON_0000105)?

Also, is [Xenopus developmental stage](http://noctua-amigo.berkeleybop.org/amigo/term/XAO:1000000) also typed as a subclass of [UBERON:0000105](http://purl.obolibrary.org/obo/UBERON_0000105)?

**Comment by vanaukenk** [comment]
Note Noctua form testing ticket:  https://github.com/geneontology/noctua-form/issues/152
