### ISSUE TITLE
Individuals with type = complement does not bring root types

### ISSUE THREAD

**Issue by tmushayahama** [geneontology/minerva#434]
If a NOT qualifier is added, i.e. type is complement then no root types are returned.

![image](https://user-images.githubusercontent.com/2273929/142665152-1e29c5c5-4bb9-40f2-8ab3-daa5158226ca.png)

Just to make sure, I remove the NOT and type is class and the root types are returned 

![image](https://user-images.githubusercontent.com/2273929/142665112-c12b7d21-1902-44cc-b657-0d97da45f2c0.png)

This makes the noctua form not display NOT qualifier

tagging @vanaukenk @ukemi @balhoff

**Comment by vanaukenk** [comment]
@balhoff 
When you are doing minerva work, can you take a look at this one, too?
Many thanks.

**Comment by balhoff** [comment]
A fix for this is merged into `dev`, #451.

**Comment by tmushayahama** [comment]
Thanks @balhoff . I just checked the noctua-dev server and the root type is still empty @kltm is this now on noctua-dev

**Comment by kltm** [comment]
@tmushayahama No request to restart there so not restarted.

**Comment by kltm** [comment]
@tmushayahama @balhoff Restarting now.

**Comment by vanaukenk** [comment]
Tested on production beta with:

http://noctua.geneontology.org/workbench/noctua-form-beta/?model_id=gomodel%3A62183af000000728

Working as expected.
