### ISSUE TITLE
Catch minerva version up to deal with security issues

### ISSUE THREAD

**Issue by kltm** [geneontology/minerva#442]
Catch minerva version up to deal with security issues

**Comment by kltm** [comment]
@balhoff tagging work here

**Comment by kltm** [comment]
https://github.com/geneontology/minerva/pull/439
https://github.com/geneontology/minerva/pull/440

**Comment by kltm** [comment]
Now in testing on `dev`; looks good to me.

**Comment by kltm** [comment]
@vanaukenk While we have no more scheduled outages this year, I'd like to get this out onto `master`/production sooner rather than later.

**Comment by vanaukenk** [comment]
Sounds good @kltm 
Just let me know when you'd like to do this and we can send an email out.

**Comment by kltm** [comment]
@vanaukenk Maybe we can touch bases on this tomorrow during the minerva clearing call? It should be a very minor outage, that could possibly take minutes.

**Comment by kltm** [comment]
After a little testing, @balhoff looking at tuning the logs.

**Comment by kltm** [comment]
@balhoff The changes in #444 seems to have fixed everything from my POV--the logs are back to their previous chattiness.
If you can package that up for `master`, we can get that out on Friday (@vanaukenk ).

**Comment by kltm** [comment]
Out to production and cleared.
