### ISSUE TITLE
Generate blazegraph journal from input ontology for GPAD export

### ISSUE THREAD

**Issue by balhoff** [geneontology/minerva#454]
GPAD export now requires an onto journal input: https://github.com/geneontology/minerva/pull/452/commits/7e4d3080a60663fca0e64f92013f7ce667130f5a

But this may not be convenient, and could possibly be generated from the ontology argument. This new required argument is failing the GO pipeline.

**Comment by kltm** [comment]
When closed, will pass to https://github.com/geneontology/pipeline/issues/270
