### ISSUE TITLE
Root types on minerva-dev need to reflect latest neo build

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/minerva#457]
Hi @balhoff 

@tmushayahama and I are doing some testing on noctua-dev and see that SGD complexes and Complex Portal complexes have different root types.

As an example, for an SGD complex, minerva-dev types this as an information biomacromolecule.  Complex Portal complexes have no root type currently on minerva-dev.

Here's a test model on noctua-dev:  http://noctua-dev.berkeleybop.org/editor/graph/gomodel:6202e3b700000250

Production minerva is showing the correct types for both SGD and Complex Portal complexes of root CC and GO:0032991.

Let us know if you have any questions.

**Comment by balhoff** [comment]
My guess is that the noctu-dev ontology is out of date.

**Comment by kltm** [comment]
Running rebuild cycle on `dev`.

**Comment by vanaukenk** [comment]
Tested on noctua-dev and appears to be working okay:

http://noctua-dev.berkeleybop.org/workbench/noctua-form/?model_id=gomodel%3A621fffab00000027
