### ISSUE TITLE
Migrate obsolete/invalid relations in GO-CAM models

### ISSUE THREAD

**Issue by pgaudet** [geneontology/minerva#460]
For eg 'transports or maintains localization of', 'directly regulates', etc

**Comment by kltm** [comment]
From discussion today, the recording format would be a TSV, in the noctua-models repo, that can be idempotently run.

**Comment by vanaukenk** [comment]
To keep all of the information in one ticket, I'm closing this one in favor of #456.
Note that we also have older tickets for the individual changes that are now part of the project.
