### ISSUE TITLE
add model copy operation

### ISSUE THREAD

**Issue by balhoff** [geneontology/minerva#464]
This will support https://github.com/geneontology/noctua/issues/606.

- Extend batch API with a COPY operation
  - Possibly also expose as an additional REST endpoint (requested by @tmushayahama)
- Perform copy:
  - Create new model
  - Copy all axioms from copied model to new model
  - Remove evidence from all edges
  - Replace contributor and provider on model and all nodes and edges with the user performing the operation
  - Add annotation assertion to new model node: `<NEW_MODEL_IRI> prov:wasDerivedFrom <OLD_MODEL_IRI>`

**Comment by tmushayahama** [comment]
Thanks @balhoff . On a parallel @vanaukenk do you have a workflow in mind from the Noctua Form and Landing Page how this will work?

**Comment by vanaukenk** [comment]
Closing this as the first pass on shallow model copy is done.
