### ISSUE TITLE
Decide on format for find and replace tsv

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/minerva#465]
This ticket is to define the fields we want in a TSV that will be used to apply find and replaced_by changes in GO-CAMs outside of the changes that can be made based on replaced_by tags in an ontology.  For example, this TSV would handle changes to RO terms used based on changes in annotation practice.

Here are 4-5 fields I can think of to include; there may be others:

1. Existing term
2. Replacement term
3. Github handle of requester
4. Link to relevant github ticket
5. Date requested (maybe that could somehow be included automatically?)

@kltm @balhoff @cmungall - anything I'm missing or that you think is not needed?  Thx.

**Comment by balhoff** [comment]
@vanaukenk I would like to have two TSVs: `replace_relations.tsv` and `replace_classes.tsv`. The database change code is pretty different for the two cases. I think that format sounds sufficient.

**Comment by balhoff** [comment]
My preference is to specify terms in the TSV by IRI and not by CURIE, e.g. `http://purl.obolibrary.org/obo/GO_0036268` and not `GO:0036268`. This removes a dependency on which prefixes are configured in Minerva. Does anyone object to this?

**Comment by kltm** [comment]
@balhoff I suppose I'd ask how difficult/annoying that would be?
Generally, with all of the formats we consume and interact with, we use CURIEs. I think it would be nice to continue that here, unless there is an overriding difficulty or other concern.

**Comment by balhoff** [comment]
That's fine, it won't be hard to handle. I suppose the CURIE ship has sailed. :-)

**Comment by kltm** [comment]
@balhoff I think that might be nice. Maybe we could touch bases at some point with @vanaukenk to talk a little about this and update-related (https://github.com/geneontology/noctua/issues/766).

**Comment by vanaukenk** [comment]
@kltm @balhoff 
Wrt scheduling the relations updates, let's plan for the Noctua systems outage on May 12th.  That will give us time to do a test run on noctua-dev to make sure everything's working as expected.

**Comment by balhoff** [comment]
@kltm here are running instructions: https://github.com/geneontology/minerva/pull/478/files#diff-aefb43779e951b6f961416f1195b5d9b753eca8a12a29f64a7a2cd8fb432e63d

**Comment by vanaukenk** [comment]
This work is done.
