### ISSUE TITLE
include git revision and tbox ontology version in status service output

### ISSUE THREAD

**Issue by balhoff** [geneontology/minerva#469]
We frequently have issues that would be clarified by knowing what version of Minerva is running, or what release of the ontology is loaded, e.g. #466.

**Comment by kltm** [comment]
Noting #167

**Comment by kltm** [comment]
@balhoff Do you want to try this out on `dev` first?

**Comment by balhoff** [comment]
Might as well! I've now merged the changes into `dev`.

**Comment by kltm** [comment]
@balhoff Does that look good to you?

**Comment by balhoff** [comment]
Yes, thanks!

**Comment by kltm** [comment]
"Trivial", so moving straight to "Done".
