### ISSUE TITLE
Trace save/flush command and make sure equivalent to --dump-owl-models

### ISSUE THREAD

**Issue by kltm** [geneontology/minerva#475]
In conversation with @balhoff and @vanaukenk today, we'll be changing the minerva outage SOP.
One thing that we'd like to improve would be how models get flushed.

Currently, through the API, we use the `manager.store_all()` command. That maps to the function:

`        var store_req = new request('meta', 'store-all');`

It would be good to trace this through minerva and make sure that

* stopping minerva
* --dump-owl-models

is equivalent to this command.

**Comment by balhoff** [comment]
@kltm can you translate that into a request URL for Minerva? I can find a `store` model-level operation, and an `export-all` operation.

**Comment by kltm** [comment]
@balhoff Okay, digging around a little, you should be interested in `export-all`, going through `m3BatchPrivileged`. If you need the actually URL, I can dig in a bit more (the logger is currently not writing on dev).

**Comment by balhoff** [comment]
`export-all` simply writes all models found in the Blazegraph journal to files. If there are unsaved changes, they will be lost. This calls the same code as the CLI option `dump-owl-models`: https://github.com/geneontology/minerva/blob/daa78af32e316dab534fdc64ba3a2dbfa5f954ad/minerva-core/src/main/java/org/geneontology/minerva/BlazegraphMolecularModelManager.java#L767

Compare:
- https://github.com/geneontology/minerva/blob/daa78af32e316dab534fdc64ba3a2dbfa5f954ad/minerva-server/src/main/java/org/geneontology/minerva/server/handler/JsonOrJsonpBatchHandler.java#L176-L177
  https://github.com/geneontology/minerva/blob/daa78af32e316dab534fdc64ba3a2dbfa5f954ad/minerva-server/src/main/java/org/geneontology/minerva/server/handler/OperationsImpl.java#L698-L700
- https://github.com/geneontology/minerva/blob/daa78af32e316dab534fdc64ba3a2dbfa5f954ad/minerva-cli/src/main/java/org/geneontology/minerva/cli/CommandLineInterface.java#L206
  https://github.com/geneontology/minerva/blob/daa78af32e316dab534fdc64ba3a2dbfa5f954ad/minerva-cli/src/main/java/org/geneontology/minerva/cli/CommandLineInterface.java#L405

**Comment by kltm** [comment]
@balhoff "unsaved changes, they will be lost"--are you saying here that unsaved changes get purged when that method runs?

Either way, the new SOP would be doing the same thing, so I think technically this is completed (although I'd like to get clarification there before closing).

**Comment by balhoff** [comment]
> @balhoff "unsaved changes, they will be lost"--are you saying here that unsaved changes get purged when that method runs?

Oh, no, I mean that unsaved changes are ignored. It just dumps what has been committed to the database.

**Comment by kltm** [comment]
Sounds good--clarification had and I think we're done here. Thank you for tracing that behavior.
