### ISSUE TITLE
Test mock ontology term replacement for new SOP

### ISSUE THREAD

**Issue by kltm** [geneontology/minerva#476]
A place to put results and discussion of a mock run of the new minerva outage SOP.

Related to #456 
Tagging @vanaukenk @balhoff

**Comment by kltm** [comment]
noctua-models branch https://github.com/geneontology/noctua-models/tree/issue-minerva-476-test-replacement

**Comment by kltm** [comment]
For perusal, what a simulated run on noctua-models `master` might look like: https://github.com/geneontology/noctua-models/commits/issue-minerva-476-test-replacement

**Comment by kltm** [comment]
Pinging @vanaukenk @balhoff

**Comment by vanaukenk** [comment]
Decision from the 2022-04-13 Pathways2GO call:

For the time being, GO will update ontology terms in _all_ models with the regular Noctua maintenance outages.

If, in the future, we find that we're diverging too much from Reactome's quarterly releases and this presents potential confusion for users, we can revisit and think about ways to exclude Reactome models from the updates.

Also noted on the call was the known desire for a more human readable diff in the next iteration of this project.

**Comment by balhoff** [comment]
Looks good.
