### ISSUE TITLE
Test mock ontology term replacement for new SOP (II)

### ISSUE THREAD

**Issue by kltm** [geneontology/minerva#479]
A follow on from https://github.com/geneontology/minerva/issues/476

A place to put results and discussion of the second mock run of the new minerva outage SOP.

Related to https://github.com/geneontology/minerva/issues/456
Tagging @vanaukenk @balhoff

**Comment by kltm** [comment]
Working branch https://github.com/geneontology/noctua-models/tree/issue-minerva-479-test-replacement-2

**Comment by kltm** [comment]
Possible future here: https://github.com/geneontology/noctua-models/commits/issue-minerva-479-test-replacement-2
Pinging @vanaukenk and @balhoff

**Comment by vanaukenk** [comment]
@kltm @balhoff @ukemi 
In the latest diff, I'm seeing EMAPA:16627 being replaced with UBERON:0034876.
Is this a case where the EMAPA term was made obsolete and is only available now as an UBERON term?

**Comment by ukemi** [comment]
Hmmmmm. Seems like a problem:
EMAPA:16627 somite 27 sclerotome
EMAPA:16647 is an xref to UBERON:0034876 and as near as I can see should not have been replaced. It's 'live' in MGI.

**Comment by ukemi** [comment]
As near as I can tell, it should not have been replaced.

**Comment by balhoff** [comment]
This term was deprecated within Uberon for some reason. This is definitely a bug in Uberon and shouldn't have happened. I'll file a bug there. We shouldn't run this update.

**Comment by balhoff** [comment]
https://github.com/obophenotype/uberon/issues/2440

**Comment by kltm** [comment]
@balhoff Possibly related question: does minerva do replace operations when `replaced_by` is present during any other operations, or is it only considered when we do the bulk updates? For example, if during "normal" editorial operations I did something with an obsolete term, would minerva ever attempt to replace it?

**Comment by balhoff** [comment]
No. It used to do some automatic replacement to calculate root types for nodes (but not changing the data), but I removed this in the recent performance-improvement PRs.

**Comment by kltm** [comment]
@balhoff Okay great! Something was kicking around in my head about that--thank you for clarifying.

After talking to @vanaukenk we'll go ahead with a reduced SOP today, just: power down, flush, save, remove ontology journal, restart (and have ontology journal build back up).

**Comment by vanaukenk** [comment]
I've added this issue to the 2022-05-02 ontology call; we may also want to discuss on a manager's call.

**Comment by kltm** [comment]
Replaced by #483
