### ISSUE TITLE
Some Chebi Terms not in root types but in NEO

### ISSUE THREAD

**Issue by tmushayahama** [geneontology/minerva#481]
RNAcentral:URS00005EB5B7_9606 doesn't resolve to any root type, but it is in NEO

![image](https://user-images.githubusercontent.com/2273929/167200434-0eecf5ab-fd3a-48dc-829b-c880da2b56bd.png)

**Comment by balhoff** [comment]
This is a NEO issue: https://github.com/geneontology/neo/issues/100
