### ISSUE TITLE
Model Copy: model is not saved on initial copy (modified-p is true). Not searchable on landing page

### ISSUE THREAD

**Issue by tmushayahama** [geneontology/minerva#487]
This will make the model not searchable on landing page using the search api on initial because modified-p is true. Is there a way to add it to the searchable models while modified-p is true of maybe save the model on copy? 

tagging @balhoff @vanaukenk

**Comment by balhoff** [comment]
I implemented this and added to #482.

**Comment by ukemi** [comment]
This morning I made a copy of the Reactome purine catabolism model and did not save it. I went back to the landing page, reloaded and did not see my copy. I also wanted to point out, and I have no idea why this is true, but in testing over the last few days I have forgotten to save my models many times. I don't know why this is particularly true for the copy workflow and maybe it will change once I start adding evidence to the models, but it has happened so far.

**Comment by ukemi** [comment]
I just confirmed that this works from the landing page.

**Comment by vanaukenk** [comment]
This work is done.
