### ISSUE TITLE
Model Copy: Group model metadata is not copied /added of the copied model

### ISSUE THREAD

**Issue by tmushayahama** [geneontology/minerva#488]
After copying a model the contributor's (the one who is doing the copy (new owner) group info is not added. @balhoff @vanaukenk 

![image](https://user-images.githubusercontent.com/2273929/170785633-0a250d6b-f244-4806-8d24-beafe01f1b87.png)

**Comment by vanaukenk** [comment]
@kltm says minerva has no knowledge of users and groups; this is something that's only known by the client

@tmushayahama will wait for @balhoff to investigate the title issue before we decide what to do with groups

**Comment by vanaukenk** [comment]
This work is done; the contributor group is added to the newly copied model.
