### ISSUE TITLE
Copy contributor information in Model Copy operation

### ISSUE THREAD

**Issue by ukemi** [geneontology/minerva#491]
This morning while testing model copy, I copied a model that had a number of MGI curators as contributors on the model. When I copied over the model, I was listed as the only contributor. Is this the behavior we want? It seems like a lot of work can be done before a model gets copied and the curators who made the original model should be given partial credit for the new model. Maybe this has been discussed before.

**Comment by vanaukenk** [comment]
@ukemi 
In the specifications for 'shallow' model copy, we said that only the copier would be listed as a contributor:
https://github.com/geneontology/noctua/issues/606#issuecomment-1067218188
