### ISSUE TITLE
"merge" data is not unique enough to update; all merge operations should contain the model annotations

### ISSUE THREAD

**Issue by kltm** [geneontology/minerva#5]
As it stands now, it seems that if merge data comes back from an operation that did not deal with model annotations (like edge addition), no model annotations are sent back with the merge.

Imagine an model with model annotations and several individuals. If I add an individual, I get back merge data with an individual and no model annotations. Without knowing the initial state, it is not possible to know during an update if I had also deleted all of the model annotations in addition to adding individual.

The only way I can see around this is to always pass back the annotations for the model. Perhaps my case in scratch is wrong?

**Comment by hdietze** [comment]
This was a case of returning a minimal set. There is no technical reason, not to send always all model annotations.

**Comment by kltm** [comment]
Yes, I certainly think is was intentional Once Upon a Time, and probably a good idea. However, now that we have batch actions, there is literally no way of knowing if there was mass model annotation deletion occurring during an operation, so I think it will have to be changed.

**Comment by kltm** [comment]
Cheers!
