### ISSUE TITLE
Annotation from a production model is missing on snapshot

### ISSUE THREAD

**Issue by ukemi** [geneontology/minerva#524]
I 'm trying to figure out where an annotation is going missing.

If I look at the GPAD output from this model directly on Noctua:
http://noctua.geneontology.org/editor/graph/gomodel:61b2b68300000617?

I see this annotation:
MGI	MGI:95805	involved_in	GO:0038133	PMID:11173924	ECO:0000266	RGD:619758		20230714	MGI		contributor=https://orcid.org/0000-0001-7476-6306|model-state=production|noctua-model-id=gomodel:61b2b68300000617

but if I look at the noctua_mgi.gpad file, I can't find it. Can anyone track down where it goes missing?

**Comment by kltm** [comment]
@ukemi Where are you "seeing" this annotation if it is not realized in the noctua_mgi.gpad file? Part of a preview?
As the annotation is not in the gpad file, the place to look would be the minerva code, so @balhoff would be the best place to start.

**Comment by balhoff** [comment]
Snapshot was made July 12, and that annotation has date July 14. Could that be it?

**Comment by ukemi** [comment]
The model has been around for quite a while. Unless the typo in the rat identifier caused the annotation not to be generated but I didn't think were were that smart about the 'with' field.

**Comment by kltm** [comment]
@ukemi This is showing up in the current snapshot "src" and "final" product:
```
MGI     MGI:95805       involved_in     GO:0038133      PMID:11173924   ECO:0000266     RGD:619758              20230714        MGI             contributor=https://orcid.org/0000-0001-7476-6306|model-state=production|noctua-model-id=gomodel:61b2b68300000617
```

**Comment by ukemi** [comment]
@kltm  Excellent. I don't know why it was missing before, but I'll take it that it's there now.
