### ISSUE TITLE
causally_upstream_of _or _within -o- part _of -> causally_upstream_of _or _within

### ISSUE THREAD

**Issue by ukemi** [geneontology/minerva#527]
With the decision to eliminate the 'involved in' terms and convert them to GO-CAM models we are losing information when we convert the GO-CAM to standard annotations. If the original annotation had a GP to term relation of causally_upstream_of_or_within 'blah involved in blac' and it is decomposed to an expression in which the GP is causally upstream of or within blah that is part of blac, only a single annotation is generated to blah. The information about the other process is lost in an annotation extension.

We need to generate annotations to both process as happens when the GP2term relation is part_of.

See http://noctua.geneontology.org/editor/graph/gomodel:64d5781900001000
and the annotation preview for an example.

ping @LiNiMGI

**Comment by balhoff** [comment]
@ukemi are you proposing we add the property chain `causally_upstream_of _or _within o part _of -> causally_upstream_of _or _within`? I think that makes sense. Could you make an RO issue?

**Comment by ukemi** [comment]
Yep. https://github.com/oborel/obo-relations/issues/746

**Comment by balhoff** [comment]
> Do you think we also need
> acts_upstream_of_or_within o part_of -> acts_upstream_of_or_within?

Probably so.

**Comment by kltm** [comment]
@ukemi Is this part of a project, or something else?

**Comment by ukemi** [comment]
Something else. Unless we consider annotation review due to obsoletion a project.

**Comment by ukemi** [comment]
@balhoff knows better than I but I suspect once the property chains are added to RO, the reasoning that is in place will consider them and create the missing annotations.

**Comment by balhoff** [comment]
> @balhoff knows better than I but I suspect once the property chains are added to RO, the reasoning that is in place will consider them and create the missing annotations.

That's true, it should only require changes in RO.

**Comment by pgaudet** [comment]
If this only requires changes in RO, should we close this ticket?

**Comment by balhoff** [comment]
I opened a pull request: https://github.com/oborel/obo-relations/pull/771

**Comment by balhoff** [comment]
This has been merged in RO.
