### ISSUE TITLE
Edge cases when not using validation cause problems, and may potentially bring down server

### ISSUE THREAD

**Issue by kltm** [geneontology/minerva#53]
There needs to be more investigation to see if this is the same thing, or two separate items that just happened to coincide (pretty much down to the minute, but you never know).

At the Hinxton meeting, there were two instances where Minerva became completely unresponsive, after a very brief period of slowing down (a minute or so, if that). On investigation, both times, all cores available on the machine were completely pegged; memory and i/o seemed to be fine. The condition seemed permanent both times and killing was necessary.

Okay, those are the facts. A lot of users were doing a lot of weird things, so the log was not of much use.

Okay, here's my theory about what happened, although this may be a different issue. The night before we had the problem, we turned the validator off so that people could use uniprot ids that were not in NEO. Later on, a user directly input "PPID" as the enabled_by entity for an annoton. Minerva apparently took it, but once it was on disk, was unable to re-read it from disk or perform any operations on it. E.g.:

```
      Error (error): Could not successfully handle batch
      request. Exception:
      org.semanticweb.owlapi.model.OWLRuntimeException. Prefix not
      registered for prefix name: :; your operation was likely not
      performed.
```

I can add the file as it was on disk if desired.

Anyways, working backwards for the second incident, /right/ after this happened, Minerva went nuts. My current belief is that some type of logic operation occurred right after this was input and the fact that it was "unreal" caused havoc.

I can give more details to @balhoff as needed.

I think a minimal fix would be that, even without validation, some kind of CURIE, not just a random string, is needed.

**Comment by cmungall** [comment]
Yes, I think we need two fixes

 1. making minerva robust to failed reads (it should definitely report this up the chain as a serious error, but it shouldn't crash)
 2. even without validation switched on, it should be a valid IRI. 

In theory 2 should not be an issue. It should be impossible at the OWLAPI level to make and save an invalid IRI. However, omn is probably not well tested for edge cases. All the more reason to push ahead with https://github.com/geneontology/noctua-models/issues/14

**Comment by kltm** [comment]
For 1, it does not crash on failed reads, but the failed read prevents getting meta-information for all models and (obviously) information/ops on the problem model. These are indeed reported, but it might be nice to capture these at the minerva end and clean them a bit, rather than just passing the raw error up--it tends to frighten users.

**Comment by kltm** [comment]
While what exactly was going on may never be know, I agree with @balhoff that this is likely an academic frustration now that #58 has been closed.
