### ISSUE TITLE
Constraints on model saving should be clearly documented

### ISSUE THREAD

**Issue by cmungall** [geneontology/minerva#56]
See https://github.com/geneontology/minerva/blob/d8f7fc14a0de376103c96404b8ead328540ae2f7/minerva-server/src/main/java/org/geneontology/minerva/server/validation/BeforeSaveModelValidator.java

The logic is hidden in java. Ideally this would be separated into easily configured rules, e.g. SPARQL or Shex, see #40

**Comment by kltm** [comment]
This would also be great for having things like per-site, or even per-user/org, rules.
