### ISSUE TITLE
Make sure genuine tests run and pass on travis-CI

### ISSUE THREAD

**Issue by cmungall** [geneontology/minerva#57]
#27 was a first pass, but we never actually ran the test step, as it took so long on travis.

All our repos should have non-fake functioning travis checks

**Comment by kltm** [comment]
There is a crack in the .travis.yml:
```yaml
# run tests
# Warning: travis fails, when log output >4M
script:
  - mvn clean compile
```
Is this a travis limitation? I know that test were always done before a master commit, but I didn't realize that travis was compilation only...

**Comment by balhoff** [comment]
I changed to `mvn clean test` in the blazegraph-store branch. However I disabled a bunch of tests and will be adding them back as I make them work properly with the database backend or create slimmed down ontologies to be used in the tests. But at least the working tests will be run.

**Comment by cmungall** [comment]
I note M3ExpressionParserTest could use a slimmed down ontology, it only ever uses two different classes.

We have a slimmed down ontology with PR #48

**Comment by cmungall** [comment]
@yy20716 see #48 for an example of what should be done.

The original tests all imported go-lego.owl which is a massive ontology and not suited for running on travis. For testing all that is required are smaller extracts of ontologies.
