### ISSUE TITLE
GAF/GPAD example model 57c82fad00000643

### ISSUE THREAD

**Issue by ukemi** [geneontology/minerva#60]
This is an example of chaining annotation extensions (column 16) into an annotation line. It is also an example of whether or not we want to make root-node annotations using Noctua. They are not shown here.

GAF model 57c82fad00000643  
MGI MGI:3026877 Ptprh Mmus      GO:0005902  PMID:19170756   EXP     C           gene    taxon:10090 20160920    GO_Noctua   part_of(CL:0000239),part_of(UBERON:0004808)

GPAD model 57c82fad00000643  
MGI MGI:3026877 part_of GO:0005902  PMID:19170756   ECO:0000087         20160920    GO_Noctua   part_of(CL:0000239),part_of(UBERON:0004808) contributor=GOC:hjd

**Comment by balhoff** [comment]
Test job output: https://build.berkeleybop.org/job/export-lego-to-gpad-sparql/lastSuccessfulBuild/artifact/legacy/gpad/57c82fad00000643.gpad/*view*/

**Comment by balhoff** [comment]
The test output is matching your example. It's also including the root-node annotations. I'll go ahead and close this ticket, but please re-open if you see anything amiss.
