### ISSUE TITLE
GAP/GPAD example, most basic, 55dce5d200000074

### ISSUE THREAD

**Issue by cmungall** [geneontology/minerva#61]
http://noctua.berkeleybop.org/editor/graph/gomodel:55dce5d200000074

This example is designed to show a basic structural mapping from LEGO to GPAD, ignoring for now evidence. See the [original spec](https://github.com/geneontology/minerva/blob/master/specs/gaf-to-lego.md)

Focusing on AUX1:

<img width="866" alt="screen shot 2016-09-27 at 2 39 03 pm" src="https://cloud.githubusercontent.com/assets/50745/18892857/2df94b2e-84c0-11e6-8969-b247ad2645e3.png">

GPAD annotations, shown as simple triples:
1. AUX1 enables `auxin influx transmembrane transporter activity` (inferred using inverse of `enabled by`)
2. AUX1 involved-in `carpel development` (inferred using `enables o part-of` in RO)
3. AUX1 part-of (`plasma membrane` and part-of some carpel)

**TODO** - it's not clear the last example can be inferred using property chains in RO. @dosumis do we need to add?

Note the last example also demonstrates the rendering an annotation extension by looking one-ahead.

**Comment by dosumis** [comment]
On 27 Sep 2016, at 22:47, Chris Mungall <notifications@github.com> wrote:

> http://noctua.berkeleybop.org/editor/graph/gomodel:55dce5d200000074
> 
> This example is designed to show a basic structural mapping from LEGO to GPAD, ignoring for now evidence. See the original spec
> 
> Focusing on AUX1:
> 
> 
> 
> GPAD annotations, shown as simple triples:
> 
> AUX1 enables auxin influx transmembrane transporter activity (inferred using inverse of enabled by)
> AUX1 involved-in carpel development (inferred using enables o part-of in RO)
> AUX1 part-of (plasma membrane and part-of some carpel)
> TODO - it's not clear the last example can be inferred using property chains in RO. @dosumis do we need to add?
> 
enabled_by o occurs_in -> part_of seems reasonable.  There may be some circumstances where this breaks down, but I can't think of any offhand.

**Comment by dosumis** [comment]
From discussion in meeting:

All agree to add property chain.

All also agree that complete annotation (which should come with reasoning anyway) =>

AUX1 enables (auxin influx transmembrane transporter activity that (part_of some 'carpel development') and ('occurs in' some 'plasma membrane') and ('occurs in' some 'carpel')
AUX1 involved_in carpel development
AUX1 part-of (plasma membrane and part-of some carpel)

**Comment by balhoff** [comment]
Here's this example after inference. I'm assuming the above-mentioned property chain hasn't been added already. (Sorry the gene names are not being rendered; I tried to put them in the same positions).
![55dce5d200000074_inference](https://cloud.githubusercontent.com/assets/210210/18969704/39457b2c-865c-11e6-85a7-da581aafa7a3.png)

**Comment by balhoff** [comment]
@dosumis @cmungall is there any limit on the relations allowed in the annotation extension? I am trying to figure out how to limit the possible output when inference is working. This is in the context of developing a SPARQL query to output GPAD from the "fully" inferred graph. Otherwise property chains are working quite well with RDFox.

**Comment by dosumis** [comment]
> is there any limit on the relations allowed in the annotation extension?

There are constraints that crudely enforce patterns for extensions in conventional annotation.   These are a closed world version of domain and range as negative constraints (of that makes sense!) We could pull these across, but would need to discuss semantics.

**Comment by balhoff** [comment]
Here is output from the test job: https://build.berkeleybop.org/job/export-lego-to-gpad-sparql/lastSuccessfulBuild/artifact/legacy/gpad/55dce5d200000074.gpad/*view*/

**Comment by dosumis** [comment]
Shall we start up meeting on this again from next Wed?

**Comment by balhoff** [comment]
Sounds good. The output from that Jenkins job will be updated as the code and models change, so it gives us something concrete to look at.

**Comment by vanaukenk** [comment]
Hi,

Yes, I would be in favor of starting up our Wednesday GAF/GPAD output calls again.  Shall we aim for the 18th at 8am PST?

--K.

**Comment by vanaukenk** [comment]
One thing that would make checking GPAD output easier would be to have gene IDs displayed somewhere in the editorial view on Noctua.  It would probably be too much clutter to include them in the box with the activity, but when clicking on the green square, it would be nice to have the gene ID listed next to the entity name.  These IDs are present in the autocomplete list when we first add entities.  I can add a ticket to the Noctua tracker, if this request is more appropriate there.

**Comment by dosumis** [comment]
> On Jan 11, 2017, at 2:38 PM, vanaukenk <notifications@github.com> wrote:
> 
> Hi,
> 
> Yes, I would be in favor of starting up our Wednesday GAF/GPAD output calls again. Shall we aim for the 18th at 8am PST?
> 
> 
Works for me.

**Comment by balhoff** [comment]
@vanaukenk I see what you mean about gene IDs. If you switch to "compact" view, you can then click the green square on the gene node to see the ID. But it is awkward. I would make a ticket for Noctua rather than here.

**Comment by cmungall** [comment]
I notice you're using `|`s in the GPAD, this is OR, which can't yet be expressed in Noctua. Best to use `,`

http://bmcbioinformatics.biomedcentral.com/articles/10.1186/1471-2105-15-155#Sec17

(and should we do an extra layer of reasoner checks on the output?)

**Comment by balhoff** [comment]
Oh, right, thanks: a12ec900e6418ea17d64f485b3254975c22500cb

**Comment by balhoff** [comment]
The [test output](https://build.berkeleybop.org/job/export-lego-to-gpad-sparql/lastSuccessfulBuild/artifact/legacy/gpad/55dce5d200000074.gpad/*view*/) is missing results due to missing evidence in the model. I could either add dummy evidence for verification, or we could just close this issue.
