### ISSUE TITLE
minerva has stopped serving GAF or GPAD from within Noctua

### ISSUE THREAD

**Issue by cmungall** [geneontology/minerva#64]
go to http://noctua.berkeleybop.org/

click on any 'GAF' link. Hangs for a loooong time then returns with a one-line header and no body

same for doing it within a model

not clear where the problem lies. Any idea how to debug @kltm - this is very odd, I don't see how the minimal commits @balhoff made to minerva could have contributed. Has anything changed on the barista/noctua side 

let's see what happens next time this runs:
https://build.berkeleybop.org/job/export-lego-to-legacy/

if that breaks we know it is somehow in the minerva core and not services/plumbing..

**Comment by kltm** [comment]
So far, looking like problems on toaster...

**Comment by kltm** [comment]
The load id 899.68, which is a bit of a record. The issues seems to be minerva itself. I'm going to nuke it and restart.

**Comment by kltm** [comment]
Actually, minerva was an innocent struggling. The galaxy setup went rogue, spawning 990 processes. I'd put money on a bad upstart -> systemd conversion that I did yesterday.
Fixed now, yes?

**Comment by cmungall** [comment]
Fixed, thanks!
