### ISSUE TITLE
GPAD still contains RO identifiers

### ISSUE THREAD

**Issue by ukemi** [geneontology/minerva#65]
In almost all cases the RO identifiers are translated to the text name values that include underscores when they are converted to the GPAD and GAF files. But there are still cases where the RO identifiers sneak in. In the mgi production file, RO:0002413 can be found in the file. We need to be sure that they all are translated for our loads into MGI.

**Comment by cmungall** [comment]
@dosumis @balhoff I don't recall if this is a function of gorel.owl or if we inject the shorthand labels at some other point?

**Comment by balhoff** [comment]
@ukemi do you know a model that will result in the RO:0002413 (directly provides input for (process to process)) in the file?

**Comment by ukemi** [comment]
It's this one:  57c82fad00000358

**Comment by balhoff** [comment]
@cmungall it's here: [AbstractLegoTranslator.getRelId](https://github.com/geneontology/minerva/blob/master/minerva-converter/src/main/java/org/geneontology/minerva/legacy/AbstractLegoTranslator.java#L436)

The call into `Owl2Obo` is returning null. I didn't dig into that yet.

**Comment by balhoff** [comment]
@ukemi thanks that was very helpful!

**Comment by ukemi** [comment]
You are welcome. I will try to remember to add the GAF/GPAD label to these kinds of requests in the future.

**Comment by cmungall** [comment]
I'd like to remove all refs to Owl2Obo and make everything driven by explicit URI contraction and expansion rules, but this may be a big task...

**Comment by balhoff** [comment]
@cmungall I guess this is looking for the value of a `shorthand` annotation that seems to be provided by `go-plus.owl` (you probably knew this but I am figuring it out). So I guess in the immediate term (before developing another system) we need to add annotations in the appropriate source ontology. RO_0002413 is not in go-plus.

**Comment by balhoff** [comment]
@dosumis should a shorthand for RO:0002413 be added to gorel.owl? Is that done one by one as these things pop up?

**Comment by balhoff** [comment]
This was fixed by 8207f67c51d708f599066ad9569dabb12e8f9e09.
