### ISSUE TITLE
Evidence codes in GPAD

### ISSUE THREAD

**Issue by ukemi** [geneontology/minerva#67]
One of the things that we need to do when we load the GPAD file into MGI is to convert the ECO codes from the GPAD file into the three-letter evidence codes that GO uses in the GAF and that we use currently. It seems like this will be a common occurrence for anyone who loads GPAD into a conventional representation. Would it be possible to create a property in the GPAD file that represents the correct three letter GO evidence code? In the long run it would be better to have this in the source file than to have each group do it separately.

**Comment by vanaukenk** [comment]
As an example, here are two lines of GPAD that we get from Protein2GO where Tony has included, in the properties field, the three-letter GO evidence that corresponds to the ECO ID:

UniProtKB   WBGene00019762  A9D4S6  part_of GO:0071014  GO_REF:0000033  ECO:0000318 PANTHER:PTN000133724        20150707    GO_Central      go_evidence=IBA

UniProtKB   A0FLQ8  enables GO:0000977  PMID:24068940   ECO:0000314         20131113    WormBase    happens_during(GO:0030968)|has_direct_input(WB:WBGene00004804)  go_evidence=IDA|id=2113687991|curator_name=Kimberly Van Auken|curator_uri=https://orcid.org/0000-0002-1706-4196

**Comment by balhoff** [comment]
Minerva won't be handling the GPAD-to-GAF conversion, so I think this proposal should be handled downstream, e.g. there could be a job that annotates the GPAD lines with such a `go_evidence` property. Re-open if you disagree.
