### ISSUE TITLE
GAF/GPAD example, includes annotations to root nodes and multiple evidence on an edge

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/minerva#68]
http://noctua.berkeleybop.org/editor/graph/gomodel:57f1b14b00000123

This is a very simple model, but there are two separate lines of evidence for the edge relations.  There are also annotations to the root molecular_function term where I've used the IMP and IGI evidence and annotation extensions for the corresponding BP terms.  Note that this is different from our current use of the ND evidence code for root node annotation, and this particular issue will likely need sorting out at the upcoming GOC meeting.

The reason I don't have the reciprocal annotations for the other gene cited in the With/From field is that these are the first annotations for this gene from WB, so its ID is not yet represented in NEO.  gpi file hopefully coming soon.....

I'm not sure I have the relations correct in the GPAD representation.  I used 'acts causally upstream of or within' for the relation between the gene and the BP, but 'causally upstream of or within' for the molecular function annotation extensions.  The annotation properties are consistent with what WB currently gets from the GPAD file from Protein2GO.  Thx.

GAF annotations:

WB  WBGene00009977  swan-1      GO:0009408  PMID:20940704   IMP     P       F53C11.8    gene    taxon:6239  20161005    GO_Noctua  
WB  WBGene00009977  swan-1      GO:0009408  PMID:20940704   IGI WB:WBGene00009976   P       F53C11.8    gene    taxon:6239  20161005    GO_Noctua  
WB  WBGene00009977  swan-1      GO:0006970  PMID:20940704   IMP     P       F53C11.8    gene    taxon:6239  20161005     GO_Noctua  
WB  WBGene00009977  swan-1      GO:0006970  PMID:20940704   IGI WB:WBGene00009976   P       F53C11.8    gene    taxon:6239  20161005    GO_Noctua   

WB  WBGene00009977  swan-1      GO:0003674  PMID:20940704   IMP     P       F53C11.8    gene    taxon:6239  20161005    GO_Noctua   causally_upstream_of_or_within(GO:0009408)

WB  WBGene00009977  swan-1      GO:0003674  PMID:20940704   IGI WB:WBGene00009976   P       F53C11.8    gene    taxon:6239  20161005    GO_Noctua   causally_upstream_of_or_within(GO:0009408)

WB  WBGene00009977  swan-1      GO:0003674  PMID:20940704   IMP     P       F53C11.8    gene    taxon:6239  20161005    GO_Noctua   causally_upstream_of_or_within(GO:0006970)

WB  WBGene00009977  swan-1      GO:0003674  PMID:20940704   IGI WB:WBGene00009976   P       F53C11.8    gene    taxon:6239  20161005    GO_Noctua   causally_upstream_of_or_within(GO:0006970)

GPAD annotations:

WB  WBGene00009977  acts_upstream_of_or_within  GO:0009408  PMID:20940704   ECO:0000315         20161005    GO_Noctua       go_evidence=IMP|curator_name=Kimberly Van Auken|curator_uri=https://orcid.org/0000-0002-1706-4196

WB  WBGene00009977  acts_upstream_of_or_within  GO:0009408  PMID:20940704   ECO:0000316 WB:WBGene00009976       20161005    GO_Noctua       go_evidence=IGI|curator_name=Kimberly Van Auken|curator_uri=https://orcid.org/0000-0002-1706-4196

WB  WBGene00009977  acts_upstream_of_or_within  GO:0006970  PMID:20940704   ECO:0000315         20161005     GO_Noctua      go_evidence=IMP|curator_name=Kimberly Van Auken|curator_uri=https://orcid.org/0000-0002-1706-4196

WB  WBGene00009977  acts_upstream_of_or_within  GO:0006970  PMID:20940704   ECO:0000316 WB:WBGene00009976       20161005    GO_Noctua       go_evidence=IGI|curator_name=Kimberly Van Auken|curator_uri=https://orcid.org/0000-0002-1706-4196

WB  WBGene00009977  enables GO:0003674  PMID:20940704   ECO:0000315         20161005     GO_Noctua  causally_upstream_of_or_within(GO:0009408)  go_evidence=IMP|curator_name=Kimberly Van Auken|curator_uri=https://orcid.org/0000-0002-1706-4196

WB  WBGene00009977  enables GO:0003674  PMID:20940704   ECO:0000316 WB:WBGene00009976       20161005    GO_Noctua   causally_upstream_of_or_within(GO:0009408)  go_evidence=IGI|curator_name=Kimberly Van Auken|curator_uri=https://orcid.org/0000-0002-1706-4196

WB  WBGene00009977  enables GO:0003674  PMID:20940704   ECO:0000315         20161005    GO_Noctua   causally_upstream_of_or_within(GO:0006970)  go_evidence=IMP|curator_name=Kimberly Van Auken|curator_uri=https://orcid.org/0000-0002-1706-4196

WB  WBGene00009977  enables GO:0003674  PMID:20940704   ECO:0000316 WB:WBGene00009976       20161005    GO_Noctua   causally_upstream_of_or_within(GO:0006970)  go_evidence=IGI|curator_name=Kimberly Van Auken|curator_uri=https://orcid.org/0000-0002-1706-4196

**Comment by balhoff** [comment]
Using SPARQL query to the graphstore, I am getting pretty much exactly what you propose for the GPAD annotations:

```csv
  "pr_type" , "rel_label" , "target_type" , "target_type_label" , "extensions" , "evidence_type" , "with" , "contributor" , "date" , "source" ,
 "http://www.wormbase.org/db/gene/gene?name=WBGene00009977" , "enables" , "http://purl.obolibrary.org/obo/GO_0003674" , "molecular_function" , "causally upstream of or within(response to heat)" , "http://purl.obolibrary.org/obo/ECO_0000315" ,  , "http://orcid.org/0000-0002-1706-4196" , "2016-10-05" , "PMID:20940704 " ,
 "http://www.wormbase.org/db/gene/gene?name=WBGene00009977" , "enables" , "http://purl.obolibrary.org/obo/GO_0003674" , "molecular_function" , "causally upstream of or within(response to heat)" , "http://purl.obolibrary.org/obo/ECO_0000316" , "WB:WBGene00009976" , "http://orcid.org/0000-0002-1706-4196" , "2016-10-05" , "PMID:20940704" ,
 "http://www.wormbase.org/db/gene/gene?name=WBGene00009977" , "enables" , "http://purl.obolibrary.org/obo/GO_0003674" , "molecular_function" , "causally upstream of or within(response to osmotic stress)" , "http://purl.obolibrary.org/obo/ECO_0000315" ,  , "http://orcid.org/0000-0002-1706-4196" , "2016-10-05" , "PMID:20940704 " ,
 "http://www.wormbase.org/db/gene/gene?name=WBGene00009977" , "enables" , "http://purl.obolibrary.org/obo/GO_0003674" , "molecular_function" , "causally upstream of or within(response to osmotic stress)" , "http://purl.obolibrary.org/obo/ECO_0000316" , "WB:WBGene00009976" , "http://orcid.org/0000-0002-1706-4196" , "2016-10-05" , "PMID:20940704" ,
 "http://www.wormbase.org/db/gene/gene?name=WBGene00009977" , "acts upstream of or within" , "http://purl.obolibrary.org/obo/GO_0009408" , "response to heat" , "causally downstream of or within(molecular_function)" , "http://purl.obolibrary.org/obo/ECO_0000315" ,  , "http://orcid.org/0000-0002-1706-4196" , "2016-10-05" , "PMID:20940704 " ,
 "http://www.wormbase.org/db/gene/gene?name=WBGene00009977" , "acts upstream of or within" , "http://purl.obolibrary.org/obo/GO_0009408" , "response to heat" , "causally downstream of or within(molecular_function)" , "http://purl.obolibrary.org/obo/ECO_0000316" , "WB:WBGene00009976" , "http://orcid.org/0000-0002-1706-4196" , "2016-10-05" , "PMID:20940704" ,
 "http://www.wormbase.org/db/gene/gene?name=WBGene00009977" , "acts upstream of or within" , "http://purl.obolibrary.org/obo/GO_0006970" , "response to osmotic stress" , "causally downstream of or within(molecular_function)" , "http://purl.obolibrary.org/obo/ECO_0000315" ,  , "http://orcid.org/0000-0002-1706-4196" , "2016-10-05" , "PMID:20940704 " ,
 "http://www.wormbase.org/db/gene/gene?name=WBGene00009977" , "acts upstream of or within" , "http://purl.obolibrary.org/obo/GO_0006970" , "response to osmotic stress" , "causally downstream of or within(molecular_function)" , "http://purl.obolibrary.org/obo/ECO_0000316" , "WB:WBGene00009976" , "http://orcid.org/0000-0002-1706-4196" , "2016-10-05" , "PMID:20940704" ,
```

**Comment by balhoff** [comment]
The only real difference I see is that an extension is inferred for the `acts upstream of or within` annotations: `causally downstream of or within(molecular_function)`.

**Comment by balhoff** [comment]
Testing output: https://build.berkeleybop.org/job/export-lego-to-gpad-sparql/lastSuccessfulBuild/artifact/legacy/gpad/57f1b14b00000123.gpad/*view*/

There are fewer annotations being output by the test system, probably a result of not including the full RO or missing evidence.

**Comment by balhoff** [comment]
@vanaukenk how does the output for this model look with the current code?

**Comment by vanaukenk** [comment]
This appears to be fixed.  Closing this ticket.
