### ISSUE TITLE
Complexes are showing up in gafs and gpads as annotated objects

### ISSUE THREAD

**Issue by ukemi** [geneontology/minerva#69]
When a complex enables a function, the GO identifier of the complex shows up in the generated gaf and gpad as the annotated object. This shouldn't happen. Instead, if the complex has has_part relations to gene products, those should show up as the annotated objects.

**Comment by balhoff** [comment]
@ukemi could you post an example model for this? I think we would need a new property chain like `part_of o enables -> enables`.

**Comment by ukemi** [comment]
Hi @balhoff 

Here is a good one. 
http://noctua.berkeleybop.org/editor/graph/gomodel:584b49fa00000095
Let me know if it is too complex. If it is, I can make a simple one.

-D

**Comment by balhoff** [comment]
In my version the complex isn't showing up as the annotated object. It is however showing up as a cellular component annotation for each of the gene products:

https://build.berkeleybop.org/job/export-lego-to-gpad-sparql/lastSuccessfulBuild/artifact/legacy/gpad/584b49fa00000095.gpad/*view*/

But we will need some additional semantics to get function annotations for the gene products.

**Comment by ukemi** [comment]
GAF

!gaf-version: 2.0
GO	0000796	condensin complex		GO:0005515	PMID:26166704	IPI	UniProtKB:Q69ZR2	F			gene		20161223	GO_Noctua		
UniProtKB	Q9Y6Q9	NCOA3 Hsap		GO:0003682	PMID:26166704	IDA		F			gene	taxon:9606	20161223	GO_Noctua		
UniProtKB	Q9Y6Q9	NCOA3 Hsap		GO:0071733	PMID:26166704	TAS		P			gene	taxon:9606	20161223	GO_Noctua	part_of(GO:0043627),RO:0002406(GO:0042789)	
GO	0000796	condensin complex		GO:0003682	PMID:26166704	IDA		F			gene		20161214	GO_Noctua	RO:0002406(GO:0003682)	
GO	0000796	condensin complex		GO:0071733	PMID:26166704	IMP	UniProtKB:Q9BPX3	P			gene		20161214	GO_Noctua	part_of(GO:0043627),RO:0002406(GO:0042789)	
GO	0000796	condensin complex		GO:0071733	PMID:26166704	IDA		P			gene		20161214	GO_Noctua	part_of(GO:0043627),RO:0002406(GO:0042789)	
GO	0000796	condensin complex		GO:0071733	PMID:26166704	IMP	UniProtKB:P42695	P			gene		20161214	GO_Noctua	part_of(GO:0043627),RO:0002406(GO:0042789)	
UniProtKB	Q09472	EP300 Hsap		GO:0003682	PMID:26166704	IDA		F			gene	taxon:9606	20161223	GO_Noctua		
UniProtKB	Q09472	EP300 Hsap		GO:0071733	PMID:26166704	TAS		P			gene	taxon:9606	20161223	GO_Noctua	part_of(GO:0043627),RO:0002406(GO:0042789)	
GO	0000796	condensin complex		GO:0030331	PMID:26166704	IDA		F			gene		20161214	GO_Noctua	has_input(UniProtKB:P03372)	
GO	0000796	condensin complex		GO:0030331	PMID:26166704	IDA		F			gene		20161214	GO_Noctua	has_input(UniProtKB:P03372)	
UniProtKB	Q92993	KAT5 Hsap		GO:0003682	PMID:26166704	IDA		F			gene	taxon:9606	20161223	GO_Noctua		
UniProtKB	Q92993	KAT5 Hsap		GO:0071733	PMID:26166704	TAS		P			gene	taxon:9606	20161223	GO_Noctua	part_of(GO:0043627),RO:0002406(GO:0042789)	
UniProtKB	Q9ULT8	HECTD1 Hsap		GO:0005515	PMID:26166704	ISO	UniProtKB:Q69ZR2	F			gene	taxon:9606	20161223	GO_Noctua		
UniProtKB	P03372	ESR1 Hsap		GO:0003682	PMID:26166704	IDA		F			gene	taxon:9606	20161214	GO_Noctua	RO:0002406(GO:0003682)	
UniProtKB	P03372	ESR1 Hsap		GO:0071733	PMID:26166704	IMP	UniProtKB:Q9BPX3	P			gene	taxon:9606	20161214	GO_Noctua	part_of(GO:0043627),RO:0002406(GO:0042789)	
UniProtKB	P03372	ESR1 Hsap		GO:0071733	PMID:26166704	IDA		P			gene	taxon:9606	20161214	GO_Noctua	part_of(GO:0043627),RO:0002406(GO:0042789)	
UniProtKB	P03372	ESR1 Hsap		GO:0071733	PMID:26166704	IMP	UniProtKB:P42695	P			gene	taxon:9606	20161214	GO_Noctua	part_of(GO:0043627),RO:0002406(GO:0042789)	
GO	0000796	condensin complex		GO:0003682	PMID:26166704	IDA		F			gene		20161214	GO_Noctua	RO:0002406(GO:0003682)	
GO	0000796	condensin complex		GO:0071733	PMID:26166704	IMP	UniProtKB:Q9BPX3	P			gene		20161214	GO_Noctua	part_of(GO:0043627),RO:0002406(GO:0042789)	
GO	0000796	condensin complex		GO:0071733	PMID:26166704	IDA		P			gene		20161214	GO_Noctua	part_of(GO:0043627),RO:0002406(GO:0042789)	
GO	0000796	condensin complex		GO:0071733	PMID:26166704	IMP	UniProtKB:P42695	P			gene		20161214	GO_Noctua	part_of(GO:0043627),RO:0002406(GO:0042789)	
UniProtKB	Q15788	NCOA1 Hsap		GO:0003682	PMID:26166704	IDA		F			gene	taxon:9606	20161223	GO_Noctua		
UniProtKB	Q15788	NCOA1 Hsap		GO:0071733	PMID:26166704	TAS		P			gene	taxon:9606	20161223	GO_Noctua	part_of(GO:0043627),RO:0002406(GO:0042789)	
UniProtKB	Q9ULT8	HECTD1 Hsap		GO:0004842	GO_REF:0000033	IBA	PANTHER:PTN000134256	F			gene	taxon:9606	20161223	GO_Noctua	negatively_regulates(GO:0001106)	
UniProtKB	P48552	NRIP1 Hsap		GO:0001106	PMID:26166704	IMP		F			gene	taxon:9606	20161223	GO_Noctua	RO:0002408(GO:0071733)	
GO	0003682	chromatin binding		GO:0003682	PMID:26166704	IDA		F			gene		20161223	GO_Noctua		
GO	0003682	chromatin binding		GO:0071733	PMID:26166704	TAS		P			gene		20161223	GO_Noctua	part_of(GO:0043627),RO:0002406(GO:0042789)

**Comment by ukemi** [comment]
!gpa-version: 1.2
UniProtKB	P48552	enables	GO:0001106	PMID:26166704	ECO:0000315			20161223	GO_Noctua	RO:0002408(GO:0071733)	lego-model-id=gomodel:584b49fa00000095|contributor=http://orcid.org/0000-0001-7476-6306
GO	0000796	enables	GO:0030331	PMID:26166704	ECO:0000314			20161214	GO_Noctua	has_input(UniProtKB:P03372)	lego-model-id=gomodel:584b49fa00000095|contributor=http://orcid.org/0000-0001-7476-6306
GO	0000796	enables	GO:0030331	PMID:26166704	ECO:0000314			20161214	GO_Noctua	has_input(UniProtKB:P03372)	lego-model-id=gomodel:584b49fa00000095|contributor=http://orcid.org/0000-0001-7476-6306
GO	0000796	enables	GO:0005515	PMID:26166704	ECO:0000353	UniProtKB:Q69ZR2		20161223	GO_Noctua		lego-model-id=gomodel:584b49fa00000095|contributor=http://orcid.org/0000-0001-7476-6306
GO	0000796	enables	GO:0003682	PMID:26166704	ECO:0000314			20161214	GO_Noctua	RO:0002406(GO:0003682)	lego-model-id=gomodel:584b49fa00000095|contributor=http://orcid.org/0000-0001-7476-6306
GO	0000796	involved_in	GO:0071733	PMID:26166704	ECO:0000314			20161214	GO_Noctua	part_of(GO:0043627),RO:0002406(GO:0042789)	lego-model-id=gomodel:584b49fa00000095|contributor=http://orcid.org/0000-0001-7476-6306
GO	0000796	involved_in	GO:0071733	PMID:26166704	ECO:0000315	UniProtKB:Q9BPX3		20161214	GO_Noctua	part_of(GO:0043627),RO:0002406(GO:0042789)	lego-model-id=gomodel:584b49fa00000095|contributor=http://orcid.org/0000-0001-7476-6306
GO	0000796	involved_in	GO:0071733	PMID:26166704	ECO:0000315	UniProtKB:P42695		20161214	GO_Noctua	part_of(GO:0043627),RO:0002406(GO:0042789)	lego-model-id=gomodel:584b49fa00000095|contributor=http://orcid.org/0000-0001-7476-6306
GO	0000796	enables	GO:0003682	PMID:26166704	ECO:0000314			20161214	GO_Noctua	RO:0002406(GO:0003682)	lego-model-id=gomodel:584b49fa00000095|contributor=http://orcid.org/0000-0001-7476-6306
GO	0000796	involved_in	GO:0071733	PMID:26166704	ECO:0000314			20161214	GO_Noctua	part_of(GO:0043627),RO:0002406(GO:0042789)	lego-model-id=gomodel:584b49fa00000095|contributor=http://orcid.org/0000-0001-7476-6306
GO	0000796	involved_in	GO:0071733	PMID:26166704	ECO:0000315	UniProtKB:Q9BPX3		20161214	GO_Noctua	part_of(GO:0043627),RO:0002406(GO:0042789)	lego-model-id=gomodel:584b49fa00000095|contributor=http://orcid.org/0000-0001-7476-6306
GO	0000796	involved_in	GO:0071733	PMID:26166704	ECO:0000315	UniProtKB:P42695		20161214	GO_Noctua	part_of(GO:0043627),RO:0002406(GO:0042789)	lego-model-id=gomodel:584b49fa00000095|contributor=http://orcid.org/0000-0001-7476-6306
GO	0003682	enables	GO:0003682	PMID:26166704	ECO:0000314			20161223	GO_Noctua		lego-model-id=gomodel:584b49fa00000095|contributor=http://orcid.org/0000-0001-7476-6306
GO	0003682	involved_in	GO:0071733	PMID:26166704	ECO:0000304			20161223	GO_Noctua	part_of(GO:0043627),RO:0002406(GO:0042789)	lego-model-id=gomodel:584b49fa00000095|contributor=http://orcid.org/0000-0001-7476-6306
UniProtKB	Q15788	enables	GO:0003682	PMID:26166704	ECO:0000314			20161223	GO_Noctua		lego-model-id=gomodel:584b49fa00000095|contributor=http://orcid.org/0000-0001-7476-6306
UniProtKB	Q15788	involved_in	GO:0071733	PMID:26166704	ECO:0000304			20161223	GO_Noctua	part_of(GO:0043627),RO:0002406(GO:0042789)	lego-model-id=gomodel:584b49fa00000095|contributor=http://orcid.org/0000-0001-7476-6306
UniProtKB	Q09472	enables	GO:0003682	PMID:26166704	ECO:0000314			20161223	GO_Noctua		lego-model-id=gomodel:584b49fa00000095|contributor=http://orcid.org/0000-0001-7476-6306
UniProtKB	Q09472	involved_in	GO:0071733	PMID:26166704	ECO:0000304			20161223	GO_Noctua	part_of(GO:0043627),RO:0002406(GO:0042789)	lego-model-id=gomodel:584b49fa00000095|contributor=http://orcid.org/0000-0001-7476-6306
UniProtKB	Q9ULT8	enables	GO:0004842	GO_REF:0000033	ECO:0000318	PANTHER:PTN000134256		20161223	GO_Noctua	negatively_regulates(GO:0001106)	lego-model-id=gomodel:584b49fa00000095|contributor=http://orcid.org/0000-0001-7476-6306
UniProtKB	Q9ULT8	enables	GO:0005515	PMID:26166704	ECO:0000266	UniProtKB:Q69ZR2		20161223	GO_Noctua		lego-model-id=gomodel:584b49fa00000095|contributor=http://orcid.org/0000-0001-7476-6306
UniProtKB	Q92993	enables	GO:0003682	PMID:26166704	ECO:0000314			20161223	GO_Noctua		lego-model-id=gomodel:584b49fa00000095|contributor=http://orcid.org/0000-0001-7476-6306
UniProtKB	Q92993	involved_in	GO:0071733	PMID:26166704	ECO:0000304			20161223	GO_Noctua	part_of(GO:0043627),RO:0002406(GO:0042789)	lego-model-id=gomodel:584b49fa00000095|contributor=http://orcid.org/0000-0001-7476-6306
UniProtKB	Q9Y6Q9	enables	GO:0003682	PMID:26166704	ECO:0000314			20161223	GO_Noctua		lego-model-id=gomodel:584b49fa00000095|contributor=http://orcid.org/0000-0001-7476-6306
UniProtKB	Q9Y6Q9	involved_in	GO:0071733	PMID:26166704	ECO:0000304			20161223	GO_Noctua	part_of(GO:0043627),RO:0002406(GO:0042789)	lego-model-id=gomodel:584b49fa00000095|contributor=http://orcid.org/0000-0001-7476-6306
UniProtKB	P03372	enables	GO:0003682	PMID:26166704	ECO:0000314			20161214	GO_Noctua	RO:0002406(GO:0003682)	lego-model-id=gomodel:584b49fa00000095|contributor=http://orcid.org/0000-0001-7476-6306
UniProtKB	P03372	involved_in	GO:0071733	PMID:26166704	ECO:0000314			20161214	GO_Noctua	part_of(GO:0043627),RO:0002406(GO:0042789)	lego-model-id=gomodel:584b49fa00000095|contributor=http://orcid.org/0000-0001-7476-6306
UniProtKB	P03372	involved_in	GO:0071733	PMID:26166704	ECO:0000315	UniProtKB:Q9BPX3		20161214	GO_Noctua	part_of(GO:0043627),RO:0002406(GO:0042789)	lego-model-id=gomodel:584b49fa00000095|contributor=http://orcid.org/0000-0001-7476-6306
UniProtKB	P03372	involved_in	GO:0071733	PMID:26166704	ECO:0000315	UniProtKB:P42695		20161214	GO_Noctua	part_of(GO:0043627),RO:0002406(GO:0042789)	lego-model-id=gomodel:584b49fa00000095|contributor=http://orcid.org/0000-0001-7476-6306

**Comment by balhoff** [comment]
Hope I didn't confuse you, I mean in the new inferred GPAD system the complexes aren't being annotated.

**Comment by ukemi** [comment]
Ah ok. I'm easily confused. So this one is fixed, sort of.

**Comment by cmungall** [comment]
I think we should be getting contributes-to inferences, from RO:

     P contributes-to F <- P part-of C, C enables F

**Comment by balhoff** [comment]
The closest I can find to this in RO is:

`'part of' o 'capable of' -> 'part of structure that is capable of'`

**Comment by cmungall** [comment]
(in the weeds stuff follows)

And contributes-to is a subproperty of this.

But here is the challenge. capable-of is a pseudo-modal relation. We've never had a satisfactory phrasing of this.

We have an RO expansion

`bearer_of (some realized_by only P)`

Formally we can't do this as a chain because of the only

We do have a chain defined

has-prototype o 'actively participates in' -> capable-of

I think it should actually be has-prototype o enables

TLDR1 - I think we can declare victory on round 1 and handle this on a successive pass 

TLDR2 - there will be a simpler solution using RO, only need capable-of for ontology/TBox axioms. We can frame everything to do with annotation as instance relations.

**Comment by vanaukenk** [comment]
Just need to revisit this issue with another model to make sure this issue is definitely fixed wrt GO protein-containing complexes as annotated objects.

**Comment by vanaukenk** [comment]
I'm closing this ticket for now, as I no longer think we're exporting annotations made to GO protein-containing complex terms or its children.
We still need to shore up guidelines, though, on how to include protein-containing complexes in GO-CAM models.
If need be, we can start another ticket about that and property chains needed to export gene-centric annotations in the corresponding GPAD.
