### ISSUE TITLE
GAF production consistently fails in some situations

### ISSUE THREAD

**Issue by kltm** [geneontology/minerva#75]
During the Noctua training session, for some users working on larger models, they often could not generate GAFs, getting a typical "timeout" error from barista. After some experimentation, it looks like the GAF generation worked better once "warmed-up", with more success after the initial try.

It seems like this may have something to do with either 1) the amount of time that minerva allows the graph store to run a query before terminating it or 2) the increased load with multiple users slowed minerva enough that it could not give a timely response.

**Comment by balhoff** [comment]
There should not be any query timeout on the embedded Blazegraph in Minerva. I have noted that GAF production is quite slow in general (including prior to the switch to Blazegraph). So I would not be surprised if multiple users would overload it. I have been thinking that it would make sense to include RDFox in the GAF production function (using SPARQL as for go-graphstore), regardless of whether RDFox ends up being used in the real-time reasoning features of Minerva.

**Comment by cmungall** [comment]
but this is still using the old minerva gaf generation code, correct?

I'm offline and not sure if there is a ticket describing the overarching 
plan with reasoning, gpad generation, etc.

**Comment by balhoff** [comment]
Closing this as Noctua/Minerva is no longer providing GAF exports.
