### ISSUE TITLE
Annotations not loading into GPAD

### ISSUE THREAD

**Issue by ukemi** [geneontology/minerva#81]
The production model:
http://noctua.berkeleybop.org/editor/graph/gomodel:5835403200000017

has mouse annotations that should be output into the production GPAD file:
https://build.berkeleybop.org/job/export-lego-to-legacy/production/mgi.gpad

From the Noctua tool I can export them directly, so I know they can be generated:

!gpa-version: 1.2
MGI	MGI:98480	enables	GO:0000981	PMID:18550854	ECO:0000314			20161130	GO_Noctua	positively_regulates(GO:0006366)	contributor=http://orcid.org/0000-0001-7476-6306
MGI	MGI:98510	enables	GO:0003700	PMID:16673016	ECO:0000314			20161129	GO_Noctua	positively_regulates(GO:0006366)	contributor=http://orcid.org/0000-0001-7476-6306
MGI	MGI:96677	enables	GO:0005020	MGI:MGI:1859033	ECO:0000314			20161130	GO_Noctua	negatively_regulates(GO:0030218)	contributor=http://orcid.org/0000-0001-7476-6306
MGI	MGI:1923294	enables	GO:0043425	PMID:16673016	ECO:0000314			20161129	GO_Noctua	RO:0002408(GO:0003700),has_input(MGI:MGI:98510)	contributor=http://orcid.org/0000-0001-7476-6306
MGI	MGI:1923294	enables	GO:0043425	PMID:16673016	ECO:0000070			20161129	GO_Noctua	RO:0002408(GO:0003700),has_input(MGI:MGI:98510)	contributor=http://orcid.org/0000-0001-7476-6306
MGI	MGI:1923294	part_of	GO:0005634	PMID:16673016	ECO:0000314			20161129	GO_Noctua		contributor=http://orcid.org/0000-0001-7476-6306
MGI	MGI:1923294	part_of	GO:0005634	PMID:16673016	ECO:0006005			20161129	GO_Noctua		contributor=http://orcid.org/0000-0001-7476-6306
MGI	MGI:1923294	enables	GO:0043425	PMID:16673016	ECO:0000314			20161129	GO_Noctua	has_input(MGI:MGI:98480),RO:0002408(GO:0000981)	contributor=http://orcid.org/0000-0001-7476-6306
MGI	MGI:1923294	enables	GO:0043425	PMID:16673016	ECO:0000070			20161129	GO_Noctua	has_input(MGI:MGI:98480),RO:0002408(GO:0000981)	contributor=http://orcid.org/0000-0001-7476-6306
MGI	MGI:1923294	part_of	GO:0005634	PMID:16673016	ECO:0000314			20161129	GO_Noctua		contributor=http://orcid.org/0000-0001-7476-6306
MGI	MGI:1923294	part_of	GO:0005634	PMID:16673016	ECO:0006005			20161129	GO_Noctua		contributor=http://orcid.org/0000-0001-7476-6306

**Comment by ukemi** [comment]
Hi Jim,

I'm not sure what you guys tweaked yesterday, but my annotations are in the GPAD file today.

-D

**Comment by kltm** [comment]
@balhoff 
...nothing was changed on any public site, except that development AmiGO had a data reload. I don't believe that minerva any long contacts that amigo for id resolution, but that is the only mechanism that has changed in the last 24hrs.
Any thoughts here?

**Comment by balhoff** [comment]
@kltm agree about frustrating non-repeatability! It could be linked to the OWLAPI problem fixed by #83, which has resulted in a couple of models with multiple values for model state.

**Comment by balhoff** [comment]
Seems to have been fixed, probably by the OWL API fixes.
