### ISSUE TITLE
Remove json-model annotation from models

### ISSUE THREAD

**Issue by balhoff** [geneontology/minerva#85]
Minerva adds a JSON version of each model as an annotation value on the model itself. I think this was previously used by epione. These can be "huge" text blobs and don't seem to be needed anymore. Currently they need to be filtered from the list of model annotations so they don't appear in the `Edit annotations` panel in Noctua.

If @kltm and @cmungall can confirm that these JSON blobs are no longer needed, I think it would be good to remove the code that adds them.

**Comment by kltm** [comment]
Okay, let me explain my recollection of the purpose of these blobs is. It's a little more complicated than just epione, but that is a big part of what's going on.

I think this mostly comes down to minerva being a curation and logic engine, not a web server. When we first started getting interest in having noctua models being embedded in external sites, and thinking about what we would do when we started supporting noctua models in AmiGO production, the idea of having tens of thousands of hits against barista/minerva directly for model information was a non-starter.  Given the rest of the infrastructure in place, it made the most sense to have simply keep the models in AmiGO for storage and distribution--people would be using that as an API anyways.

The software evolution up until this point has led us to having two document types for noctua in golr: `noctua_model_meta` and `model_annotation`. The first was produced by epione to run the model search table and run the external services for model discovery; the second was the last remaining in a set of experiments for how noctua curated models could be viewed in AmiGO and is currently loaded by some hacks in owltools. Both of these document types contain an `owl_blob_json` field, and looking at owltools/OWLTools-Solr/src/main/java/owltools/solrj/ModelAnnotationSolrDocumentLoader.java, it seems that they both did this by reading the http://geneontology.org/lego/json-model annotation property from the models, in their own way.

We have done away with epione, which leaves us with `model_annotation` as the last remaining usable API for information delivery. Removing 'json-model' completely should include work on a replacement loader for AmiGO/GOlr that is capable of extracting complete model information.

**Comment by kltm** [comment]
Possibly a dupe with #38, with a little detail about what is going on in minerva.

**Comment by kltm** [comment]
Also geneontology/noctua#275. We'll probably need to reopen loading issues more generally across the board and hopefully coordinate with monarch as well.

**Comment by cmungall** [comment]
AFAICR this essentially comes down to bad design in owltools. To avoid circular dependencies the loader (OWLTools-Solr) can't know anything about Minerva code, so minerva needs to package the json in advance.

**Comment by cmungall** [comment]
Discussed with @balhoff and @kltm 

This is used to populate json-model in the solr document. This is only used in the cyto-view within amigo, which is a useful demo, not required, so the embedded json can go.

**Comment by balhoff** [comment]
Fixed by #95.
