### ISSUE TITLE
Improve mapping to relation IRIs to shorthand labels for GPAD

### ISSUE THREAD

**Issue by balhoff** [geneontology/minerva#87]
In the current GPAD export (and in the Jena-driven version I have developed), relation IRIs are mapped to shorthand labels like "enables" and "negatively_regulates". This works via `Owl2Obo.getIdentifierFromObject`. Calling this for every relation is incredibly slow. This could be better done via a JSON-LD context that maps these relations to the shorthand labels.

I need to see whether the Minerva handling of JSON-LD allows compacting an ID all the way to a "non-curie". This may be a good time to integrate @jnguyenx's [curie-util](https://github.com/prefixcommons/curie-util) (and also see how it handles that aspect of JSON-LD).

But is this mapping appropriately handled via curie mappings/JSON-LD context or instead by just querying the ontology for values for `http://www.geneontology.org/formats/oboInOwl#shorthand`? (This is what Owl2Obo is doing but it could be done much faster in another way). Maybe this is a special case that shouldn't go through the standard curie machinery. @cmungall?

See also #65.

**Comment by cmungall** [comment]
I'm not so keen on relying on oio:shorthand, this introduces an implicit dependency onto an obscure procedure whereby these properties get injected into the ontology via `--add-obo-shorthand-to-properties`.

JSON-LD contexts seem like an elegant mechanism, but may not be quite right here. It introduces an extra point of configuration.

How about ditching the owltools dependency and just having a procedure that is entirely local to GAF/GPAD that looks up the label and adds the underscores?

How does configuring the list of relations we want to be generated in lego->gpad conversion come in here? We *could* have this configuration do double duty, serving as both a filter, and a mapping from IDs to shortforms.

**Comment by balhoff** [comment]
If it is reliable enough for GAF/GPAD consumers to just replace the label with an underscore version, that ought to be straightforward. Since these shorthands are kind of used as identifiers by consumers I thought sticking with the shorthand annotation in the ontology would make it more formal and consistent. I didn't know about that injection procedure, I thought they were hand-edited.

In the meantime I made a little index of of IRI -> shorthand from the ontology within Minerva for use by GAF/GPAD. That should be fast but doesn't really change the overall picture.

Currently there are two lists of relations relevant to LEGO -> GPAD. One is the allowable relations from gene product to GO term. It is hard-coded into the SPARQL query as part of the Minerva source (derived from discussions with you and others). The other list is the relations allowable in annotation extensions. It is also hard-coded in the SPARQL query and was generated from all the properties used in someValuesFrom restrictions in go-plus.

Those lists could be incorporated into a standalone file (ontology?) somewhere which states which of the two uses a property is allowed for and what shorthand to use. I could store this in the Minerva source, or somewhere else. Or the information could be included as annotation assertions within/imported into go-lego (legorel?).

**Comment by cmungall** [comment]
I'm fine with having the SPARQL query be the config here. Easy to extend

**Comment by balhoff** [comment]
Added local transformation of labels in 8207f67c51d708f599066ad9569dabb12e8f9e09.
