### ISSUE TITLE
Report release version via --version argument

### ISSUE THREAD

**Issue by balhoff** [geneontology/minerva#89]

**Comment by kltm** [comment]
😄

**Comment by kltm** [comment]
I was just wondering how your fix interacted with the current implementation:
```
sjcarbon@moiraine:~/local/src/git/noctua[master]$:) java -jar ./java/lib/minerva-cli.jar --version
git-revision-sha1	d78e4e2f88a302eebe7d4603f8243dd6fc86263c
git-revision-url	https://github.com/geneontology/minerva/commit/d78e4e2f88a302eebe7d4603f8243dd6fc86263c
git-branch	master
git-dirty	true
sjcarbon@moiraine:~/local/src/git/noctua[master]$:) 
```
Does it just print in the minerva level and then pass off to the owltools runner (as is done for the minerva version above)?

**Comment by balhoff** [comment]
Oh wow, thanks for pointing this out. I completely forgot that there are options coming from owltools. Let's leave this open until I sort that out.

**Comment by cmungall** [comment]
I wouldn't be sad if minerva ended up with its own independent CLI... 
whatever makes sense

**Comment by kltm** [comment]
We'd still want the github hash in minerva (noctua) and owltools (amigo) as that it the most certain way to determine what is going on with the code--versioning can have mistakes, the hash though...

**Comment by balhoff** [comment]
Minerva command runner extends owltools JS command runner extends owlsim2 command runner extends owlsim command runner extends Solr/GOlr command runner extends taxon constraints command runner extends GAF command runner extends CommandRunner extends CommandRunnerBase.

I hadn't noticed this. :-)

**Comment by kltm** [comment]
I hope you like turtles... 
🐢
 🐢
 🐢
 🐢
 ...

**Comment by balhoff** [comment]
I don't think this is needed—I had overlooked the already existing option.
