### ISSUE TITLE
Implement ObjectPropertyAssertion reasoning

### ISSUE THREAD

**Issue by cmungall** [geneontology/minerva#9]
Elk does not implement OPA reasoning. Either
- evaluate other reasoner, e.g. Konklude
- use a modularization strategy, either within the reasoner (e.g. MORE) or our own wrapper (e.g. SLME+Hermit)
- Write a forward chaining OPA reasoner on top of Elk; simply iterate through adding OPAs based on rules derived from the EL spec (e.g. transitivity) until saturation

consult @dosumis for advice

**Comment by cmungall** [comment]
Required for examples in https://github.com/geneontology/noctua/issues/3

**Comment by hdietze** [comment]
The minerva server now supports the usage of HermiT and SLME. 
I already had the SLME option implement, in case we needed it to minimize the memory foot print for each model (reasoner).

The first tests reveal that the SLME is a performance bottle neck. Using the SLME (ELK or HermiT as reasoner) approach, the runtime of the tests significantly increases (112 seconds vs 290 seconds ~ x2.6)
Once the module is extracted, the runtime difference between ELK and Hermit appears to be about 1-2% slower using HermiT.

Also running HermiT without the SLME is impossible (out-of-memory)

**Comment by goodb** [comment]
@balhoff I think this can be closed as Arachne does this, yes?

**Comment by balhoff** [comment]
Agree.
