### ISSUE TITLE
Update Models before merging relations

### ISSUE THREAD

**Issue by ukemi** [geneontology/minerva#91]
https://github.com/geneontology/go-ontology/issues/12811

We need to update all of the existing models so that they will not contain outdated properties once the merge in the above ticket is completed. Please check the task in the above ticket once the update is complete.

**Comment by balhoff** [comment]
@cmungall I think these 4 updates should do it:

```sparql
PREFIX directly_activates: <http://purl.obolibrary.org/obo/RO_0002406>
PREFIX directly_positively_regulates: <http://purl.obolibrary.org/obo/RO_0002629>
DELETE { 
    GRAPH ?g { ?s directly_activates: ?o . }
}
INSERT { 
    GRAPH ?g { ?s directly_positively_regulates: ?o . }
}
WHERE {
    GRAPH ?g { ?s directly_activates: ?o . }
} 
```

```sparql
PREFIX directly_activates: <http://purl.obolibrary.org/obo/RO_0002406>
PREFIX directly_positively_regulates: <http://purl.obolibrary.org/obo/RO_0002629>
DELETE { 
    GRAPH ?g { ?s ?p directly_activates: . }
}
INSERT { 
    GRAPH ?g { ?s ?p directly_positively_regulates: . }
}
WHERE {
    GRAPH ?g { ?s ?p directly_activates: . }
} 
```

```sparql
PREFIX directly_inhibits: <http://purl.obolibrary.org/obo/RO_0002408>
PREFIX directly_negatively_regulates: <http://purl.obolibrary.org/obo/RO_0002630>
DELETE { 
    GRAPH ?g { ?s directly_inhibits: ?o . }
}
INSERT { 
    GRAPH ?g { ?s directly_negatively_regulates: ?o . }
}
WHERE {
    GRAPH ?g { ?s directly_inhibits: ?o . }
} 
```

```sparql
PREFIX directly_inhibits: <http://purl.obolibrary.org/obo/RO_0002408>
PREFIX directly_negatively_regulates: <http://purl.obolibrary.org/obo/RO_0002630>
DELETE { 
    GRAPH ?g { ?s ?p directly_inhibits: . }
}
INSERT { 
    GRAPH ?g { ?s ?p directly_negatively_regulates: . }
}
WHERE {
    GRAPH ?g { ?s ?p directly_inhibits: . }
} 
```

**Comment by balhoff** [comment]
@kltm we should coordinate a time to bring Noctua down while I do this update. Should just take a few minutes.

**Comment by kltm** [comment]
@balhoff To clarify, this will be:
* bring the system down
* update the models in-place
* destroy/re-create journal
* restart system
yes?

**Comment by balhoff** [comment]
* Bring the system down
* Copy the journal file elsewhere to run SPARQL server
* Run update
* Stop SPARQL server
* Move updated journal in place of old journal
* Restart system

**Comment by kltm** [comment]
Fair enough. Do you want to run the server/migration, or do you have a command for me?

**Comment by balhoff** [comment]
Actually, now that I think about this more I think it would be worth holding off and first implementing a command line to just run the SPARQL update via the minerva jar (instead of starting up the actual Blazegraph server). If you haven't already started kicking people off, we could delay this until tomorrow and I'll create that command first.

**Comment by kltm** [comment]
Sounds good to me! If what you put in could be generalized to make doing these types of operations in the future more plug-and-play, that would be great--this will probably be a work pattern that comes up a lot.

**Comment by balhoff** [comment]
@kltm yes exactly.

**Comment by balhoff** [comment]
Completed by https://github.com/geneontology/noctua/issues/431
