### ISSUE TITLE
Create a method for passing SPARQL to Minerva's Blazegraph

### ISSUE THREAD

**Issue by kltm** [geneontology/minerva#93]
Just like the passing of other special Minerva commands (like the "periphery" ops, see `query` stub in https://github.com/berkeleybop/bbop-manager-minerva/wiki/MinervaRequestAPI), Minerva should be able to accept SPARQL queries.

One thing to keep in mind here is that Minerva probably needs to be aware enough about what is going on to pass back the proper response to meet expectations; e.g. things that update need to send (maybe) "rebuild", etc.

**Comment by balhoff** [comment]
Something to consider is whether this needs to take into account unsaved model state. SPARQL can only query over what's been written into the database. Related, we've discussed writing reasoner results into the database after each change, to support SPARQL. Currently the reasoner uses an in-memory Jena model, which enables reasoning results for unsaved model state. Perhaps we need to keep both.

**Comment by goodb** [comment]
Hi @balhoff just pinging that priority for this one is raised as it is now considered a blocker for https://github.com/geneontology/noctua/issues/484 which is on the shortlist for things to improve before Montreal meeting.  @kltm @cmungall @lpalbou
