### ISSUE TITLE
Revise GPAD inference approach

### ISSUE THREAD

**Issue by balhoff** [geneontology/minerva#96]
The latest version of the SPARQL+inference-driven GPAD export uses Jena rules to infer direct annotation relations (R, e.g. `enables`, `involved in`, etc.) between gene products (X) and GO term instances (Y). For each annotation relation, an inference explanation is computed to determine the asserted statements required for the inference. The current code simply collects all available evidence annotations from any of those asserted statements, and outputs an annotation X R Y for each evidence. This can result in some undesirable output, for example annotations using evidence across different papers.

We will refine the approach in the following ways:
1. For an annotation to be generated at all, every asserted relation required for the annotation relation (i.e. in the explanation) must have an attached evidence.
2. The evidence used for the annotation relation will be any evidence on an asserted relation (found in the explanation) which has the GO term instance as a subject or object.
3. Annotation extensions will only be included in the annotation if all asserted relations within the explanation of the extension relation have an evidence referencing the same paper as the primary evidence in the annotation.

The annotation extension criteria (3) can become complicated. For example:
```turtle
[a MF] enabled_by [a GP] ;
    occurs_in [a CC1;
               part_of [a CC2;
                        part_of [a CC3]
                       ]
              ] .
```
We can infer the annotation:
```turtle
[a GP] part_of [a CC1] .
```
Potential annotation extensions are `part_of(CC2), part_of(CC3)`. Now for each extension relation, eg. ```[a CC1] part_of [a CC3]```, we have to compute the explanation and make sure all involved relations have evidence and that the evidence is from the same paper as the primary annotation evidence.

**Comment by balhoff** [comment]
@cmungall @dosumis @vanaukenk @ukemi does this match your recollection of our conclusion?

**Comment by ukemi** [comment]
Perfect!

**Comment by vanaukenk** [comment]
Yes, @balhoff that is consistent with what we said this morning.  Thanks for the excellent summary!

**Comment by balhoff** [comment]
This has been done for a while.
